package org.jxapi.generator.java.exchange.api.ws;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.gen.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.gen.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.gen.WebsocketEndpointDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.JavaCodeGenUtil;
import org.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;
import org.jxapi.generator.java.exchange.ExchangeGenUtil;
import org.jxapi.util.PlaceHolderResolver;

/**
 * Unit test for {@link WebsocketEndpointClassesGenerator}
 */
public class WebsocketEndpointClassesGeneratorTest {
  
  private static final Path BASE_PKG = Paths.get("com", "foo", "bar", "gen", "marketdata");
  
  private Path srcFolder;
  
  @After
  public void tearDown() throws IOException {
    if (srcFolder != null) {
      JavaCodeGenUtil.deletePath(srcFolder);
      srcFolder = null;
    }
  }
  
  private void checkJavaFilesCount(Path relativePkg, int count) {
    ClassesGeneratorTestUtil.checkJavaFilesCount(srcFolder.resolve(BASE_PKG).resolve(relativePkg), count);
  }
  
  private Path checkSourceFileExists(Path srcFilePath) {
    return ClassesGeneratorTestUtil.checkSourceFileExists(srcFolder.resolve(BASE_PKG), srcFilePath);
  }

  @Test
  public void testGenerateWebsocketEndpointClasses() throws IOException {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    WebsocketEndpointDescriptor wsEndpoint = api.getWebsocketEndpoints().get(0);
    PlaceHolderResolver docPlaceHolderResolver = 
        PlaceHolderResolver.create(ExchangeGenUtil.getDescriptionReplacements(exchange));
    WebsocketEndpointClassesGenerator generator = new WebsocketEndpointClassesGenerator(exchange, api, wsEndpoint, docPlaceHolderResolver);
    generator.generateClasses(srcFolder);
    
    checkJavaFilesCount(Paths.get("pojo/deserializers"), 2);
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataTickerStreamMessageDeserializer.java"));
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataTickerStreamRequestDeserializer.java"));
    
    checkJavaFilesCount(Paths.get("pojo"), 4);
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataTickerStreamRequestDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataTickerStreamRequestSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Request parameters for subscribing to ticker stream. Use {@link com.foo.bar.gen.MyTestExchangeConstants#ALL_TICKERS} to subscribe to every ticker. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataTickerStreamRequestSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataTickerStreamRequestDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataTickerStreamRequest implements Pojo<MyTestExchangeMarketDataTickerStreamRequest> {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -1518904708630110389L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataTickerStreamRequest} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private String symbol;\n"
        + "  private String apiKey;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Symbol to subscribe to ticker stream of. Use {@link com.foo.bar.gen.MyTestExchangeConstants#ALL_TICKERS} to subscribe to every ticker. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public String getSymbol() {\n"
        + "    return symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param symbol Symbol to subscribe to ticker stream of. Use {@link com.foo.bar.gen.MyTestExchangeConstants#ALL_TICKERS} to subscribe to every ticker. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public void setSymbol(String symbol) {\n"
        + "    this.symbol = symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return API key, see {@link com.foo.bar.gen.MyTestExchangeProperties#API_KEY}\n"
        + "   */\n"
        + "  public String getApiKey() {\n"
        + "    return apiKey;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param apiKey API key, see {@link com.foo.bar.gen.MyTestExchangeProperties#API_KEY}\n"
        + "   */\n"
        + "  public void setApiKey(String apiKey) {\n"
        + "    this.apiKey = apiKey;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataTickerStreamRequest o = (MyTestExchangeMarketDataTickerStreamRequest) other;\n"
        + "    return Objects.equals(this.symbol, o.symbol)\n"
        + "        && Objects.equals(this.apiKey, o.apiKey);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataTickerStreamRequest other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.symbol, other.symbol);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.apiKey, other.apiKey);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(symbol, apiKey);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataTickerStreamRequest deepClone() {\n"
        + "    MyTestExchangeMarketDataTickerStreamRequest clone = new MyTestExchangeMarketDataTickerStreamRequest();\n"
        + "    clone.symbol = this.symbol;\n"
        + "    clone.apiKey = this.apiKey;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataTickerStreamRequest}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private String symbol;\n"
        + "    private String apiKey;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>symbol</code> field in the builder\n"
        + "     * @param symbol Symbol to subscribe to ticker stream of. Use {@link com.foo.bar.gen.MyTestExchangeConstants#ALL_TICKERS} to subscribe to every ticker. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setSymbol(String)\n"
        + "     */\n"
        + "    public Builder symbol(String symbol)  {\n"
        + "      this.symbol = symbol;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>apiKey</code> field in the builder\n"
        + "     * @param apiKey API key, see {@link com.foo.bar.gen.MyTestExchangeProperties#API_KEY}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setApiKey(String)\n"
        + "     */\n"
        + "    public Builder apiKey(String apiKey)  {\n"
        + "      this.apiKey = apiKey;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataTickerStreamRequest using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataTickerStreamRequest build() {\n"
        + "      MyTestExchangeMarketDataTickerStreamRequest res = new MyTestExchangeMarketDataTickerStreamRequest();\n"
        + "      res.symbol = this.symbol;\n"
        + "      res.apiKey = this.apiKey;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataTickerStreamRequest.java"))));
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.math.BigDecimal;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataTickerStreamMessageDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataTickerStreamMessageSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Ticker message. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataTickerStreamMessageSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataTickerStreamMessageDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataTickerStreamMessage implements Pojo<MyTestExchangeMarketDataTickerStreamMessage> {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -5198810711898892549L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataTickerStreamMessage} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private String topic;\n"
        + "  private String symbol;\n"
        + "  private Long timestamp;\n"
        + "  private BigDecimal priceChange;\n"
        + "  private BigDecimal priceChangePercent;\n"
        + "  private BigDecimal last;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Topic. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>t</strong>\n"
        + "   */\n"
        + "  public String getTopic() {\n"
        + "    return topic;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param topic Topic. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>t</strong>\n"
        + "   */\n"
        + "  public void setTopic(String topic) {\n"
        + "    this.topic = topic;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Symbol name. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>s</strong>\n"
        + "   */\n"
        + "  public String getSymbol() {\n"
        + "    return symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param symbol Symbol name. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>s</strong>\n"
        + "   */\n"
        + "  public void setSymbol(String symbol) {\n"
        + "    this.symbol = symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Timestamp of the message. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>T</strong>\n"
        + "   */\n"
        + "  public Long getTimestamp() {\n"
        + "    return timestamp;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param timestamp Timestamp of the message. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>T</strong>\n"
        + "   */\n"
        + "  public void setTimestamp(Long timestamp) {\n"
        + "    this.timestamp = timestamp;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Price change in the last 24 hours. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>p</strong>\n"
        + "   */\n"
        + "  public BigDecimal getPriceChange() {\n"
        + "    return priceChange;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param priceChange Price change in the last 24 hours. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>p</strong>\n"
        + "   */\n"
        + "  public void setPriceChange(BigDecimal priceChange) {\n"
        + "    this.priceChange = priceChange;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Price change percent in the last 24 hours. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>P</strong>\n"
        + "   */\n"
        + "  public BigDecimal getPriceChangePercent() {\n"
        + "    return priceChangePercent;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param priceChangePercent Price change percent in the last 24 hours. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>P</strong>\n"
        + "   */\n"
        + "  public void setPriceChangePercent(BigDecimal priceChangePercent) {\n"
        + "    this.priceChangePercent = priceChangePercent;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Last traded price. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>p</strong>\n"
        + "   */\n"
        + "  public BigDecimal getLast() {\n"
        + "    return last;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param last Last traded price. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} <br>Message field <strong>p</strong>\n"
        + "   */\n"
        + "  public void setLast(BigDecimal last) {\n"
        + "    this.last = last;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataTickerStreamMessage o = (MyTestExchangeMarketDataTickerStreamMessage) other;\n"
        + "    return Objects.equals(this.topic, o.topic)\n"
        + "        && Objects.equals(this.symbol, o.symbol)\n"
        + "        && Objects.equals(this.timestamp, o.timestamp)\n"
        + "        && Objects.equals(this.priceChange, o.priceChange)\n"
        + "        && Objects.equals(this.priceChangePercent, o.priceChangePercent)\n"
        + "        && Objects.equals(this.last, o.last);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataTickerStreamMessage other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.topic, other.topic);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.symbol, other.symbol);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.timestamp, other.timestamp);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.priceChange, other.priceChange);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.priceChangePercent, other.priceChangePercent);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.last, other.last);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(topic, symbol, timestamp, priceChange, priceChangePercent, last);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataTickerStreamMessage deepClone() {\n"
        + "    MyTestExchangeMarketDataTickerStreamMessage clone = new MyTestExchangeMarketDataTickerStreamMessage();\n"
        + "    clone.topic = this.topic;\n"
        + "    clone.symbol = this.symbol;\n"
        + "    clone.timestamp = this.timestamp;\n"
        + "    clone.priceChange = this.priceChange;\n"
        + "    clone.priceChangePercent = this.priceChangePercent;\n"
        + "    clone.last = this.last;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataTickerStreamMessage}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private String topic;\n"
        + "    private String symbol;\n"
        + "    private Long timestamp;\n"
        + "    private BigDecimal priceChange;\n"
        + "    private BigDecimal priceChangePercent;\n"
        + "    private BigDecimal last;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>topic</code> field in the builder\n"
        + "     * @param topic Topic. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} Message field <strong>t</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setTopic(String)\n"
        + "     */\n"
        + "    public Builder topic(String topic)  {\n"
        + "      this.topic = topic;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>symbol</code> field in the builder\n"
        + "     * @param symbol Symbol name. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} Message field <strong>s</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setSymbol(String)\n"
        + "     */\n"
        + "    public Builder symbol(String symbol)  {\n"
        + "      this.symbol = symbol;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>timestamp</code> field in the builder\n"
        + "     * @param timestamp Timestamp of the message. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} Message field <strong>T</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setTimestamp(Long)\n"
        + "     */\n"
        + "    public Builder timestamp(Long timestamp)  {\n"
        + "      this.timestamp = timestamp;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>priceChange</code> field in the builder\n"
        + "     * @param priceChange Price change in the last 24 hours. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} Message field <strong>p</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setPriceChange(BigDecimal)\n"
        + "     */\n"
        + "    public Builder priceChange(BigDecimal priceChange)  {\n"
        + "      this.priceChange = priceChange;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>priceChangePercent</code> field in the builder\n"
        + "     * @param priceChangePercent Price change percent in the last 24 hours. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} Message field <strong>P</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setPriceChangePercent(BigDecimal)\n"
        + "     */\n"
        + "    public Builder priceChangePercent(BigDecimal priceChangePercent)  {\n"
        + "      this.priceChangePercent = priceChangePercent;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>last</code> field in the builder\n"
        + "     * @param last Last traded price. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME} Message field <strong>p</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setLast(BigDecimal)\n"
        + "     */\n"
        + "    public Builder last(BigDecimal last)  {\n"
        + "      this.last = last;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataTickerStreamMessage using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataTickerStreamMessage build() {\n"
        + "      MyTestExchangeMarketDataTickerStreamMessage res = new MyTestExchangeMarketDataTickerStreamMessage();\n"
        + "      res.topic = this.topic;\n"
        + "      res.symbol = this.symbol;\n"
        + "      res.timestamp = this.timestamp;\n"
        + "      res.priceChange = this.priceChange;\n"
        + "      res.priceChangePercent = this.priceChangePercent;\n"
        + "      res.last = this.last;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataTickerStreamMessage.java"))));
    
    checkJavaFilesCount(Paths.get("pojo/serializers"), 2);
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataTickerStreamRequestSerializer.java"));
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataTickerStreamMessageSerializer.java"));
  }
  
  @Test
  public void testGenerateWebsocketEndpointWithRequestAndMessageImplementingCustomInterfaces() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithRequestAndResponseImplementingCustomInterfaces.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    WebsocketEndpointDescriptor wsEndpoint = api.getWebsocketEndpoints().get(0);
    WebsocketEndpointClassesGenerator generator = new WebsocketEndpointClassesGenerator(exchange, api, wsEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(Paths.get("pojo/deserializers"), 2);
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataTickerStreamMessageDeserializer.java"));
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataTickerStreamRequestDeserializer.java"));
    
    checkJavaFilesCount(Paths.get("pojo"), 4);
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.TickerStreamRequestInterface1;\n"
        + "import com.foo.bar.TickerStreamRequestInterface2;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataTickerStreamRequestDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataTickerStreamRequestSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Ticker stream subscription request\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataTickerStreamRequestSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataTickerStreamRequestDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataTickerStreamRequest implements Pojo<MyTestExchangeMarketDataTickerStreamRequest>, TickerStreamRequestInterface1, TickerStreamRequestInterface2 {\n"
        + "  \n"
        + "  private static final long serialVersionUID = 8012256550868394115L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataTickerStreamRequest} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private String symbol;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Symbol to subscribe to ticker stream of\n"
        + "   */\n"
        + "  public String getSymbol() {\n"
        + "    return symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param symbol Symbol to subscribe to ticker stream of\n"
        + "   */\n"
        + "  public void setSymbol(String symbol) {\n"
        + "    this.symbol = symbol;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataTickerStreamRequest o = (MyTestExchangeMarketDataTickerStreamRequest) other;\n"
        + "    return Objects.equals(this.symbol, o.symbol);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataTickerStreamRequest other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.symbol, other.symbol);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(symbol);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataTickerStreamRequest deepClone() {\n"
        + "    MyTestExchangeMarketDataTickerStreamRequest clone = new MyTestExchangeMarketDataTickerStreamRequest();\n"
        + "    clone.symbol = this.symbol;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataTickerStreamRequest}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private String symbol;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>symbol</code> field in the builder\n"
        + "     * @param symbol Symbol to subscribe to ticker stream of\n"
        + "     * @return Builder instance\n"
        + "     * @see #setSymbol(String)\n"
        + "     */\n"
        + "    public Builder symbol(String symbol)  {\n"
        + "      this.symbol = symbol;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataTickerStreamRequest using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataTickerStreamRequest build() {\n"
        + "      MyTestExchangeMarketDataTickerStreamRequest res = new MyTestExchangeMarketDataTickerStreamRequest();\n"
        + "      res.symbol = this.symbol;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataTickerStreamRequest.java"))));
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.math.BigDecimal;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.TickerStreamResponseInterface1;\n"
        + "import com.foo.bar.TickerStreamResponseInterface2;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataTickerStreamMessageDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataTickerStreamMessageSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Ticker stream message\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataTickerStreamMessageSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataTickerStreamMessageDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataTickerStreamMessage implements Pojo<MyTestExchangeMarketDataTickerStreamMessage>, TickerStreamResponseInterface1, TickerStreamResponseInterface2 {\n"
        + "  \n"
        + "  private static final long serialVersionUID = 1671784664167570937L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataTickerStreamMessage} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private String topic;\n"
        + "  private String symbol;\n"
        + "  private BigDecimal last;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Topic <br>Message field <strong>t</strong>\n"
        + "   */\n"
        + "  public String getTopic() {\n"
        + "    return topic;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param topic Topic <br>Message field <strong>t</strong>\n"
        + "   */\n"
        + "  public void setTopic(String topic) {\n"
        + "    this.topic = topic;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Symbol name <br>Message field <strong>s</strong>\n"
        + "   */\n"
        + "  public String getSymbol() {\n"
        + "    return symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param symbol Symbol name <br>Message field <strong>s</strong>\n"
        + "   */\n"
        + "  public void setSymbol(String symbol) {\n"
        + "    this.symbol = symbol;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Last traded price <br>Message field <strong>p</strong>\n"
        + "   */\n"
        + "  public BigDecimal getLast() {\n"
        + "    return last;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param last Last traded price <br>Message field <strong>p</strong>\n"
        + "   */\n"
        + "  public void setLast(BigDecimal last) {\n"
        + "    this.last = last;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataTickerStreamMessage o = (MyTestExchangeMarketDataTickerStreamMessage) other;\n"
        + "    return Objects.equals(this.topic, o.topic)\n"
        + "        && Objects.equals(this.symbol, o.symbol)\n"
        + "        && Objects.equals(this.last, o.last);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataTickerStreamMessage other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.topic, other.topic);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.symbol, other.symbol);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.last, other.last);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(topic, symbol, last);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataTickerStreamMessage deepClone() {\n"
        + "    MyTestExchangeMarketDataTickerStreamMessage clone = new MyTestExchangeMarketDataTickerStreamMessage();\n"
        + "    clone.topic = this.topic;\n"
        + "    clone.symbol = this.symbol;\n"
        + "    clone.last = this.last;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataTickerStreamMessage}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private String topic;\n"
        + "    private String symbol;\n"
        + "    private BigDecimal last;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>topic</code> field in the builder\n"
        + "     * @param topic Topic Message field <strong>t</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setTopic(String)\n"
        + "     */\n"
        + "    public Builder topic(String topic)  {\n"
        + "      this.topic = topic;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>symbol</code> field in the builder\n"
        + "     * @param symbol Symbol name Message field <strong>s</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setSymbol(String)\n"
        + "     */\n"
        + "    public Builder symbol(String symbol)  {\n"
        + "      this.symbol = symbol;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>last</code> field in the builder\n"
        + "     * @param last Last traded price Message field <strong>p</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setLast(BigDecimal)\n"
        + "     */\n"
        + "    public Builder last(BigDecimal last)  {\n"
        + "      this.last = last;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataTickerStreamMessage using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataTickerStreamMessage build() {\n"
        + "      MyTestExchangeMarketDataTickerStreamMessage res = new MyTestExchangeMarketDataTickerStreamMessage();\n"
        + "      res.topic = this.topic;\n"
        + "      res.symbol = this.symbol;\n"
        + "      res.last = this.last;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataTickerStreamMessage.java"))));
    
    checkJavaFilesCount(Paths.get("pojo/serializers"), 2);
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataTickerStreamRequestSerializer.java"));
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataTickerStreamMessageSerializer.java"));
    
  }
  
  @Test
  public void testGenerateClassesSpecificApiRequestTypesPrimitiveType() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpoint = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithIntRequestDataType", api);
    WebsocketEndpointClassesGenerator generator = new WebsocketEndpointClassesGenerator(exchange, api, websocketEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(Paths.get("."), 0);       
  }
  
  @Test
  public void testGenerateClassesSpecificApiRequestTypesEmptyRequestAndDefinedResponse() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpoint = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithObjectRequestDataTypeZeroParameters", api);
    WebsocketEndpointClassesGenerator generator = new WebsocketEndpointClassesGenerator(exchange, api, websocketEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(Paths.get("."), 1);
    checkJavaFilesCount(Paths.get("pojo/serializers"), 1);
    checkSourceFileExists(Paths.get("pojo/serializers", "TickerSerializer.java"));
    checkJavaFilesCount(Paths.get("pojo/deserializers"), 1);
    checkSourceFileExists(Paths.get("pojo/deserializers", "TickerDeserializer.java"));
    checkJavaFilesCount(Paths.get("pojo"), 3);
    checkSourceFileExists(Paths.get("pojo", "Ticker.java"));
  }
  
  @Test
  public void testGenerateClassesSpecificApiRequestTypesObjectListMapRequestReferencedObject() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpoint = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithObjectListMapRequestDataType", api);
    WebsocketEndpointClassesGenerator generator = new WebsocketEndpointClassesGenerator(exchange, api, websocketEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(Paths.get("."), 0);  
  }
  
  @Test
  public void testGenerateClassesSpecificApiRequestTypeNullRequest() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpoint = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithIntRequestDataType", api);
    websocketEndpoint.setRequest(null);
    WebsocketEndpointClassesGenerator generator = new WebsocketEndpointClassesGenerator(exchange, api, websocketEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(Paths.get("."), 0);       
  }

}
