package org.jxapi.generator.md.exchange;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.gen.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.gen.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.JavaCodeGenUtil;
import org.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;

/**
 * Unit test for {@link ExchangeReadmeMdGenerator}
 */
public class ExchangeReameMdGeneratorTest {
  
  private Path srcFolder;
  
  @After
  public void tearDown() throws IOException {
    if (srcFolder != null) {
      JavaCodeGenUtil.deletePath(srcFolder);
      srcFolder = null;
    }
  }

  @Test
  public void testGenerateExchangeReadmeFile() throws IOException {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", 
        "https://myrepo.com/myproject/master/src/main/java",
        true).writeJavaFile(srcFolder);
    File expected = srcFolder.resolve("MyTestExchange_README.md").toFile();
    Assert.assertTrue("File " + expected.getAbsolutePath() + " does not exists", expected.exists());
  }
  
  @Test
  public void testGenerateExchangeReadme() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    String actual = new ExchangeReadmeMdGenerator(
        exchange,
        "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java",
        true).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file. Should be provided config properties: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_KEY\">apiKey</a>, <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_SECRET\">apiSecret</a>. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#FIRST_NAME\">firstName</a> <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#LAST_NAME\">lastName</a>\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "    - [API Groups](#api-groups)\n"
        + "      - [MarketData](#marketdata)\n"
        + "        - [REST endpoints](#rest-endpoints)\n"
        + "        - [Websocket endpoints](#websocket-endpoints)\n"
        + "    - [Demo snippets](#demo-snippets)\n"
        + "      - [Endpoint demo snippets](#endpoint-demo-snippets)\n"
        + "        - [MarketData REST endpoints demo snippets:](#marketdata-rest-endpoints-demo-snippets)\n"
        + "        - [MarketData Websocket endpoints demo snippets](#marketdata-websocket-endpoints-demo-snippets)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataExchangeInfoDemo.java\">MyTestExchangeMarketDataExchangeInfoDemo</a> class for full usage example\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "<table>\n"
        + "  <caption>Configuration properties</caption>\n"
        + "  <tr>\n"
        + "    <th>Name</th>\n"
        + "    <th>Type</th>\n"
        + "    <th>description</th>\n"
        + "    <th>Default value</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiKey</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API key</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiSecret</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API secret</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "Some demo configuration properties are available to tune common request parameters used in demo snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can uncomment and set properties values in __demo-MyTestExchange.properties__ properties file you create from .dist template in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "\n"
        + "## API Groups\n"
        + "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
        + "\n"
        + "### MarketData\n"
        + "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
        + "\n"
        + "The market data API of MyTestExchange. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a>\n"
        + "\n"
        + "#### REST endpoints\n"
        + "\n"
        + "<table>\n"
        + "  <caption>MyTestExchange MarketData REST endpoints</caption>\n"
        + "  <tr>\n"
        + "    <th>Endpoint</th>\n"
        + "    <th>Description</th>\n"
        + "    <th>API Reference</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)\">exchangeInfo</a></td>\n"
        + "    <td>Fetch market information of symbols that can be traded. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a></td>\n"
        + "    <td><a href=\"https://docs.myexchange.com/api/rest/marketData/exchangeInfo\">link</a></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#tickers(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickersRequest)\">tickers</a></td>\n"
        + "    <td>Fetch current tickers. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a></td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "#### Websocket endpoints\n"
        + "\n"
        + "<table>\n"
        + "  <caption>MyTestExchange MarketData websocket endpoints</caption>\n"
        + "  <tr>\n"
        + "    <th>Subscription method</th>\n"
        + "    <th>Description</th>\n"
        + "    <th>API Reference</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest)\">subscribeTickerStream</a></td>\n"
        + "    <td>Subscribe to ticker stream. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a></td>\n"
        + "    <td><a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">link</a></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "## Demo snippets\n"
        + "\n"
        + "This wrapper contains demo snippets for the most important endpoints. These snippets are generated in _src/test/java/_ source folder.\n"
        + "\n"
        + "Some demo configuration properties are available to tune common request parameters used in snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can set properties values in __demo-MyTestExchange.properties__ properties file in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Endpoint demo snippets\n"
        + "\n"
        + "\n"
        + "#### MarketData REST endpoints demo snippets:\n"
        + "\n"
        + " - __exchangeInfo__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataExchangeInfoDemo.java\">MyTestExchangeMarketDataExchangeInfoDemo</a>\n"
        + " - __tickers__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataTickersDemo.java\">MyTestExchangeMarketDataTickersDemo</a>\n"
        + "\n"
        + "#### MarketData Websocket endpoints demo snippets\n"
        + "\n"
        + " - __tickerStream__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataTickerStreamDemo.java\">MyTestExchangeMarketDataTickerStreamDemo</a>\n"
        + "",
        actual);
  }
  

  @Test
  public void testGenerateExchangeReadme_AllRequestDataTypes() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    String actual = new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java",
        true).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "    - [API Groups](#api-groups)\n"
        + "      - [MarketData](#marketdata)\n"
        + "        - [REST endpoints](#rest-endpoints)\n"
        + "        - [Websocket endpoints](#websocket-endpoints)\n"
        + "    - [Demo snippets](#demo-snippets)\n"
        + "      - [Endpoint demo snippets](#endpoint-demo-snippets)\n"
        + "        - [MarketData REST endpoints demo snippets:](#marketdata-rest-endpoints-demo-snippets)\n"
        + "        - [MarketData Websocket endpoints demo snippets](#marketdata-websocket-endpoints-demo-snippets)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo</a> class for full usage example\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "\n"
        + "Some demo configuration properties are available to tune common request parameters used in demo snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can uncomment and set properties values in __demo-MyTestExchange.properties__ properties file you create from .dist template in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "\n"
        + "## API Groups\n"
        + "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
        + "\n"
        + "### MarketData\n"
        + "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
        + "\n"
        + "The market data API of MyTestExchange, with different request data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
        + "\n"
        + "#### REST endpoints\n"
        + "\n"
        + "<table>\n"
        + "  <caption>MyTestExchange MarketData REST endpoints</caption>\n"
        + "  <tr>\n"
        + "    <th>Endpoint</th>\n"
        + "    <th>Description</th>\n"
        + "    <th>API Reference</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeInt(java.lang.Integer)\">postRestRequestDataTypeInt</a></td>\n"
        + "    <td>A sample REST endpoint using INT response data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeLong(java.lang.Long)\">postRestRequestDataTypeLong</a></td>\n"
        + "    <td>A sample REST endpoint using LONG response data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeBigDecimal(java.math.BigDecimal)\">postRestRequestDataTypeBigDecimal</a></td>\n"
        + "    <td>A sample REST endpoint using BIGDECIMAL response data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeStringImplicit(java.lang.String)\">postRestRequestDataTypeStringImplicit</a></td>\n"
        + "    <td>A sample REST endpoint using STRING response data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeIntImplicitAsPathParam(java.lang.Integer)\">postRestRequestDataTypeIntImplicitAsPathParam</a></td>\n"
        + "    <td>A sample REST endpoint using STRING response data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeBoolean(java.lang.Boolean)\">postRestRequestDataTypeBoolean</a></td>\n"
        + "    <td>A sample REST endpoint using BOOLEAN response data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestNoParameters(java.lang.String)\">postRestRequestNoParameters</a></td>\n"
        + "    <td>A sample REST endpoint using POST method (HTTP request expecting a body), and no parameters. One String argument should be generated to pass raw body</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeObjectOneParameter(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest)\">postRestRequestDataTypeObjectOneParameter</a></td>\n"
        + "    <td>A sample REST endpoint using OBJECT request data type (default, explicit here), and one parameter</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeIntListWithDefaultValue(java.util.List)\">postRestRequestDataTypeIntListWithDefaultValue</a></td>\n"
        + "    <td>A sample REST endpoint using INT_LIST request data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeObjectListMap(java.util.Map)\">postRestRequestDataTypeObjectListMap</a></td>\n"
        + "    <td>A sample REST endpoint using OBJECT_LIST_MAP request data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#deletetRestRequestDataTypeObjectAsBody(java.util.Map)\">deletetRestRequestDataTypeObjectAsBody</a></td>\n"
        + "    <td>A sample REST DELETE endpoint using OBJECT request data type, and request serialized as body</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#deletetRestRequestDataTypeObjectAsQueryParams(java.util.Map)\">deletetRestRequestDataTypeObjectAsQueryParams</a></td>\n"
        + "    <td>A sample REST endpoint using OBJECT_LIST_MAP request data type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypeObjectListMap(java.util.Map)\">getRestRequestDataTypeObjectListMap</a></td>\n"
        + "    <td>A sample REST endpoint using GET (hence url query params) and object list map request type, and sample value with full structure.</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypeEmptyObject(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestRequestDataTypeEmptyObjectRequest)\">getRestRequestDataTypeEmptyObject</a></td>\n"
        + "    <td>A sample REST endpoint using GET (hence url query params) and empty request object</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypeExternalObject(com.external.pkg.ExternalObject)\">getRestRequestDataTypeExternalObject</a></td>\n"
        + "    <td>A sample REST endpoint using POST (hence request body) and request with object name representing a class with full package name, which is not to be generated</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeRawObject(java.lang.Object)\">postRestRequestDataTypeRawObject</a></td>\n"
        + "    <td>A sample REST endpoint using POST (hence request body) and raw <code>java.lang.Object</code> request object</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypePrimitiveWithMsgField(java.lang.Integer)\">getRestRequestDataTypePrimitiveWithMsgField</a></td>\n"
        + "    <td>A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypePrimitiveWithMsgFieldAsPathPAram(java.lang.Integer)\">getRestRequestDataTypePrimitiveWithMsgFieldAsPathPAram</a></td>\n"
        + "    <td>A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypeWithBothPathAndQueryParams(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestRequestDataTypeWithBothPathAndQueryParamsRequest)\">getRestRequestDataTypeWithBothPathAndQueryParams</a></td>\n"
        + "    <td>A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "#### Websocket endpoints\n"
        + "\n"
        + "<table>\n"
        + "  <caption>MyTestExchange MarketData websocket endpoints</caption>\n"
        + "  <tr>\n"
        + "    <th>Subscription method</th>\n"
        + "    <th>Description</th>\n"
        + "    <th>API Reference</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithObjectRequestDataTypeZeroParameters(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersRequest)\">subscribeStreamWithObjectRequestDataTypeZeroParameters</a></td>\n"
        + "    <td>Subscribe to stream with OBJECT request type (implicit) and no parameters</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithObjectRequestDataTypeOneParameter(com.foo.bar.gen.marketdata.pojo.SingleSymbol)\">subscribeStreamWithObjectRequestDataTypeOneParameter</a></td>\n"
        + "    <td>Subscribe to stream with OBJECT request type (default, explicit here) and parameter</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithIntRequestDataType(java.lang.Integer)\">subscribeStreamWithIntRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with INT request type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithLongRequestDataType(java.lang.Long)\">subscribeStreamWithLongRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with LONG request type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithBigDecimalRequestDataType(java.math.BigDecimal)\">subscribeStreamWithBigDecimalRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with BIGDECIMAL request type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithStringRequestDataType(java.lang.String)\">subscribeStreamWithStringRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with STRING request type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithBooleanRequestDataType(java.lang.Boolean)\">subscribeStreamWithBooleanRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with BOOLEAN request type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithStringListRequestDataType(java.util.List)\">subscribeStreamWithStringListRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with STRING_LIST request type</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithObjectListMapRequestDataType(java.util.Map)\">subscribeStreamWithObjectListMapRequestDataType</a></td>\n"
        + "    <td>Subscribe to stream with OBJECT_LIST_MAP request type. The objectName field is set to a name already defined in other API definition.</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithNullTopicAndNullRequest()\">subscribeStreamWithNullTopicAndNullRequest</a></td>\n"
        + "    <td>Subscribe to stream with null topic, request and message topic matcher. Remark: No topic matcher situation is realistic only when there is no websocket stream multiplexing, e.g. no 'topic' but a single endpoint handling all messages coming on websocket.</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithNullTopicAndPrimitiveTypeRequest(java.lang.String)\">subscribeStreamWithNullTopicAndPrimitiveTypeRequest</a></td>\n"
        + "    <td>Subscribe to stream with null topic, and primitive type request, without message topic matcher. The request is used in message topic matcher field template, so generated method implementation will perform subsitution with method request argument</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "## Demo snippets\n"
        + "\n"
        + "This wrapper contains demo snippets for the most important endpoints. These snippets are generated in _src/test/java/_ source folder.\n"
        + "\n"
        + "Some demo configuration properties are available to tune common request parameters used in snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can set properties values in __demo-MyTestExchange.properties__ properties file in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Endpoint demo snippets\n"
        + "\n"
        + "\n"
        + "#### MarketData REST endpoints demo snippets:\n"
        + "\n"
        + " - __postRestRequestDataTypeInt__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo</a>\n"
        + " - __postRestRequestDataTypeLong__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeLongDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeLongDemo</a>\n"
        + " - __postRestRequestDataTypeBigDecimal__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeBigDecimalDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeBigDecimalDemo</a>\n"
        + " - __postRestRequestDataTypeStringImplicit__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeStringImplicitDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeStringImplicitDemo</a>\n"
        + " - __postRestRequestDataTypeIntImplicitAsPathParam__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeIntImplicitAsPathParamDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeIntImplicitAsPathParamDemo</a>\n"
        + " - __postRestRequestDataTypeBoolean__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeBooleanDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeBooleanDemo</a>\n"
        + " - __postRestRequestNoParameters__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestNoParametersDemo.java\">MyTestExchangeMarketDataPostRestRequestNoParametersDemo</a>\n"
        + " - __postRestRequestDataTypeObjectOneParameter__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterDemo</a>\n"
        + " - __postRestRequestDataTypeIntListWithDefaultValue__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeIntListWithDefaultValueDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeIntListWithDefaultValueDemo</a>\n"
        + " - __postRestRequestDataTypeObjectListMap__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeObjectListMapDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeObjectListMapDemo</a>\n"
        + " - __deletetRestRequestDataTypeObjectAsBody__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataDeletetRestRequestDataTypeObjectAsBodyDemo.java\">MyTestExchangeMarketDataDeletetRestRequestDataTypeObjectAsBodyDemo</a>\n"
        + " - __deletetRestRequestDataTypeObjectAsQueryParams__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataDeletetRestRequestDataTypeObjectAsQueryParamsDemo.java\">MyTestExchangeMarketDataDeletetRestRequestDataTypeObjectAsQueryParamsDemo</a>\n"
        + " - __getRestRequestDataTypeObjectListMap__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataGetRestRequestDataTypeObjectListMapDemo.java\">MyTestExchangeMarketDataGetRestRequestDataTypeObjectListMapDemo</a>\n"
        + " - __getRestRequestDataTypeEmptyObject__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataGetRestRequestDataTypeEmptyObjectDemo.java\">MyTestExchangeMarketDataGetRestRequestDataTypeEmptyObjectDemo</a>\n"
        + " - __getRestRequestDataTypeExternalObject__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataGetRestRequestDataTypeExternalObjectDemo.java\">MyTestExchangeMarketDataGetRestRequestDataTypeExternalObjectDemo</a>\n"
        + " - __postRestRequestDataTypeRawObject__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeRawObjectDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeRawObjectDemo</a>\n"
        + " - __getRestRequestDataTypePrimitiveWithMsgField__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataGetRestRequestDataTypePrimitiveWithMsgFieldDemo.java\">MyTestExchangeMarketDataGetRestRequestDataTypePrimitiveWithMsgFieldDemo</a>\n"
        + " - __getRestRequestDataTypePrimitiveWithMsgFieldAsPathPAram__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataGetRestRequestDataTypePrimitiveWithMsgFieldAsPathPAramDemo.java\">MyTestExchangeMarketDataGetRestRequestDataTypePrimitiveWithMsgFieldAsPathPAramDemo</a>\n"
        + " - __getRestRequestDataTypeWithBothPathAndQueryParams__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataGetRestRequestDataTypeWithBothPathAndQueryParamsDemo.java\">MyTestExchangeMarketDataGetRestRequestDataTypeWithBothPathAndQueryParamsDemo</a>\n"
        + "\n"
        + "#### MarketData Websocket endpoints demo snippets\n"
        + "\n"
        + " - __streamWithObjectRequestDataTypeZeroParameters__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersDemo.java\">MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersDemo</a>\n"
        + " - __streamWithObjectRequestDataTypeOneParameter__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithObjectRequestDataTypeOneParameterDemo.java\">MyTestExchangeMarketDataStreamWithObjectRequestDataTypeOneParameterDemo</a>\n"
        + " - __streamWithIntRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithIntRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithIntRequestDataTypeDemo</a>\n"
        + " - __streamWithLongRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithLongRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithLongRequestDataTypeDemo</a>\n"
        + " - __streamWithBigDecimalRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithBigDecimalRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithBigDecimalRequestDataTypeDemo</a>\n"
        + " - __streamWithStringRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithStringRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithStringRequestDataTypeDemo</a>\n"
        + " - __streamWithBooleanRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithBooleanRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithBooleanRequestDataTypeDemo</a>\n"
        + " - __streamWithStringListRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithStringListRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithStringListRequestDataTypeDemo</a>\n"
        + " - __streamWithObjectListMapRequestDataType__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithObjectListMapRequestDataTypeDemo.java\">MyTestExchangeMarketDataStreamWithObjectListMapRequestDataTypeDemo</a>\n"
        + " - __streamWithNullTopicAndNullRequest__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithNullTopicAndNullRequestDemo.java\">MyTestExchangeMarketDataStreamWithNullTopicAndNullRequestDemo</a>\n"
        + " - __streamWithNullTopicAndPrimitiveTypeRequest__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataStreamWithNullTopicAndPrimitiveTypeRequestDemo.java\">MyTestExchangeMarketDataStreamWithNullTopicAndPrimitiveTypeRequestDemo</a>\n"
        + "",
        actual);
  }
  
  @Test
  public void testGenerateExchangeReadme_ApiGroupWithNoWebsocketEndpoints() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    exchange.getApis().get(0).setWebsocketEndpoints(null);
    String actual = new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", 
        "https://myrepo.com/myproject/master",
        true).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file. Should be provided config properties: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_KEY\">apiKey</a>, <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_SECRET\">apiSecret</a>. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#FIRST_NAME\">firstName</a> <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#LAST_NAME\">lastName</a>\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "    - [API Groups](#api-groups)\n"
        + "      - [MarketData](#marketdata)\n"
        + "        - [REST endpoints](#rest-endpoints)\n"
        + "    - [Demo snippets](#demo-snippets)\n"
        + "      - [Endpoint demo snippets](#endpoint-demo-snippets)\n"
        + "        - [MarketData REST endpoints demo snippets:](#marketdata-rest-endpoints-demo-snippets)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataExchangeInfoDemo.java\">MyTestExchangeMarketDataExchangeInfoDemo</a> class for full usage example\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "<table>\n"
        + "  <caption>Configuration properties</caption>\n"
        + "  <tr>\n"
        + "    <th>Name</th>\n"
        + "    <th>Type</th>\n"
        + "    <th>description</th>\n"
        + "    <th>Default value</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiKey</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API key</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiSecret</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API secret</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "Some demo configuration properties are available to tune common request parameters used in demo snippets, as <a href=\"https://myrepo.com/myproject/master/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can uncomment and set properties values in __demo-MyTestExchange.properties__ properties file you create from .dist template in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "\n"
        + "## API Groups\n"
        + "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
        + "\n"
        + "### MarketData\n"
        + "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
        + "\n"
        + "The market data API of MyTestExchange. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a>\n"
        + "\n"
        + "#### REST endpoints\n"
        + "\n"
        + "<table>\n"
        + "  <caption>MyTestExchange MarketData REST endpoints</caption>\n"
        + "  <tr>\n"
        + "    <th>Endpoint</th>\n"
        + "    <th>Description</th>\n"
        + "    <th>API Reference</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)\">exchangeInfo</a></td>\n"
        + "    <td>Fetch market information of symbols that can be traded. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a></td>\n"
        + "    <td><a href=\"https://docs.myexchange.com/api/rest/marketData/exchangeInfo\">link</a></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#tickers(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickersRequest)\">tickers</a></td>\n"
        + "    <td>Fetch current tickers. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a></td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "## Demo snippets\n"
        + "\n"
        + "This wrapper contains demo snippets for the most important endpoints. These snippets are generated in _src/test/java/_ source folder.\n"
        + "\n"
        + "Some demo configuration properties are available to tune common request parameters used in snippets, as <a href=\"https://myrepo.com/myproject/master/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can set properties values in __demo-MyTestExchange.properties__ properties file in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Endpoint demo snippets\n"
        + "\n"
        + "\n"
        + "#### MarketData REST endpoints demo snippets:\n"
        + "\n"
        + " - __exchangeInfo__: <a href=\"https://myrepo.com/myproject/master/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataExchangeInfoDemo.java\">MyTestExchangeMarketDataExchangeInfoDemo</a>\n"
        + " - __tickers__: <a href=\"https://myrepo.com/myproject/master/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataTickersDemo.java\">MyTestExchangeMarketDataTickersDemo</a>\n"
        + "",
        actual);
  }
  
  @Test
  public void testGenerateExchangeReadme_ApiGroupWithNoRestEndpoints() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    api.setRestEndpoints(null);
    String actual = new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", 
        "https://myrepo.com/myproject/master/src/main/java",
        false).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file. Should be provided config properties: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_KEY\">apiKey</a>, <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_SECRET\">apiSecret</a>. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#FIRST_NAME\">firstName</a> <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#LAST_NAME\">lastName</a>\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "    - [API Groups](#api-groups)\n"
        + "      - [MarketData](#marketdata)\n"
        + "        - [Websocket endpoints](#websocket-endpoints)\n"
        + "    - [Demo snippets](#demo-snippets)\n"
        + "      - [Endpoint demo snippets](#endpoint-demo-snippets)\n"
        + "        - [MarketData Websocket endpoints demo snippets](#marketdata-websocket-endpoints-demo-snippets)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataTickerStreamDemo.java\">MyTestExchangeMarketDataTickerStreamDemo</a> class for full usage example\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "<table>\n"
        + "  <caption>Configuration properties</caption>\n"
        + "  <tr>\n"
        + "    <th>Name</th>\n"
        + "    <th>Type</th>\n"
        + "    <th>description</th>\n"
        + "    <th>Default value</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiKey</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API key</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiSecret</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API secret</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "\n"
        + "## API Groups\n"
        + "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
        + "\n"
        + "### MarketData\n"
        + "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
        + "\n"
        + "The market data API of MyTestExchange. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a>\n"
        + "\n"
        + "\n"
        + "#### Websocket endpoints\n"
        + "\n"
        + "<table>\n"
        + "  <caption>MyTestExchange MarketData websocket endpoints</caption>\n"
        + "  <tr>\n"
        + "    <th>Subscription method</th>\n"
        + "    <th>Description</th>\n"
        + "    <th>API Reference</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest)\">subscribeTickerStream</a></td>\n"
        + "    <td>Subscribe to ticker stream. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html#AUTHOR_FULL_NAME\">authorFullName</a></td>\n"
        + "    <td><a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">link</a></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "## Demo snippets\n"
        + "\n"
        + "This wrapper contains demo snippets for the most important endpoints. These snippets are generated in _src/test/java/_ source folder.\n"
        + "\n"
        + "Some demo configuration properties are available to tune common request parameters used in snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can set properties values in __demo-MyTestExchange.properties__ properties file in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Endpoint demo snippets\n"
        + "\n"
        + "\n"
        + "#### MarketData Websocket endpoints demo snippets\n"
        + "\n"
        + " - __tickerStream__: <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataTickerStreamDemo.java\">MyTestExchangeMarketDataTickerStreamDemo</a>\n"
        + "",
        actual);
  }
  
  @Test
  public void testGenerateExchangeReadme_NoApiGroup() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    exchange.setApis(null);
    String actual = new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java",
        false
        ).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file. Should be provided config properties: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_KEY\">apiKey</a>, <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_SECRET\">apiSecret</a>. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#FIRST_NAME\">firstName</a> <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#LAST_NAME\">lastName</a>\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "<table>\n"
        + "  <caption>Configuration properties</caption>\n"
        + "  <tr>\n"
        + "    <th>Name</th>\n"
        + "    <th>Type</th>\n"
        + "    <th>description</th>\n"
        + "    <th>Default value</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiKey</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API key</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiSecret</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API secret</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "",
        actual);
  }
  
  @Test
  public void testGenerateExchangeReadme_NoApiGroupNoDemoProperties() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    exchange.setApis(null);
    String actual = new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", 
        "https://myrepo.com/myproject/master/src/main/java", 
        true).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file. Should be provided config properties: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_KEY\">apiKey</a>, <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_SECRET\">apiSecret</a>. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#FIRST_NAME\">firstName</a> <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#LAST_NAME\">lastName</a>\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "<table>\n"
        + "  <caption>Configuration properties</caption>\n"
        + "  <tr>\n"
        + "    <th>Name</th>\n"
        + "    <th>Type</th>\n"
        + "    <th>description</th>\n"
        + "    <th>Default value</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiKey</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API key</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiSecret</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API secret</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "Some demo configuration properties are available to tune common request parameters used in demo snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can uncomment and set properties values in __demo-MyTestExchange.properties__ properties file you create from .dist template in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "",
        actual);
  }
  
  @Test
  public void testGenerateExchangeReadme_ApiGroupWithNoDescriptionNoRestNoWsEndpoint() throws IOException {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    api.setRestEndpoints(null);
    api.setWebsocketEndpoints(null);
    api.setDescription(null);
    String actual = new ExchangeReadmeMdGenerator(
        exchange, 
        "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java",
        true).generate();
    Assert.assertEquals("# MyTestExchange API Java wrapper\n"
        + "\n"
        + "A sample Exchange descriptor file. Should be provided config properties: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_KEY\">apiKey</a>, <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeProperties.html#API_SECRET\">apiSecret</a>. Author: <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#FIRST_NAME\">firstName</a> <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.Author.html#LAST_NAME\">lastName</a>\n"
        + "<!-- BEGIN TABLE OF CONTENTS -->\n"
        + "  - [MyTestExchange API Java wrapper](#mytestexchange-api-java-wrapper)\n"
        + "      - [Quick start](#quick-start)\n"
        + "      - [Properties](#properties)\n"
        + "      - [Constants](#constants)\n"
        + "    - [API Groups](#api-groups)\n"
        + "      - [MarketData](#marketdata)\n"
        + "\n"
        + "<!-- END TABLE OF CONTENTS -->\n"
        + "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
        + "### Quick start\n"
        + "\n"
        + "This wrapper offers Java interfaces for using MyTestExchange API\n"
        + "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
        + "``` java\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "\n"
        + "public void call() {\n"
        + "  Properties properties = new Properties();\n"
        + "  // Set relevant configuration properties (see documentation) in 'props'\n"
        + "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
        + "  // Access API groups and their endpoints through 'exchange' methods.\n"
        + "}\n"
        + "```\n"
        + "\n"
        + "### Properties\n"
        + "\n"
        + "<table>\n"
        + "  <caption>Configuration properties</caption>\n"
        + "  <tr>\n"
        + "    <th>Name</th>\n"
        + "    <th>Type</th>\n"
        + "    <th>description</th>\n"
        + "    <th>Default value</th>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiKey</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API key</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "  <tr>\n"
        + "    <td>apiSecret</td>\n"
        + "    <td>STRING</td>\n"
        + "    <td>API secret</td>\n"
        + "    <td></td>\n"
        + "  </tr>\n"
        + "</table>\n"
        + "Some demo configuration properties are available to tune common request parameters used in demo snippets, as <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/MyTestExchangeDemoProperties.java\">MyTestExchangeDemoProperties</a> class.\n"
        + " These properties are used to configure default values for request parameters used in demo snippets.\n"
        + "\n"
        + "In order to run demo snippets, you can uncomment and set properties values in __demo-MyTestExchange.properties__ properties file you create from .dist template in src/test/resources folder.\n"
        + "\n"
        + "\n"
        + "### Constants\n"
        + "\n"
        + "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
        + "\n"
        + "## API Groups\n"
        + "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
        + "\n"
        + "### MarketData\n"
        + "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
        + "\n"
        + "",
        actual);
  }
}
