package com.scz.jxapi.generator.java.exchange.api;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import com.scz.jxapi.exchange.descriptor.ExchangeApiDescriptor;
import com.scz.jxapi.exchange.descriptor.ExchangeDescriptor;
import com.scz.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;


/**
 * Unit test for {@link ExchangeApiInterfaceGenerator}
 */
public class ExchangeApiInterfaceGeneratorTest {

	@Test
	public void testGenerateExchangeApi() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickersResponse;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "\n"
				+ "/**\n"
				+ " * MyTestExchange MarketData API</br>\n"
				+ " * The market data API of MyTestExchange\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
				+ "  String ID = \"MarketData\";\n"
				+ "  String EXCHANGE_INFO_REST_API = \"exchangeInfo\";\n"
				+ "  String TICKERS_REST_API = \"tickers\";\n"
				+ "  String TICKER_STREAM_WS_API = \"tickerStream\";\n"
				+ "  /**\n"
				+ "   * Fetch market information of symbols that can be traded\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed.@see <a href=\"https://docs.myexchange.com/api/rest/marketData/exchangeInfo\">Reference documentation</a>\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request);\n"
				+ "  /**\n"
				+ "   * Fetch current tickers\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestExchangeMarketDataTickersResponse> tickers();\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to tickerStream stream.<br>\n"
				+ "   * <a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">Reference documentation</a>subscribeTickerStream()\n"
				+ "   * Subscribe to ticker stream\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeTickerStream(MyTestExchangeMarketDataTickerStreamRequest request, WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from tickerStream stream.\n"
				+ "   * <a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">Reference documentation</a>subscribeTickerStream()\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeTickerStream()\n"
				+ "   */\n"
				+ "  boolean unsubscribeTickerStream(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoWsEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoWebsocketEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "\n"
				+ "/**\n"
				+ " * MyTestExchange MarketData API</br>\n"
				+ " * The market data API of MyTestExchange, , with only 1 REST endpoint and no websocket endpoint\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
				+ "  String ID = \"MarketData\";\n"
				+ "  String EXCHANGE_INFO_REST_API = \"exchangeInfo\";\n"
				+ "  /**\n"
				+ "   * Fetch market information of symbols that can be traded\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoRestEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoRestEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.TickerMessage;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "\n"
				+ "/**\n"
				+ " * MyTestExchange MarketData API</br>\n"
				+ " * The market data API of MyTestExchange\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
				+ "  String ID = \"MarketData\";\n"
				+ "  String TICKER_STREAM_STRING_OBJECT_TYPE_WS_API = \"tickerStreamStringObjectType\";\n"
				+ "  String TICKER_STREAM_STRING_REQUEST_TYPE_WS_API = \"tickerStreamStringRequestType\";\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to tickerStreamStringObjectType stream.<br>\n"
				+ "   * Subscribe to ticker stream\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeTickerStreamStringObjectType(MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest request, WebsocketListener<TickerMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from tickerStreamStringObjectType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeTickerStreamStringObjectType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeTickerStreamStringObjectType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to tickerStreamStringRequestType stream.<br>\n"
				+ "   * Subscribe to ticker stream\n"
				+ "   * \n"
				+ "   * @param symbol Symbol to subscribe to ticker stream of\n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeTickerStreamStringRequestType(String symbol, WebsocketListener<TickerMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from tickerStreamStringRequestType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeTickerStreamStringRequestType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeTickerStreamStringRequestType(String subscriptionId);\n"
				+ "}\n"
				+ "", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificResponseDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataSubscribeTickerMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "\n"
				+ "/**\n"
				+ " * MyTestExchange MarketData API</br>\n"
				+ " * The market data API of MyTestExchange, , with different response data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
				+ "  String ID = \"MarketData\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_INT_REST_API = \"getRestResponseDataTypeInt\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_LONG_REST_API = \"getRestResponseDataTypeLong\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_BIG_DECIMAL_REST_API = \"getRestResponseDataTypeBigDecimal\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_STRING_REST_API = \"getRestResponseDataTypeString\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_BOOLEAN_REST_API = \"getRestResponseDataTypeBoolean\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_OBJECT_REST_API = \"getRestResponseDataTypeObject\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_INT_LIST_REST_API = \"getRestResponseDataTypeIntList\";\n"
				+ "  String GET_REST_RESPONSE_DATA_TYPE_OBJECT_LIST_MAP_REST_API = \"getRestResponseDataTypeObjectListMap\";\n"
				+ "  String GET_REST_EMPTY_RESPONSE_DATA_TYPE_REST_API = \"getRestEmptyResponseDataType\";\n"
				+ "  String SUBSCRIBE_TICKER_WS_API = \"subscribeTicker\";\n"
				+ "  String SUBSCRIBE_TICKERT_MAP_LIST_STREAM_WS_API = \"subscribeTickertMapListStream\";\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed.If successful, will provide response:A random int\n"
				+ "   */\n"
				+ "  FutureRestResponse<Integer> getRestResponseDataTypeInt();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using LONG response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<Long> getRestResponseDataTypeLong();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BIGDECIMAL response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<BigDecimal> getRestResponseDataTypeBigDecimal();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using STRING response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<String> getRestResponseDataTypeString();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BOOLEAN response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<Boolean> getRestResponseDataTypeBoolean();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT response data type (default type, explicit here)\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObject();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT_LIST response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<List<Integer>> getRestResponseDataTypeIntList();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT_LIST_MAP response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<Map<String, List<MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMap();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using empty response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<String> getRestEmptyResponseDataType();\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to subscribeTicker stream.<br>\n"
				+ "   * Subscribe to stream with OBJECT message type (default, explicit here)\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeSubscribeTicker(WebsocketListener<MyTestExchangeMarketDataSubscribeTickerMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from subscribeTicker stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeSubscribeTicker()\n"
				+ "   */\n"
				+ "  boolean unsubscribeSubscribeTicker(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to subscribeTickertMapListStream stream.<br>\n"
				+ "   * Subscribe to stream with OBJECT_MAP_LIST message type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeSubscribeTickertMapListStream(WebsocketListener<List<Map<String, MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage>>> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from subscribeTickertMapListStream stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeSubscribeTickertMapListStream()\n"
				+ "   */\n"
				+ "  boolean unsubscribeSubscribeTickertMapListStream(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificRequestDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MultiSymbol;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "\n"
				+ "/**\n"
				+ " * MyTestExchange MarketData API</br>\n"
				+ " * The market data API of MyTestExchange, , with different request data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
				+ "  String ID = \"MarketData\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_INT_REST_API = \"postRestRequestDataTypeInt\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_LONG_REST_API = \"postRestRequestDataTypeLong\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_BIG_DECIMAL_REST_API = \"postRestRequestDataTypeBigDecimal\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_STRING_REST_API = \"postRestRequestDataTypeString\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_BOOLEAN_REST_API = \"postRestRequestDataTypeBoolean\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_OBJECT_NO_PARAMETERS_REST_API = \"postRestRequestDataTypeObjectNoParameters\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_OBJECT_ONE_PARAMETER_REST_API = \"postRestRequestDataTypeObjectOneParameter\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_INT_LIST_REST_API = \"postRestRequestDataTypeIntList\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_OBJECT_LIST_MAP_REST_API = \"postRestRequestDataTypeObjectListMap\";\n"
				+ "  String GET_REST_REQUEST_DATA_TYPE_OBJECT_LIST_MAP_REST_API = \"getRestRequestDataTypeObjectListMap\";\n"
				+ "  String GET_REST_REQUEST_DATA_TYPE_EMPTY_OBJECT_REST_API = \"getRestRequestDataTypeEmptyObject\";\n"
				+ "  String GET_REST_REQUEST_DATA_TYPE_PRIMITIVE_WITH_MSG_FIELD_REST_API = \"getRestRequestDataTypePrimitiveWithMsgField\";\n"
				+ "  String POST_REST_REQUEST_DATA_TYPE_NO_PARAMS_BUT_URL_PARAMETERS_REST_API = \"postRestRequestDataTypeNoParamsButUrlParameters\";\n"
				+ "  String STREAM_WITH_OBJECT_REQUEST_DATA_TYPE_ZERO_PARAMETERS_WS_API = \"streamWithObjectRequestDataTypeZeroParameters\";\n"
				+ "  String STREAM_WITH_OBJECT_REQUEST_DATA_TYPE_ONE_PARAMETER_WS_API = \"streamWithObjectRequestDataTypeOneParameter\";\n"
				+ "  String STREAM_WITH_INT_REQUEST_DATA_TYPE_WS_API = \"streamWithIntRequestDataType\";\n"
				+ "  String STREAM_WITH_LONG_REQUEST_DATA_TYPE_WS_API = \"streamWithLongRequestDataType\";\n"
				+ "  String STREAM_WITH_BIG_DECIMAL_REQUEST_DATA_TYPE_WS_API = \"streamWithBigDecimalRequestDataType\";\n"
				+ "  String STREAM_WITH_STRING_REQUEST_DATA_TYPE_WS_API = \"streamWithStringRequestDataType\";\n"
				+ "  String STREAM_WITH_BOOLEAN_REQUEST_DATA_TYPE_WS_API = \"streamWithBooleanRequestDataType\";\n"
				+ "  String STREAM_WITH_STRING_LIST_REQUEST_DATA_TYPE_WS_API = \"streamWithStringListRequestDataType\";\n"
				+ "  String STREAM_WITH_OBJECT_LIST_MAP_REQUEST_DATA_TYPE_WS_API = \"streamWithObjectListMapRequestDataType\";\n"
				+ "  String STREAM_WITH_NULL_TOPIC_AND_NULL_REQUEST_WS_API = \"streamWithNullTopicAndNullRequest\";\n"
				+ "  String STREAM_WITH_NULL_TOPIC_AND_PRIMITIVE_TYPE_REQUEST_WS_API = \"streamWithNullTopicAndPrimitiveTypeRequest\";\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeInt(Integer request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using LONG response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeLong(Long request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BIGDECIMAL response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeBigDecimal(BigDecimal request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using STRING response data type\n"
				+ "   * @param hello Say Hi!\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeString(String hello);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BOOLEAN response data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeBoolean(Boolean request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT request data type (implicit), and no parameters\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectNoParameters();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT request data type (default, explicit here), and one parameter\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectOneParameter(MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT_LIST request data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeIntList(List<Integer> request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT_LIST_MAP request data type\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectListMap(Map<String, List<SingleSymbol>> request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using GET (hence url query params) and object list map request type. The object used as values contains \n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> getRestRequestDataTypeObjectListMap(Map<String, List<MultiSymbol>> request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using GET (hence url query params) and empty request object\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> getRestRequestDataTypeEmptyObject();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> getRestRequestDataTypePrimitiveWithMsgField(Integer age);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using POST method (hence no url parameters by default), no arguments, but url parameters through 'urlParameters' property\n"
				+ "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeNoParamsButUrlParameters();\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithObjectRequestDataTypeZeroParameters stream.<br>\n"
				+ "   * Subscribe to stream with OBJECT request type (implicit) and no parameters\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithObjectRequestDataTypeZeroParameters(WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithObjectRequestDataTypeZeroParameters stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithObjectRequestDataTypeZeroParameters()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithObjectRequestDataTypeZeroParameters(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithObjectRequestDataTypeOneParameter stream.<br>\n"
				+ "   * Subscribe to stream with OBJECT request type (default, explicit here) and parameter\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithObjectRequestDataTypeOneParameter(SingleSymbol symbolObj, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithObjectRequestDataTypeOneParameter stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithObjectRequestDataTypeOneParameter()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithObjectRequestDataTypeOneParameter(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithIntRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with INT request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithIntRequestDataType(Integer request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithIntRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithIntRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithIntRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithLongRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with LONG request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithLongRequestDataType(Long request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithLongRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithLongRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithLongRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithBigDecimalRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with BIGDECIMAL request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithBigDecimalRequestDataType(BigDecimal request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithBigDecimalRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithBigDecimalRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithBigDecimalRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithStringRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with STRING request type\n"
				+ "   * \n"
				+ "   * @param symbol Market symbol\n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithStringRequestDataType(String symbol, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithStringRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithStringRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithStringRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithBooleanRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with BOOLEAN request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithBooleanRequestDataType(Boolean request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithBooleanRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithBooleanRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithBooleanRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithStringListRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with STRING_LIST request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithStringListRequestDataType(List<String> request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithStringListRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithStringListRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithStringListRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithObjectListMapRequestDataType stream.<br>\n"
				+ "   * Subscribe to stream with OBJECT_LIST_MAP request type. The objectName field is set to a name already defined in other API definition.\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithObjectListMapRequestDataType(Map<String, List<MultiSymbol>> request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithObjectListMapRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithObjectListMapRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithObjectListMapRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithNullTopicAndNullRequest stream.<br>\n"
				+ "   * Subscribe to stream with null topic, request and message topic matcher. Remark: No topic matcher situation is realistic only when there is no websocket stream multiplexing, e.g. no 'topic' but a single endpoint handling all messages coming on websocket.\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithNullTopicAndNullRequest(WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithNullTopicAndNullRequest stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithNullTopicAndNullRequest()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithNullTopicAndNullRequest(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithNullTopicAndPrimitiveTypeRequest stream.<br>\n"
				+ "   * Subscribe to stream with null topic, and primitive type request, without message topic matcher. The request is used in message topic matcher field template, so generated method implementation will perform subsitution with method request argument\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithNullTopicAndPrimitiveTypeRequest(String myTopic, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithNullTopicAndPrimitiveTypeRequest stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithNullTopicAndPrimitiveTypeRequest()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithNullTopicAndPrimitiveTypeRequest(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
}
