package com.scz.netutis.websocket;

public enum MockWebsocketHookEventType {
	AFTER_INIT,
	BEFORE_CONNECT,
	AFTER_CONNECT,
	BEFORE_DISCONNECT,
	AFTER_DISCONNECT,
	GET_SUBSCRIBE_REQUEST_MESSAGE,
	GET_UNSUBSCRIBE_REQUEST_MESSAGE,
	GET_HEARTBEAT;
}
