package org.jxapi.generator.java.exchange.api.rest;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.gen.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.gen.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.gen.RestEndpointDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.JavaCodeGenUtil;
import org.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;
import org.jxapi.generator.java.exchange.ExchangeGenUtil;
import org.jxapi.util.PlaceHolderResolver;

/**
 * Unit test for {@link RestEndpointClassesGenerator}
 */
public class RestEndpointClassesGeneratorTest {
  
  private static final Path BASE_PKG = Paths.get("com", "foo", "bar", "gen", "marketdata");
  
  private Path srcFolder;
  
  @After
  public void tearDown() throws IOException {
    if (srcFolder != null) {
      JavaCodeGenUtil.deletePath(srcFolder);
      srcFolder = null;
    }
  }
  
  private void checkJavaFilesCount(Path relativePkg, int count) {
    ClassesGeneratorTestUtil.checkJavaFilesCount(srcFolder.resolve(BASE_PKG).resolve(relativePkg), count);
  }
  
  private Path checkSourceFileExists(Path srcFilePath) {
    return ClassesGeneratorTestUtil.checkSourceFileExists(srcFolder.resolve(BASE_PKG), srcFilePath);
  }

  @Test
  public void testGenerateRestEndpointClasses() throws IOException {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = api.getRestEndpoints().get(0);
    PlaceHolderResolver docPlaceHolderResolver = 
        PlaceHolderResolver.create(ExchangeGenUtil.getDescriptionReplacements(exchange));
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, docPlaceHolderResolver);
    generator.generateClasses(srcFolder);
    
    checkJavaFilesCount(Paths.get("pojo"), 5);
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.MyTestExchangePaginatedRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataExchangeInfoRequestDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataExchangeInfoRequestSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CollectionUtil;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Request parameters for fetching exchange info. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataExchangeInfoRequestSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataExchangeInfoRequestDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataExchangeInfoRequest implements Pojo<MyTestExchangeMarketDataExchangeInfoRequest>, MyTestExchangePaginatedRequest {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -4193695595206420816L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataExchangeInfoRequest} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private List<String> symbols;\n"
        + "  private String apiKey;\n"
        + "  private String author;\n"
        + "  private Integer page;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return The list of symbol to fetch market information for. Leave empty to fetch all markets. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public List<String> getSymbols() {\n"
        + "    return symbols;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param symbols The list of symbol to fetch market information for. Leave empty to fetch all markets. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public void setSymbols(List<String> symbols) {\n"
        + "    this.symbols = symbols;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return API key, see {@link com.foo.bar.gen.MyTestExchangeProperties#API_KEY}\n"
        + "   */\n"
        + "  public String getApiKey() {\n"
        + "    return apiKey;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param apiKey API key, see {@link com.foo.bar.gen.MyTestExchangeProperties#API_KEY}\n"
        + "   */\n"
        + "  public void setApiKey(String apiKey) {\n"
        + "    this.apiKey = apiKey;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Author name, see {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public String getAuthor() {\n"
        + "    return author;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param author Author name, see {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public void setAuthor(String author) {\n"
        + "    this.author = author;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Page number to return, defaults to 1. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public Integer getPage() {\n"
        + "    return page;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param page Page number to return, defaults to 1. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public void setPage(Integer page) {\n"
        + "    this.page = page;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataExchangeInfoRequest o = (MyTestExchangeMarketDataExchangeInfoRequest) other;\n"
        + "    return Objects.equals(this.symbols, o.symbols)\n"
        + "        && Objects.equals(this.apiKey, o.apiKey)\n"
        + "        && Objects.equals(this.author, o.author)\n"
        + "        && Objects.equals(this.page, o.page);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataExchangeInfoRequest other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compareLists(this.symbols, other.symbols, CompareUtil::compare);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.apiKey, other.apiKey);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.author, other.author);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.page, other.page);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(symbols, apiKey, author, page);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataExchangeInfoRequest deepClone() {\n"
        + "    MyTestExchangeMarketDataExchangeInfoRequest clone = new MyTestExchangeMarketDataExchangeInfoRequest();\n"
        + "    clone.symbols = CollectionUtil.cloneList(this.symbols);\n"
        + "    clone.apiKey = this.apiKey;\n"
        + "    clone.author = this.author;\n"
        + "    clone.page = this.page;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataExchangeInfoRequest}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private List<String> symbols;\n"
        + "    private String apiKey;\n"
        + "    private String author;\n"
        + "    private Integer page;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>symbols</code> field in the builder\n"
        + "     * @param symbols The list of symbol to fetch market information for. Leave empty to fetch all markets. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setSymbols(List<String>)\n"
        + "     */\n"
        + "    public Builder symbols(List<String> symbols)  {\n"
        + "      this.symbols = symbols;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add an item to the <code>symbols</code> list.\n"
        + "     * @param item Item to add to current <code>symbols</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyTestExchangeMarketDataExchangeInfoRequest#setSymbols(List)\n"
        + "     */\n"
        + "    public Builder addToSymbols(String item) {\n"
        + "      if (this.symbols == null) {\n"
        + "        this.symbols = CollectionUtil.createList();\n"
        + "      }\n"
        + "      this.symbols.add(item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>apiKey</code> field in the builder\n"
        + "     * @param apiKey API key, see {@link com.foo.bar.gen.MyTestExchangeProperties#API_KEY}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setApiKey(String)\n"
        + "     */\n"
        + "    public Builder apiKey(String apiKey)  {\n"
        + "      this.apiKey = apiKey;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>author</code> field in the builder\n"
        + "     * @param author Author name, see {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setAuthor(String)\n"
        + "     */\n"
        + "    public Builder author(String author)  {\n"
        + "      this.author = author;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>page</code> field in the builder\n"
        + "     * @param page Page number to return, defaults to 1. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setPage(Integer)\n"
        + "     */\n"
        + "    public Builder page(Integer page)  {\n"
        + "      this.page = page;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataExchangeInfoRequest using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataExchangeInfoRequest build() {\n"
        + "      MyTestExchangeMarketDataExchangeInfoRequest res = new MyTestExchangeMarketDataExchangeInfoRequest();\n"
        + "      res.symbols = CollectionUtil.cloneList(this.symbols);\n"
        + "      res.apiKey = this.apiKey;\n"
        + "      res.author = this.author;\n"
        + "      res.page = this.page;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataExchangeInfoRequest.java"))));
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.MyTestExchangePaginatedResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataExchangeInfoResponseDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataExchangeInfoResponseSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CollectionUtil;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.DeepCloneable;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Response object for MyTestExchange MarketData API exchangeInfo REST endpoint<br>\n"
        + " * Fetch market information of symbols that can be traded. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataExchangeInfoResponseSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataExchangeInfoResponseDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataExchangeInfoResponse implements Pojo<MyTestExchangeMarketDataExchangeInfoResponse>, MyTestExchangePaginatedResponse {\n"
        + "  \n"
        + "  private static final long serialVersionUID = 7439089996962557233L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataExchangeInfoResponse} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private Integer responseCode;\n"
        + "  private Integer currentPage;\n"
        + "  private Integer totalPages;\n"
        + "  private List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Request response code\n"
        + "   */\n"
        + "  public Integer getResponseCode() {\n"
        + "    return responseCode;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param responseCode Request response code\n"
        + "   */\n"
        + "  public void setResponseCode(Integer responseCode) {\n"
        + "    this.responseCode = responseCode;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Current page index.\n"
        + "   */\n"
        + "  public Integer getCurrentPage() {\n"
        + "    return currentPage;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param currentPage Current page index.\n"
        + "   */\n"
        + "  public void setCurrentPage(Integer currentPage) {\n"
        + "    this.currentPage = currentPage;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Total number of pages.\n"
        + "   */\n"
        + "  public Integer getTotalPages() {\n"
        + "    return totalPages;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param totalPages Total number of pages.\n"
        + "   */\n"
        + "  public void setTotalPages(Integer totalPages) {\n"
        + "    this.totalPages = totalPages;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return List of market information for each requested symbol. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public List<MyTestExchangeMarketDataExchangeInfoResponsePayload> getPayload() {\n"
        + "    return payload;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param payload List of market information for each requested symbol. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   */\n"
        + "  public void setPayload(List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload) {\n"
        + "    this.payload = payload;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataExchangeInfoResponse o = (MyTestExchangeMarketDataExchangeInfoResponse) other;\n"
        + "    return Objects.equals(this.responseCode, o.responseCode)\n"
        + "        && Objects.equals(this.currentPage, o.currentPage)\n"
        + "        && Objects.equals(this.totalPages, o.totalPages)\n"
        + "        && Objects.equals(this.payload, o.payload);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataExchangeInfoResponse other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.responseCode, other.responseCode);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.currentPage, other.currentPage);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.totalPages, other.totalPages);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compareLists(this.payload, other.payload, CompareUtil::compare);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(responseCode, currentPage, totalPages, payload);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataExchangeInfoResponse deepClone() {\n"
        + "    MyTestExchangeMarketDataExchangeInfoResponse clone = new MyTestExchangeMarketDataExchangeInfoResponse();\n"
        + "    clone.responseCode = this.responseCode;\n"
        + "    clone.currentPage = this.currentPage;\n"
        + "    clone.totalPages = this.totalPages;\n"
        + "    clone.payload = CollectionUtil.deepCloneList(this.payload, DeepCloneable::deepClone);\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataExchangeInfoResponse}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private Integer responseCode;\n"
        + "    private Integer currentPage;\n"
        + "    private Integer totalPages;\n"
        + "    private List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>responseCode</code> field in the builder\n"
        + "     * @param responseCode Request response code\n"
        + "     * @return Builder instance\n"
        + "     * @see #setResponseCode(Integer)\n"
        + "     */\n"
        + "    public Builder responseCode(Integer responseCode)  {\n"
        + "      this.responseCode = responseCode;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>currentPage</code> field in the builder\n"
        + "     * @param currentPage Current page index.\n"
        + "     * @return Builder instance\n"
        + "     * @see #setCurrentPage(Integer)\n"
        + "     */\n"
        + "    public Builder currentPage(Integer currentPage)  {\n"
        + "      this.currentPage = currentPage;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>totalPages</code> field in the builder\n"
        + "     * @param totalPages Total number of pages.\n"
        + "     * @return Builder instance\n"
        + "     * @see #setTotalPages(Integer)\n"
        + "     */\n"
        + "    public Builder totalPages(Integer totalPages)  {\n"
        + "      this.totalPages = totalPages;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>payload</code> field in the builder\n"
        + "     * @param payload List of market information for each requested symbol. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "     * @return Builder instance\n"
        + "     * @see #setPayload(List<MyTestExchangeMarketDataExchangeInfoResponsePayload>)\n"
        + "     */\n"
        + "    public Builder payload(List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload)  {\n"
        + "      this.payload = payload;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add an item to the <code>payload</code> list.\n"
        + "     * @param item Item to add to current <code>payload</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyTestExchangeMarketDataExchangeInfoResponse#setPayload(List)\n"
        + "     */\n"
        + "    public Builder addToPayload(MyTestExchangeMarketDataExchangeInfoResponsePayload item) {\n"
        + "      if (this.payload == null) {\n"
        + "        this.payload = CollectionUtil.createList();\n"
        + "      }\n"
        + "      this.payload.add(item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataExchangeInfoResponse using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataExchangeInfoResponse build() {\n"
        + "      MyTestExchangeMarketDataExchangeInfoResponse res = new MyTestExchangeMarketDataExchangeInfoResponse();\n"
        + "      res.responseCode = this.responseCode;\n"
        + "      res.currentPage = this.currentPage;\n"
        + "      res.totalPages = this.totalPages;\n"
        + "      res.payload = CollectionUtil.deepCloneList(this.payload, DeepCloneable::deepClone);\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataExchangeInfoResponse.java"))));
    
    checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataExchangeInfoResponsePayload.java"));
    
    checkJavaFilesCount(Paths.get("pojo/serializers"), 3);
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataExchangeInfoRequestSerializer.java"));        
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataExchangeInfoResponsePayloadSerializer.java"));
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataExchangeInfoResponseSerializer.java"));  
    
    checkJavaFilesCount(Paths.get("pojo/deserializers"), 3);
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataExchangeInfoRequestDeserializer.java"));
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataExchangeInfoResponseDeserializer.java"));
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataExchangeInfoResponsePayloadDeserializer.java"));
  }
  
  @Test
  public void testGenerateRestEndpointClassesWithRequestAndResponseImplementingCustomInterfaces() throws IOException {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithRequestAndResponseImplementingCustomInterfaces.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("exchangeInfo", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    
    checkJavaFilesCount(Paths.get("pojo"), 5);
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.ExchangeInfoRequestInterface1;\n"
        + "import com.foo.bar.ExchangeInfoRequestInterface2;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataExchangeInfoRequestDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataExchangeInfoRequestSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CollectionUtil;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Exchange info request\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataExchangeInfoRequestSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataExchangeInfoRequestDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataExchangeInfoRequest implements Pojo<MyTestExchangeMarketDataExchangeInfoRequest>, ExchangeInfoRequestInterface1, ExchangeInfoRequestInterface2 {\n"
        + "  \n"
        + "  private static final long serialVersionUID = 9027087182370646227L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataExchangeInfoRequest} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private List<String> symbols;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return The list of symbol to fetch market information for. Leave empty to fetch all markets\n"
        + "   */\n"
        + "  public List<String> getSymbols() {\n"
        + "    return symbols;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param symbols The list of symbol to fetch market information for. Leave empty to fetch all markets\n"
        + "   */\n"
        + "  public void setSymbols(List<String> symbols) {\n"
        + "    this.symbols = symbols;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataExchangeInfoRequest o = (MyTestExchangeMarketDataExchangeInfoRequest) other;\n"
        + "    return Objects.equals(this.symbols, o.symbols);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataExchangeInfoRequest other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compareLists(this.symbols, other.symbols, CompareUtil::compare);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(symbols);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataExchangeInfoRequest deepClone() {\n"
        + "    MyTestExchangeMarketDataExchangeInfoRequest clone = new MyTestExchangeMarketDataExchangeInfoRequest();\n"
        + "    clone.symbols = CollectionUtil.cloneList(this.symbols);\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataExchangeInfoRequest}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private List<String> symbols;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>symbols</code> field in the builder\n"
        + "     * @param symbols The list of symbol to fetch market information for. Leave empty to fetch all markets\n"
        + "     * @return Builder instance\n"
        + "     * @see #setSymbols(List<String>)\n"
        + "     */\n"
        + "    public Builder symbols(List<String> symbols)  {\n"
        + "      this.symbols = symbols;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add an item to the <code>symbols</code> list.\n"
        + "     * @param item Item to add to current <code>symbols</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyTestExchangeMarketDataExchangeInfoRequest#setSymbols(List)\n"
        + "     */\n"
        + "    public Builder addToSymbols(String item) {\n"
        + "      if (this.symbols == null) {\n"
        + "        this.symbols = CollectionUtil.createList();\n"
        + "      }\n"
        + "      this.symbols.add(item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataExchangeInfoRequest using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataExchangeInfoRequest build() {\n"
        + "      MyTestExchangeMarketDataExchangeInfoRequest res = new MyTestExchangeMarketDataExchangeInfoRequest();\n"
        + "      res.symbols = CollectionUtil.cloneList(this.symbols);\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataExchangeInfoRequest.java"))));
    
    Assert.assertEquals("package com.foo.bar.gen.marketdata.pojo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.foo.bar.ExchangeInfoResponseInterface1;\n"
        + "import com.foo.bar.ExchangeInfoResponseInterface2;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataExchangeInfoResponseDeserializer;\n"
        + "import com.foo.bar.gen.marketdata.pojo.serializers.MyTestExchangeMarketDataExchangeInfoResponseSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CollectionUtil;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.DeepCloneable;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Exchange info response\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyTestExchangeMarketDataExchangeInfoResponseSerializer.class)\n"
        + "@JsonDeserialize(using = MyTestExchangeMarketDataExchangeInfoResponseDeserializer.class)\n"
        + "public class MyTestExchangeMarketDataExchangeInfoResponse implements Pojo<MyTestExchangeMarketDataExchangeInfoResponse>, ExchangeInfoResponseInterface1, ExchangeInfoResponseInterface2 {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -7476378049371763608L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyTestExchangeMarketDataExchangeInfoResponse} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private Integer responseCode;\n"
        + "  private List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Request response code\n"
        + "   */\n"
        + "  public Integer getResponseCode() {\n"
        + "    return responseCode;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param responseCode Request response code\n"
        + "   */\n"
        + "  public void setResponseCode(Integer responseCode) {\n"
        + "    this.responseCode = responseCode;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return List of market information for each requested symbol\n"
        + "   */\n"
        + "  public List<MyTestExchangeMarketDataExchangeInfoResponsePayload> getPayload() {\n"
        + "    return payload;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param payload List of market information for each requested symbol\n"
        + "   */\n"
        + "  public void setPayload(List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload) {\n"
        + "    this.payload = payload;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyTestExchangeMarketDataExchangeInfoResponse o = (MyTestExchangeMarketDataExchangeInfoResponse) other;\n"
        + "    return Objects.equals(this.responseCode, o.responseCode)\n"
        + "        && Objects.equals(this.payload, o.payload);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyTestExchangeMarketDataExchangeInfoResponse other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.responseCode, other.responseCode);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compareLists(this.payload, other.payload, CompareUtil::compare);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(responseCode, payload);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyTestExchangeMarketDataExchangeInfoResponse deepClone() {\n"
        + "    MyTestExchangeMarketDataExchangeInfoResponse clone = new MyTestExchangeMarketDataExchangeInfoResponse();\n"
        + "    clone.responseCode = this.responseCode;\n"
        + "    clone.payload = CollectionUtil.deepCloneList(this.payload, DeepCloneable::deepClone);\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyTestExchangeMarketDataExchangeInfoResponse}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private Integer responseCode;\n"
        + "    private List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>responseCode</code> field in the builder\n"
        + "     * @param responseCode Request response code\n"
        + "     * @return Builder instance\n"
        + "     * @see #setResponseCode(Integer)\n"
        + "     */\n"
        + "    public Builder responseCode(Integer responseCode)  {\n"
        + "      this.responseCode = responseCode;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>payload</code> field in the builder\n"
        + "     * @param payload List of market information for each requested symbol\n"
        + "     * @return Builder instance\n"
        + "     * @see #setPayload(List<MyTestExchangeMarketDataExchangeInfoResponsePayload>)\n"
        + "     */\n"
        + "    public Builder payload(List<MyTestExchangeMarketDataExchangeInfoResponsePayload> payload)  {\n"
        + "      this.payload = payload;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add an item to the <code>payload</code> list.\n"
        + "     * @param item Item to add to current <code>payload</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyTestExchangeMarketDataExchangeInfoResponse#setPayload(List)\n"
        + "     */\n"
        + "    public Builder addToPayload(MyTestExchangeMarketDataExchangeInfoResponsePayload item) {\n"
        + "      if (this.payload == null) {\n"
        + "        this.payload = CollectionUtil.createList();\n"
        + "      }\n"
        + "      this.payload.add(item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyTestExchangeMarketDataExchangeInfoResponse using the values set in this builder\n"
        + "     */\n"
        + "    public MyTestExchangeMarketDataExchangeInfoResponse build() {\n"
        + "      MyTestExchangeMarketDataExchangeInfoResponse res = new MyTestExchangeMarketDataExchangeInfoResponse();\n"
        + "      res.responseCode = this.responseCode;\n"
        + "      res.payload = CollectionUtil.deepCloneList(this.payload, DeepCloneable::deepClone);\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        Files.readString(checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataExchangeInfoResponse.java"))));
    
    checkSourceFileExists(Paths.get("pojo", "MyTestExchangeMarketDataExchangeInfoResponsePayload.java"));
    
    checkJavaFilesCount(Paths.get("pojo/serializers"), 3);
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataExchangeInfoRequestSerializer.java"));        
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataExchangeInfoResponsePayloadSerializer.java"));
    checkSourceFileExists(Paths.get("pojo/serializers", "MyTestExchangeMarketDataExchangeInfoResponseSerializer.java"));  
    
    checkJavaFilesCount(Paths.get("pojo/deserializers"), 3);
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataExchangeInfoRequestDeserializer.java"));
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataExchangeInfoResponseDeserializer.java"));
    checkSourceFileExists(Paths.get("pojo/deserializers", "MyTestExchangeMarketDataExchangeInfoResponsePayloadDeserializer.java"));
  }

  @Test
  public void testGenerateClassesSpecificApiRequestTypesPrimitiveType() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeInt", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    
    checkJavaFilesCount(Paths.get("pojo"), 3);
    checkSourceFileExists(Paths.get("pojo", "GenericResponse.java"));
    
    checkJavaFilesCount(Paths.get("pojo/deserializers"), 1);
    checkSourceFileExists(Paths.get("pojo/deserializers", "GenericResponseDeserializer.java"));
    
    checkJavaFilesCount(Paths.get("pojo/serializers"), 1);
    checkSourceFileExists(Paths.get("pojo/serializers", "GenericResponseSerializer.java"));           
  }
  
  @Test
  public void testGenerateClassesSpecificApiRequestTypesPrimitiveListType() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeIntListWithDefaultValue", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(srcFolder, 0);        
  }
  
  @Test
  public void testGenerateClassesSpecificApiRequestTypesNoParametersRequest() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestNoParameters", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(srcFolder, 0);        
  }
  
  @Test
  public void testGenerateClassesSpecificApiResponseTypesPrimitiveType() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("getRestResponseDataTypeInt", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(srcFolder, 0); 
  }
  
  @Test
  public void testGenerateClassesSpecificApiResponseTypesPrimitiveListType() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("getRestResponseDataTypeIntList", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(srcFolder, 0); 
  }
  
  @Test
  public void testGenerateClassesSpecificApiResponseTypesEmptyResponse() throws Exception {
    srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("getRestEmptyResponseDataType", api);
    RestEndpointClassesGenerator generator = new RestEndpointClassesGenerator(exchange, api, restEndpoint, null);
    generator.generateClasses(srcFolder);
    checkJavaFilesCount(srcFolder, 0); 
  }
}
