package org.jxapi.generator.java.exchange.constants;

import java.util.List;
import java.util.Map;

import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.DefaultConfigProperty;
import org.jxapi.exchange.descriptor.Type;
import org.jxapi.util.PlaceHolderResolver;

/**
 * Unit test for {@link PropertiesClassGenerator}
 */
public class PropertiesClassGeneratorTest {

    @Test
    public void testGenerate() {
        DefaultConfigProperty stringProp = DefaultConfigProperty.create("myString", Type.STRING, "My String property, for instance '${sampleMyStringValue}'", "foo");
        DefaultConfigProperty stringPropWithNoDescriptionNoDefaultValue = DefaultConfigProperty.create("myStringWithNoDescriptionNoDefaultValue", Type.STRING, null, null);
        DefaultConfigProperty intProp = DefaultConfigProperty.create("myInt", Type.INT, "My int property", 42);
        DefaultConfigProperty longProp = DefaultConfigProperty.create("myLong", Type.LONG, "My long property", 1234567890123456L);
        DefaultConfigProperty boolProp = DefaultConfigProperty.create("myBool", Type.BOOLEAN, "My boolean property", true);
        DefaultConfigProperty bigDecimalProp = DefaultConfigProperty.create("myBigDecimal", Type.BIGDECIMAL, "My BigDecimal property", 1.2345);
        PlaceHolderResolver placeholderResolver = PlaceHolderResolver.create(Map.of("sampleMyStringValue", "bar"));
        PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", "myExchange", 
            List.of(stringProp, 
                stringPropWithNoDescriptionNoDefaultValue, 
                intProp, 
                longProp, 
                boolProp, 
                bigDecimalProp),
                placeholderResolver);
        String expected =  "package com.x.y;\n"
            + "\n"
            + "import java.math.BigDecimal;\n"
            + "import java.util.List;\n"
            + "import java.util.Properties;\n"
            + "\n"
            + "import javax.annotation.processing.Generated;\n"
            + "import org.jxapi.exchange.descriptor.ConfigProperty;\n"
            + "import org.jxapi.exchange.descriptor.DefaultConfigProperty;\n"
            + "import org.jxapi.exchange.descriptor.Type;\n"
            + "import org.jxapi.util.PropertiesUtil;\n"
            + "\n"
            + "/**\n"
            + " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
            + " * <table>\n"
            + " *   <caption>myExchange properties</caption>\n"
            + " *   <tr>\n"
            + " *     <th>Name</th>\n"
            + " *     <th>Type</th>\n"
            + " *     <th>Description</th>\n"
            + " *     <th>Default value</th>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myString</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td>My String property, for instance 'bar'</td>\n"
            + " *     <td>foo</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myStringWithNoDescriptionNoDefaultValue</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td></td>\n"
            + " *     <td></td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myInt</td>\n"
            + " *     <td>INT</td>\n"
            + " *     <td>My int property</td>\n"
            + " *     <td>42</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myLong</td>\n"
            + " *     <td>LONG</td>\n"
            + " *     <td>My long property</td>\n"
            + " *     <td>1234567890123456</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBool</td>\n"
            + " *     <td>BOOLEAN</td>\n"
            + " *     <td>My boolean property</td>\n"
            + " *     <td>true</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBigDecimal</td>\n"
            + " *     <td>BIGDECIMAL</td>\n"
            + " *     <td>My BigDecimal property</td>\n"
            + " *     <td>1.2345</td>\n"
            + " *   </tr>\n"
            + " * </table>\n"
            + " * <br>\n"
            + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
            + " * @see ConfigProperty\n"
            + " */\n"
            + "@Generated(\"org.jxapi.generator.java.exchange.constants.PropertiesClassGenerator\")\n"
            + "public class MyProperties {\n"
            + "  \n"
            + "  private MyProperties(){}\n"
            + "  \n"
            + "  /**\n"
            + "   * My String property, for instance 'bar'\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_STRING = DefaultConfigProperty.create(\n"
            + "    \"myString\",\n"
            + "    Type.STRING,\n"
            + "    \"My String property, for instance 'bar'\",\n"
            + "    \"foo\");\n"
            + "  \n"
            + "  \n"
            + "  public static final ConfigProperty MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE = DefaultConfigProperty.create(\n"
            + "    \"myStringWithNoDescriptionNoDefaultValue\",\n"
            + "    Type.STRING,\n"
            + "    null,\n"
            + "    null);\n"
            + "  \n"
            + "  /**\n"
            + "   * My int property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_INT = DefaultConfigProperty.create(\n"
            + "    \"myInt\",\n"
            + "    Type.INT,\n"
            + "    \"My int property\",\n"
            + "    \"42\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My long property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_LONG = DefaultConfigProperty.create(\n"
            + "    \"myLong\",\n"
            + "    Type.LONG,\n"
            + "    \"My long property\",\n"
            + "    \"1234567890123456\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My boolean property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BOOL = DefaultConfigProperty.create(\n"
            + "    \"myBool\",\n"
            + "    Type.BOOLEAN,\n"
            + "    \"My boolean property\",\n"
            + "    \"true\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My BigDecimal property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BIG_DECIMAL = DefaultConfigProperty.create(\n"
            + "    \"myBigDecimal\",\n"
            + "    Type.BIGDECIMAL,\n"
            + "    \"My BigDecimal property\",\n"
            + "    \"1.2345\");\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myString' property.\n"
            + "   * @param properties Properties to look for value of 'myString' property into.\n"
            + "   * @return Value found in properties or default value 'foo' if not found.\n"
            + "   */\n"
            + "  public static String getMyString(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myStringWithNoDescriptionNoDefaultValue' property.\n"
            + "   * @param properties Properties to look for value of 'myStringWithNoDescriptionNoDefaultValue' property into.\n"
            + "   * @return Value found in properties or <code>null</code> if not found.\n"
            + "   */\n"
            + "  public static String getMyStringWithNoDescriptionNoDefaultValue(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myInt' property.\n"
            + "   * @param properties Properties to look for value of 'myInt' property into.\n"
            + "   * @return Value found in properties or default value '42' if not found.\n"
            + "   */\n"
            + "  public static Integer getMyInt(Properties properties) {return PropertiesUtil.getInt(properties, MY_INT);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myLong' property.\n"
            + "   * @param properties Properties to look for value of 'myLong' property into.\n"
            + "   * @return Value found in properties or default value '1234567890123456' if not found.\n"
            + "   */\n"
            + "  public static Long getMyLong(Properties properties) {return PropertiesUtil.getLong(properties, MY_LONG);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBool' property.\n"
            + "   * @param properties Properties to look for value of 'myBool' property into.\n"
            + "   * @return Value found in properties or default value 'true' if not found.\n"
            + "   */\n"
            + "  public static Boolean isMyBool(Properties properties) {return PropertiesUtil.getBoolean(properties, MY_BOOL);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBigDecimal' property.\n"
            + "   * @param properties Properties to look for value of 'myBigDecimal' property into.\n"
            + "   * @return Value found in properties or default value '1.2345' if not found.\n"
            + "   */\n"
            + "  public static BigDecimal getMyBigDecimal(Properties properties) {return PropertiesUtil.getBigDecimal(properties, MY_BIG_DECIMAL);}\n"
            + "  \n"
            + "  /**\n"
            + "   * List of all configuration properties defined in this class\n"
            + "   */\n"
            + "  public static final List<ConfigProperty> ALL = List.of(\n"
            + "    MY_STRING, \n"
            + "    MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE, \n"
            + "    MY_INT, \n"
            + "    MY_LONG, \n"
            + "    MY_BOOL, \n"
            + "    MY_BIG_DECIMAL);\n"
            + "}\n";
        Assert.assertEquals(expected, gen.generate());
    }
    
    @Test
    public void testGenerate_EmptyProperties() {      
      PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", "myExchange", List.of(), PlaceHolderResolver.NO_OP);
      Assert.assertEquals("package com.x.y;\n"
          + "\n"
          + "import java.util.List;\n"
          + "\n"
          + "import javax.annotation.processing.Generated;\n"
          + "import org.jxapi.exchange.descriptor.ConfigProperty;\n"
          + "\n"
          + "/**\n"
          + " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
          + " * <table>\n"
          + " *   <caption>myExchange properties</caption>\n"
          + " *   <tr>\n"
          + " *     <th>Name</th>\n"
          + " *     <th>Type</th>\n"
          + " *     <th>Description</th>\n"
          + " *     <th>Default value</th>\n"
          + " *   </tr>\n"
          + " * </table>\n"
          + " * <br>\n"
          + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
          + " * @see ConfigProperty\n"
          + " */\n"
          + "@Generated(\"org.jxapi.generator.java.exchange.constants.PropertiesClassGenerator\")\n"
          + "public class MyProperties {\n"
          + "  \n"
          + "  private MyProperties(){}\n"
          + "  \n"
          + "  /**\n"
          + "   * List of all configuration properties defined in this class\n"
          + "   */\n"
          + "  public static final List<ConfigProperty> ALL = List.of(\n"
          + "    );\n"
          + "}\n"
          + "", gen.generate());
    }
}
