package com.scz.jxapi.generator.java.exchange.api.demo;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import com.scz.jxapi.exchange.descriptor.ExchangeApiDescriptor;
import com.scz.jxapi.exchange.descriptor.ExchangeDescriptor;
import com.scz.jxapi.exchange.descriptor.WebsocketEndpointDescriptor;
import com.scz.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import com.scz.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;

/**
 * Unit test for {@link WebsocketEndpointDemoGenerator}
 */
public class WebsocketEndpointDemoGeneratorTest {
	
	@Test
	public void testGenerateWebsocketEndpointDemoObjectRequest() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		WebsocketEndpointDescriptor websocketEndpointDescriptor = exchangeApiDescriptor.getWebsocketEndpoints().get(0);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.DemoProperties;\n"
				+ "import com.scz.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest, com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataTickerStreamDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataTickerStreamDemo.class);\n"
				+ "  \n"
				+ "  public static MyTestExchangeMarketDataTickerStreamRequest createRequest() {\n"
				+ "    MyTestExchangeMarketDataTickerStreamRequest request = new MyTestExchangeMarketDataTickerStreamRequest();\n"
				+ "    request.setSymbol(\"BTC_USDT\");\n"
				+ "    return request;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * {@link MyTestExchangeMarketDataApi#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest, com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
				+ "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
				+ "   * @param request                            The subscription request\n"
				+ "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
				+ "   * @param configProperties                   Exchange configuration properties.\n"
				+ "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
				+ "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
				+ "   */\n"
				+ "  public static void subscribe(MyTestExchangeMarketDataTickerStreamRequest request,\n"
				+ "                               WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> messageListener,\n"
				+ "                               Properties configProperties,\n"
				+ "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
				+ "    MyTestExchangeMarketDataApi api = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties).getMyTestExchangeMarketDataApi();long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
				+ "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
				+ "    \n"
				+ "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData tickerStream' for {} ms with request:{}\", subscriptionDuration, request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    String subId = api.subscribeTickerStream(request, messageListener);\n"
				+ "    Thread.sleep(subscriptionDuration);\n"
				+ "    log.info(\"Unubscribing from 'MyTestExchange MarketData tickerStream' stream\");\n"
				+ "    api.unsubscribeTickerStream(subId);\n"
				+ "    Thread.sleep(delayBeforeExit);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs websocket endpoint 'MyTestExchange MarketData tickerStream' subscription demo.\n"
				+ "   * @param args no arguments expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      subscribe(createRequest(),\n"
				+ "                DemoUtil::logWsMessage,\n"
				+ "                DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "                DemoUtil::logWsApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n"
				+ "", 
				new WebsocketEndpointDemoGenerator(exchangeDescriptor, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
	}
	
	@Test
	public void testGenerateWebsocketEndpointDemoSpecificRequesTypePrimitiveStringWithNamedArg() throws Exception {
		ExchangeDescriptor exchange = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchange.getApis().get(0);
		WebsocketEndpointDescriptor websocketEndpointDescriptor = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithStringRequestDataType", exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.DemoProperties;\n"
				+ "import com.scz.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeStreamWithStringRequestDataType(java.lang.String, com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataStreamWithStringRequestDataTypeDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataStreamWithStringRequestDataTypeDemo.class);\n"
				+ "  \n"
				+ "  public static String createSymbol() {\n"
				+ "    return \"BTC_USDT\";\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * {@link MyTestExchangeMarketDataApi#subscribeStreamWithStringRequestDataType(java.lang.String, com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
				+ "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
				+ "   * @param request                            The subscription request\n"
				+ "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
				+ "   * @param configProperties                   Exchange configuration properties.\n"
				+ "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
				+ "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
				+ "   */\n"
				+ "  public static void subscribe(String request,\n"
				+ "                               WebsocketListener<Ticker> messageListener,\n"
				+ "                               Properties configProperties,\n"
				+ "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
				+ "    MyTestExchangeMarketDataApi api = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties).getMyTestExchangeMarketDataApi();long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
				+ "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
				+ "    \n"
				+ "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData streamWithStringRequestDataType' for {} ms with request:{}\", subscriptionDuration, request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    String subId = api.subscribeStreamWithStringRequestDataType(request, messageListener);\n"
				+ "    Thread.sleep(subscriptionDuration);\n"
				+ "    log.info(\"Unubscribing from 'MyTestExchange MarketData streamWithStringRequestDataType' stream\");\n"
				+ "    api.unsubscribeStreamWithStringRequestDataType(subId);\n"
				+ "    Thread.sleep(delayBeforeExit);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs websocket endpoint 'MyTestExchange MarketData streamWithStringRequestDataType' subscription demo.\n"
				+ "   * @param args no arguments expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      subscribe(createSymbol(),\n"
				+ "                DemoUtil::logWsMessage,\n"
				+ "                DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "                DemoUtil::logWsApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n"
				+ "", 
				new WebsocketEndpointDemoGenerator(exchange, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
	}
	
	@Test
	public void testGenerateWebsocketEndpointDemoZeroArgs() throws Exception {
		ExchangeDescriptor exchange = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchange.getApis().get(0);
		WebsocketEndpointDescriptor websocketEndpointDescriptor = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithObjectRequestDataTypeZeroParameters", exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.DemoProperties;\n"
				+ "import com.scz.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectRequestDataTypeZeroParameters(com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersDemo.class);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectRequestDataTypeZeroParameters(com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
				+ "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
				+ "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
				+ "   * @param configProperties                   Exchange configuration properties.\n"
				+ "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
				+ "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
				+ "   */\n"
				+ "  public static void subscribe(WebsocketListener<Ticker> messageListener,\n"
				+ "                               Properties configProperties,\n"
				+ "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
				+ "    MyTestExchangeMarketDataApi api = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties).getMyTestExchangeMarketDataApi();long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
				+ "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
				+ "    \n"
				+ "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData streamWithObjectRequestDataTypeZeroParameters' for {} ms\", subscriptionDuration);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    String subId = api.subscribeStreamWithObjectRequestDataTypeZeroParameters(messageListener);\n"
				+ "    Thread.sleep(subscriptionDuration);\n"
				+ "    log.info(\"Unubscribing from 'MyTestExchange MarketData streamWithObjectRequestDataTypeZeroParameters' stream\");\n"
				+ "    api.unsubscribeStreamWithObjectRequestDataTypeZeroParameters(subId);\n"
				+ "    Thread.sleep(delayBeforeExit);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs websocket endpoint 'MyTestExchange MarketData streamWithObjectRequestDataTypeZeroParameters' subscription demo.\n"
				+ "   * @param args no arguments expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      subscribe(DemoUtil::logWsMessage,\n"
				+ "                DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "                DemoUtil::logWsApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n"
				+ "", 
				new WebsocketEndpointDemoGenerator(exchange, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
	}
	
	@Test
	public void testGenerateWebsocketEndpointSpecificRequestTypeObjectListMapWithObjectDefinedInDifferentAPI() throws Exception {
		ExchangeDescriptor exchange = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchange.getApis().get(0);
		WebsocketEndpointDescriptor websocketEndpointDescriptor = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithObjectListMapRequestDataType", exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Properties;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MultiSymbol;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.MapJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.StringJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.DemoProperties;\n"
				+ "import com.scz.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectListMapRequestDataType(java.util.Map, com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataStreamWithObjectListMapRequestDataTypeDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataStreamWithObjectListMapRequestDataTypeDemo.class);\n"
				+ "  \n"
				+ "  public static Map<String, List<MultiSymbol>> createRequest() {\n"
				+ "    MultiSymbol requestItem = new MultiSymbol();\n"
				+ "    requestItem.setSymbolList(new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance()).deserialize(\"[BTC_USDT, ETH_USDT]\"));\n"
				+ "    requestItem.setSymbolMap(new MapJsonFieldDeserializer<>(new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance())).deserialize(\"{USDT=[BTC_USDT, ETH]}\"));\n"
				+ "    SingleSymbol requestItem_symbolObject = new SingleSymbol();\n"
				+ "    requestItem_symbolObject.setSymbol(\"BTC_USDT\");\n"
				+ "    requestItem.setSymbolObject(requestItem_symbolObject);\n"
				+ "    return Map.of(\"spot\", List.of(requestItem));\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectListMapRequestDataType(java.util.Map, com.scz.jxapi.netutils.websocket.WebsocketListener)}.\n"
				+ "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
				+ "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
				+ "   * @param request                            The subscription request\n"
				+ "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
				+ "   * @param configProperties                   Exchange configuration properties.\n"
				+ "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
				+ "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
				+ "   */\n"
				+ "  public static void subscribe(Map<String, List<MultiSymbol>> request,\n"
				+ "                               WebsocketListener<Ticker> messageListener,\n"
				+ "                               Properties configProperties,\n"
				+ "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
				+ "    MyTestExchangeMarketDataApi api = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties).getMyTestExchangeMarketDataApi();long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
				+ "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
				+ "    \n"
				+ "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData streamWithObjectListMapRequestDataType' for {} ms with request:{}\", subscriptionDuration, request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    String subId = api.subscribeStreamWithObjectListMapRequestDataType(request, messageListener);\n"
				+ "    Thread.sleep(subscriptionDuration);\n"
				+ "    log.info(\"Unubscribing from 'MyTestExchange MarketData streamWithObjectListMapRequestDataType' stream\");\n"
				+ "    api.unsubscribeStreamWithObjectListMapRequestDataType(subId);\n"
				+ "    Thread.sleep(delayBeforeExit);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs websocket endpoint 'MyTestExchange MarketData streamWithObjectListMapRequestDataType' subscription demo.\n"
				+ "   * @param args no arguments expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      subscribe(createRequest(),\n"
				+ "                DemoUtil::logWsMessage,\n"
				+ "                DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "                DemoUtil::logWsApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n"
				+ "", 
				new WebsocketEndpointDemoGenerator(exchange, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
	}

}
