package org.jxapi.generator.java.exchange.api.pojo;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.Field;
import org.jxapi.exchange.descriptor.Type;

/**
 * Unit test for {@link PojoGenerator}
 */
public class PojoGeneratorTest {

	@Test
	public void testGenerate() {
		String typeName = "com.x.MyPojo";
		String typeDescription = "Used in PojoGeneratorTest";
		List<Field> properties = List.of(
		  Field.builder().type(Type.LONG).name("id").build(),
		  Field.builder().type(Type.INT).name("score").description("Current score").build(),
		  Field.builder().type("OBJECT_LIST").name("foo").msgField("f").description("The foo")
						 .property(Field.builder().type(Type.TIMESTAMP).name("time").description("Creation time").build())
						 .property(Field.builder().name("bar").description("The bar")
								 				  .property(Field.builder().type(Type.STRING).name("name").build())
								 				  .build())
						 .build(),
		  Field.builder().type("OBJECT_LIST_MAP").name("toto").description("Toto")
						 .property(Field.builder().type(Type.STRING).name("id").description("Toto ID").build())
						 .build()
		);
		
		PojoGenerator generator = new PojoGenerator(typeName, typeDescription, properties, List.of("com.x.common.MyInterface"));
		Assert.assertEquals("package com.x;\n"
				+ "\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Objects;\n"
				+ "\n"
				+ "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
				+ "import com.x.common.MyInterface;\n"
				+ "import com.x.serializers.MyPojoSerializer;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.util.CollectionUtil;\n"
				+ "import org.jxapi.util.CompareUtil;\n"
				+ "import org.jxapi.util.DeepCloneable;\n"
				+ "import org.jxapi.util.EncodingUtil;\n"
				+ "import org.jxapi.util.Pojo;\n"
				+ "\n"
				+ "/**\n"
				+ " * Used in PojoGeneratorTest\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.pojo.PojoGenerator\")\n"
				+ "@JsonSerialize(using = MyPojoSerializer.class)\n"
				+ "public class MyPojo implements Pojo<MyPojo>, MyInterface {\n"
				+ "  \n"
				+ "  private static final long serialVersionUID = 926407479345105954L;\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return A new builder to build {@link MyPojo} objects\n"
				+ "   */\n"
				+ "  public static Builder builder() {\n"
				+ "    return new Builder();\n"
				+ "  }\n"
				+ "  \n"
				+ "  private Long id;\n"
				+ "  private Integer score;\n"
				+ "  private List<MyPojoFoo> foo;\n"
				+ "  private Map<String, List<MyPojoToto>> toto;\n"
				+ "  \n"
				+ "  public Long getId() {\n"
				+ "    return id;\n"
				+ "  }\n"
				+ "  \n"
				+ "  public void setId(Long id) {\n"
				+ "    this.id = id;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return Current score\n"
				+ "   */\n"
				+ "  public Integer getScore() {\n"
				+ "    return score;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param score Current score\n"
				+ "   */\n"
				+ "  public void setScore(Integer score) {\n"
				+ "    this.score = score;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return The foo Message field <strong>f</strong>\n"
				+ "   */\n"
				+ "  public List<MyPojoFoo> getFoo() {\n"
				+ "    return foo;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param foo The foo Message field <strong>f</strong>\n"
				+ "   */\n"
				+ "  public void setFoo(List<MyPojoFoo> foo) {\n"
				+ "    this.foo = foo;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return Toto\n"
				+ "   */\n"
				+ "  public Map<String, List<MyPojoToto>> getToto() {\n"
				+ "    return toto;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param toto Toto\n"
				+ "   */\n"
				+ "  public void setToto(Map<String, List<MyPojoToto>> toto) {\n"
				+ "    this.toto = toto;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean equals(Object other) {\n"
				+ "    if (other == null)\n"
				+ "      return false;\n"
				+ "    if (!getClass().equals(other.getClass()))\n"
				+ "      return false;\n"
				+ "    MyPojo o = (MyPojo) other;\n"
				+ "    return Objects.equals(id, o.id)\n"
				+ "            && Objects.equals(score, o.score)\n"
				+ "            && Objects.equals(foo, o.foo)\n"
				+ "            && Objects.equals(toto, o.toto);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int compareTo(MyPojo other) {\n"
				+ "    if (other == null) {\n"
				+ "      return 1;\n"
				+ "    }\n"
				+ "    int res = 0;\n"
				+ "    res = CompareUtil.compare(this.id, other.id);\n"
				+ "    if (res != 0) {\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "    res = CompareUtil.compare(this.score, other.score);\n"
				+ "    if (res != 0) {\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "    res = CompareUtil.compareLists(this.foo, other.foo, CompareUtil::compare);\n"
				+ "    if (res != 0) {\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "    res = CompareUtil.compareMaps(this.toto, other.toto, (l0a, l0b) -> CollectionUtil.compareLists(l0a,l0b, CompareUtil::compare));\n"
				+ "    return res;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int hashCode() {\n"
				+ "    return Objects.hash(id, score, foo, toto);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public MyPojo deepClone() {\n"
				+ "    MyPojo clone = new MyPojo();\n"
				+ "    clone.id = this.id;\n"
				+ "    clone.score = this.score;\n"
				+ "    clone.foo = CollectionUtil.deepCloneList(this.foo, DeepCloneable::deepClone);\n"
				+ "    clone.toto = CollectionUtil.deepCloneMap(this.toto, l0 -> CollectionUtil.deeplCloneList(l0, DeepCloneable::deepClone));\n"
				+ "    return clone;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String toString() {\n"
				+ "    return EncodingUtil.pojoToString(this);\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Builder for {@link MyPojo}\n"
				+ "   */\n"
				+ "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
				+ "  public static class Builder {\n"
				+ "    \n"
				+ "    private Long id;\n"
				+ "    private Integer score;\n"
				+ "    private List<MyPojoFoo> foo;\n"
				+ "    private Map<String, List<MyPojoToto>> toto;\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>id</code> field in the builder\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setId(Long)\n"
				+ "     */\n"
				+ "    public Builder id(Long id)  {\n"
				+ "      this.id = id;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>score</code> field in the builder\n"
				+ "     * @param score Current score\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setScore(Integer)\n"
				+ "     */\n"
				+ "    public Builder score(Integer score)  {\n"
				+ "      this.score = score;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>foo</code> field in the builder\n"
				+ "     * @param foo The foo Message field <strong>f</strong>\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setFoo(List<MyPojoFoo>)\n"
				+ "     */\n"
				+ "    public Builder foo(List<MyPojoFoo> foo)  {\n"
				+ "      this.foo = foo;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will add an item to the <code>foo</code> list.\n"
				+ "     * @param item Item to add to current <code>foo</code> list\n"
				+ "     * @return Builder instance\n"
				+ "     * @see MyPojo#setFoo(MyPojoFoo)\n"
				+ "     */\n"
				+ "    public Builder addToFoo(MyPojoFoo item) {\n"
				+ "      if (this.foo == null) {\n"
				+ "        this.foo = CollectionUtil.createList();\n"
				+ "      }\n"
				+ "      this.foo.add(item);\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>toto</code> field in the builder\n"
				+ "     * @param toto Toto\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setToto(Map<String, List<MyPojoToto>>)\n"
				+ "     */\n"
				+ "    public Builder toto(Map<String, List<MyPojoToto>> toto)  {\n"
				+ "      this.toto = toto;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will add or update a key/value pair to the <code>toto</code> map.\n"
				+ "     * @param item Item to add to current <code>toto</code> list\n"
				+ "     * @return Builder instance\n"
				+ "     * @see MyPojo#setToto(List<MyPojoToto>)\n"
				+ "     */\n"
				+ "    public Builder addToToto(String key, List<MyPojoToto> item) {\n"
				+ "      if (this.toto == null) {\n"
				+ "        this.toto = CollectionUtil.createMap();\n"
				+ "      }\n"
				+ "      this.toto.put(key, item);\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * @return a new instance of MyPojo using the values set in this builder\n"
				+ "     */\n"
				+ "    public MyPojo build() {\n"
				+ "      MyPojo res = new MyPojo();\n"
				+ "      res.id = this.id;\n"
				+ "      res.score = this.score;\n"
				+ "      res.foo = CollectionUtil.deepCloneList(this.foo, DeepCloneable::deepClone);\n"
				+ "      res.toto = CollectionUtil.deepCloneMap(this.toto, l0 -> CollectionUtil.deeplCloneList(l0, DeepCloneable::deepClone));\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
		Assert.assertEquals(properties, generator.getFields());
	}
	
	@Test
	public void testGenerate_ImplicitObjectType() {
		String typeName = "com.x.pojo.MyPojoWithNullAdditionnalBody";
		String typeDescription = "Used in PojoGeneratorTest";
		List<Field> properties = List.of(
			Field.builder()
			.name("myObj")
			.description("identifier")
			  .properties(List.of(
					  Field.builder().type(Type.LONG).name("id").description("identifier").build()))
			.build()
		);
		PojoGenerator generator = new PojoGenerator(typeName, typeDescription, properties, null);
		Assert.assertEquals("package com.x.pojo;\n"
				+ "\n"
				+ "import java.util.Objects;\n"
				+ "\n"
				+ "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
				+ "import com.x.serializers.MyPojoWithNullAdditionnalBodySerializer;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.util.CompareUtil;\n"
				+ "import org.jxapi.util.EncodingUtil;\n"
				+ "import org.jxapi.util.Pojo;\n"
				+ "\n"
				+ "/**\n"
				+ " * Used in PojoGeneratorTest\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.pojo.PojoGenerator\")\n"
				+ "@JsonSerialize(using = MyPojoWithNullAdditionnalBodySerializer.class)\n"
				+ "public class MyPojoWithNullAdditionnalBody implements Pojo<MyPojoWithNullAdditionnalBody> {\n"
				+ "  \n"
				+ "  private static final long serialVersionUID = -8553450902608483823L;\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return A new builder to build {@link MyPojoWithNullAdditionnalBody} objects\n"
				+ "   */\n"
				+ "  public static Builder builder() {\n"
				+ "    return new Builder();\n"
				+ "  }\n"
				+ "  \n"
				+ "  private MyPojoWithNullAdditionnalBodyMyObj myObj;\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return identifier\n"
				+ "   */\n"
				+ "  public MyPojoWithNullAdditionnalBodyMyObj getMyObj() {\n"
				+ "    return myObj;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param myObj identifier\n"
				+ "   */\n"
				+ "  public void setMyObj(MyPojoWithNullAdditionnalBodyMyObj myObj) {\n"
				+ "    this.myObj = myObj;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean equals(Object other) {\n"
				+ "    if (other == null)\n"
				+ "      return false;\n"
				+ "    if (!getClass().equals(other.getClass()))\n"
				+ "      return false;\n"
				+ "    MyPojoWithNullAdditionnalBody o = (MyPojoWithNullAdditionnalBody) other;\n"
				+ "    return Objects.equals(myObj, o.myObj);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int compareTo(MyPojoWithNullAdditionnalBody other) {\n"
				+ "    if (other == null) {\n"
				+ "      return 1;\n"
				+ "    }\n"
				+ "    int res = 0;\n"
				+ "    res = CompareUtil.compare(this.myObj, other.myObj);\n"
				+ "    return res;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int hashCode() {\n"
				+ "    return Objects.hash(myObj);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public MyPojoWithNullAdditionnalBody deepClone() {\n"
				+ "    MyPojoWithNullAdditionnalBody clone = new MyPojoWithNullAdditionnalBody();\n"
				+ "    clone.myObj = this.myObj != null ? this.myObj.deepClone() : null;\n"
				+ "    return clone;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String toString() {\n"
				+ "    return EncodingUtil.pojoToString(this);\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Builder for {@link MyPojoWithNullAdditionnalBody}\n"
				+ "   */\n"
				+ "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
				+ "  public static class Builder {\n"
				+ "    \n"
				+ "    private MyPojoWithNullAdditionnalBodyMyObj myObj;\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>myObj</code> field in the builder\n"
				+ "     * @param myObj identifier\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setMyObj(MyPojoWithNullAdditionnalBodyMyObj)\n"
				+ "     */\n"
				+ "    public Builder myObj(MyPojoWithNullAdditionnalBodyMyObj myObj)  {\n"
				+ "      this.myObj = myObj;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * @return a new instance of MyPojoWithNullAdditionnalBody using the values set in this builder\n"
				+ "     */\n"
				+ "    public MyPojoWithNullAdditionnalBody build() {\n"
				+ "      MyPojoWithNullAdditionnalBody res = new MyPojoWithNullAdditionnalBody();\n"
				+ "      res.myObj = this.myObj != null ? this.myObj.deepClone() : null;\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
		Assert.assertEquals(properties, generator.getFields());
	}
	
	@Test
	public void testGenerate_NullProperties() {
		String typeName = "com.x.pojo.MyPojoWithNullProperties";
		String typeDescription = "Used in PojoGeneratorTest";
		PojoGenerator generator = new PojoGenerator(typeName, typeDescription, null, null);
		Assert.assertEquals("package com.x.pojo;\n"
				+ "\n"
				+ "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
				+ "import com.x.serializers.MyPojoWithNullPropertiesSerializer;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.util.EncodingUtil;\n"
				+ "import org.jxapi.util.Pojo;\n"
				+ "\n"
				+ "/**\n"
				+ " * Used in PojoGeneratorTest\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.pojo.PojoGenerator\")\n"
				+ "@JsonSerialize(using = MyPojoWithNullPropertiesSerializer.class)\n"
				+ "public class MyPojoWithNullProperties implements Pojo<MyPojoWithNullProperties> {\n"
				+ "  \n"
				+ "  private static final long serialVersionUID = 739302860581584369L;\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return A new builder to build {@link MyPojoWithNullProperties} objects\n"
				+ "   */\n"
				+ "  public static Builder builder() {\n"
				+ "    return new Builder();\n"
				+ "  }\n"
				+ "  \n"
				+ "  \n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean equals(Object other) {\n"
				+ "    if (other == null)\n"
				+ "      return false;\n"
				+ "    if (!getClass().equals(other.getClass()))\n"
				+ "      return false;\n"
				+ "    return true;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int compareTo(MyPojoWithNullProperties other) {\n"
				+ "    if (other == null) {\n"
				+ "      return 1;\n"
				+ "    }\n"
				+ "    return 0;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int hashCode() {\n"
				+ "    return 31 * getClass().hashCode();\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public MyPojoWithNullProperties deepClone() {\n"
				+ "    return new MyPojoWithNullProperties();\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String toString() {\n"
				+ "    return EncodingUtil.pojoToString(this);\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Builder for {@link MyPojoWithNullProperties}\n"
				+ "   */\n"
				+ "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
				+ "  public static class Builder {\n"
				+ "    \n"
				+ "    \n"
				+ "    \n"
				+ "    /**\n"
				+ "     * @return a new instance of MyPojoWithNullProperties using the values set in this builder\n"
				+ "     */\n"
				+ "    public MyPojoWithNullProperties build() {\n"
				+ "      return new MyPojoWithNullProperties();\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
		Assert.assertEquals(List.of(), generator.getFields());
	}
	
	@Test
	public void testGeneratePojoCodeMultipleFields() {
		PojoGenerator generator = new PojoGenerator("x.y.z.pojo.Foo");
		generator.addField(Field.builder().type(Type.STRING).name("name").description("the name").build());
		generator.addField(Field.builder().objectName("Bar").name("bar").msgField("b").build());
		generator.addField(Field.builder().type(Type.INT).name("a").description("lower case 'a'").build());
		generator.addField(Field.builder().type(Type.INT).name("A").description("upper case 'A'").build());
		
		Assert.assertEquals("package x.y.z.pojo;\n"
				+ "\n"
				+ "import java.util.Objects;\n"
				+ "\n"
				+ "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.util.CompareUtil;\n"
				+ "import org.jxapi.util.EncodingUtil;\n"
				+ "import org.jxapi.util.Pojo;\n"
				+ "import x.y.z.serializers.FooSerializer;\n"
				+ "\n"
				+ "\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.pojo.PojoGenerator\")\n"
				+ "@JsonSerialize(using = FooSerializer.class)\n"
				+ "public class Foo implements Pojo<Foo> {\n"
				+ "  \n"
				+ "  private static final long serialVersionUID = -9000906500822625072L;\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return A new builder to build {@link Foo} objects\n"
				+ "   */\n"
				+ "  public static Builder builder() {\n"
				+ "    return new Builder();\n"
				+ "  }\n"
				+ "  \n"
				+ "  private String name;\n"
				+ "  private Bar bar;\n"
				+ "  private Integer a;\n"
				+ "  private Integer A;\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return the name\n"
				+ "   */\n"
				+ "  public String getName() {\n"
				+ "    return name;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param name the name\n"
				+ "   */\n"
				+ "  public void setName(String name) {\n"
				+ "    this.name = name;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return Message field <strong>b</strong>\n"
				+ "   */\n"
				+ "  public Bar getBar() {\n"
				+ "    return bar;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param bar Message field <strong>b</strong>\n"
				+ "   */\n"
				+ "  public void setBar(Bar bar) {\n"
				+ "    this.bar = bar;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return lower case 'a'\n"
				+ "   */\n"
				+ "  public Integer geta() {\n"
				+ "    return a;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param a lower case 'a'\n"
				+ "   */\n"
				+ "  public void seta(Integer a) {\n"
				+ "    this.a = a;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @return upper case 'A'\n"
				+ "   */\n"
				+ "  public Integer getA() {\n"
				+ "    return A;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * @param A upper case 'A'\n"
				+ "   */\n"
				+ "  public void setA(Integer A) {\n"
				+ "    this.A = A;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean equals(Object other) {\n"
				+ "    if (other == null)\n"
				+ "      return false;\n"
				+ "    if (!getClass().equals(other.getClass()))\n"
				+ "      return false;\n"
				+ "    Foo o = (Foo) other;\n"
				+ "    return Objects.equals(name, o.name)\n"
				+ "            && Objects.equals(bar, o.bar)\n"
				+ "            && Objects.equals(a, o.a)\n"
				+ "            && Objects.equals(A, o.A);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int compareTo(Foo other) {\n"
				+ "    if (other == null) {\n"
				+ "      return 1;\n"
				+ "    }\n"
				+ "    int res = 0;\n"
				+ "    res = CompareUtil.compare(this.name, other.name);\n"
				+ "    if (res != 0) {\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "    res = CompareUtil.compare(this.bar, other.bar);\n"
				+ "    if (res != 0) {\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "    res = CompareUtil.compare(this.a, other.a);\n"
				+ "    if (res != 0) {\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "    res = CompareUtil.compare(this.A, other.A);\n"
				+ "    return res;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public int hashCode() {\n"
				+ "    return Objects.hash(name, bar, a, A);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Foo deepClone() {\n"
				+ "    Foo clone = new Foo();\n"
				+ "    clone.name = this.name;\n"
				+ "    clone.bar = this.bar != null ? this.bar.deepClone() : null;\n"
				+ "    clone.a = this.a;\n"
				+ "    clone.A = this.A;\n"
				+ "    return clone;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String toString() {\n"
				+ "    return EncodingUtil.pojoToString(this);\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Builder for {@link Foo}\n"
				+ "   */\n"
				+ "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
				+ "  public static class Builder {\n"
				+ "    \n"
				+ "    private String name;\n"
				+ "    private Bar bar;\n"
				+ "    private Integer a;\n"
				+ "    private Integer A;\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>name</code> field in the builder\n"
				+ "     * @param name the name\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setName(String)\n"
				+ "     */\n"
				+ "    public Builder name(String name)  {\n"
				+ "      this.name = name;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>bar</code> field in the builder\n"
				+ "     * @param bar Message field <strong>b</strong>\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setBar(Bar)\n"
				+ "     */\n"
				+ "    public Builder bar(Bar bar)  {\n"
				+ "      this.bar = bar;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>a</code> field in the builder\n"
				+ "     * @param a lower case 'a'\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #seta(Integer)\n"
				+ "     */\n"
				+ "    public Builder a(Integer a)  {\n"
				+ "      this.a = a;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * Will set the value of <code>A</code> field in the builder\n"
				+ "     * @param A upper case 'A'\n"
				+ "     * @return Builder instance\n"
				+ "     * @see #setA(Integer)\n"
				+ "     */\n"
				+ "    public Builder A(Integer A)  {\n"
				+ "      this.A = A;\n"
				+ "      return this;\n"
				+ "    }\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * @return a new instance of Foo using the values set in this builder\n"
				+ "     */\n"
				+ "    public Foo build() {\n"
				+ "      Foo res = new Foo();\n"
				+ "      res.name = this.name;\n"
				+ "      res.bar = this.bar != null ? this.bar.deepClone() : null;\n"
				+ "      res.a = this.a;\n"
				+ "      res.A = this.A;\n"
				+ "      return res;\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
		Assert.assertEquals(4, generator.getFields().size());
	}

}
