package org.jxapi.generator.java.exchange.api;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.gen.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.gen.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.exchange.ExchangeGenUtil;
import org.jxapi.util.PlaceHolderResolver;


/**
 * Unit test for {@link ExchangeApiInterfaceGenerator}
 */
public class ExchangeApiInterfaceGeneratorTest {

  @Test
  public void testGenerateExchangeApi() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    PlaceHolderResolver docPlaceHolderResolver = 
        PlaceHolderResolver.create(ExchangeGenUtil.getDescriptionReplacements(exchangeDescriptor));
    
    ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor, docPlaceHolderResolver);
    Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
        + "\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickersResponse;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApi;\n"
        + "import org.jxapi.netutils.rest.FutureRestResponse;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "\n"
        + "/**\n"
        + " * MyTestExchange MarketData API<br>\n"
        + " * The market data API of MyTestExchange. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.ExchangeApiInterfaceGenerator\")\n"
        + "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of 'MarketData' API group.\n"
        + "   */\n"
        + "  String ID = \"MarketData\";\n"
        + "  /**\n"
        + "   * Name of <code>exchangeInfo</code> RestApi.\n"
        + "   */\n"
        + "   String EXCHANGE_INFO_REST_API = \"exchangeInfo\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>tickers</code> RestApi.\n"
        + "   */\n"
        + "   String TICKERS_REST_API = \"tickers\";\n"
        + "  /**\n"
        + "   * Name of <code>tickerStream</code> WsApi.\n"
        + "   */\n"
        + "   String TICKER_STREAM_WS_API = \"tickerStream\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Fetch market information of symbols that can be traded. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   * @param request Request parameters for fetching exchange info. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed.\n"
        + "   * @see <a href=\"https://docs.myexchange.com/api/rest/marketData/exchangeInfo\">Reference documentation</a>\n"
        + "   */\n"
        + "  FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request);\n"
        + "  \n"
        + "  /**\n"
        + "   * Fetch current tickers. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<MyTestExchangeMarketDataTickersResponse> tickers();\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to tickerStream stream.<br>\n"
        + "   * Subscribe to ticker stream. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   * \n"
        + "   * @param request Request parameters for subscribing to ticker stream. Use {@link com.foo.bar.gen.MyTestExchangeConstants#ALL_TICKERS} to subscribe to every ticker. Author: {@link com.foo.bar.gen.MyTestExchangeConstants#AUTHOR_FULL_NAME}\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeTickerStream(String)}\n"
        + "   * @see <a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">Reference documentation</a>\n"
        + "   */\n"
        + "  String subscribeTickerStream(MyTestExchangeMarketDataTickerStreamRequest request, WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from tickerStream stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeTickerStream(MyTestExchangeMarketDataTickerStreamRequest, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeTickerStream(String subscriptionId);\n"
        + "}\n"
        + "", 
        apiInterfaceGenerator.generate());
  }
  
  @Test
  public void testGenerateExchangeApiNoWsEndpoint() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoWebsocketEndpoint.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor, null);
    Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
        + "\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApi;\n"
        + "import org.jxapi.netutils.rest.FutureRestResponse;\n"
        + "\n"
        + "/**\n"
        + " * MyTestExchange MarketData API<br>\n"
        + " * The market data API of MyTestExchange, , with only 1 REST endpoint and no websocket endpoint\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.ExchangeApiInterfaceGenerator\")\n"
        + "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of 'MarketData' API group.\n"
        + "   */\n"
        + "  String ID = \"MarketData\";\n"
        + "  /**\n"
        + "   * Name of <code>exchangeInfo</code> RestApi.\n"
        + "   */\n"
        + "   String EXCHANGE_INFO_REST_API = \"exchangeInfo\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Fetch market information of symbols that can be traded\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request);\n"
        + "}\n"
        + "", 
        apiInterfaceGenerator.generate());
  }
  
  @Test
  public void testGenerateExchangeApiNoRestEndpoint() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoRestEndpoint.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor, null);
    Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
        + "\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.TickerMessage;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApi;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "\n"
        + "/**\n"
        + " * MyTestExchange MarketData API<br>\n"
        + " * The market data API of MyTestExchange\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.ExchangeApiInterfaceGenerator\")\n"
        + "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of 'MarketData' API group.\n"
        + "   */\n"
        + "  String ID = \"MarketData\";\n"
        + "  /**\n"
        + "   * Name of <code>tickerStreamStringObjectType</code> WsApi.\n"
        + "   */\n"
        + "   String TICKER_STREAM_STRING_OBJECT_TYPE_WS_API = \"tickerStreamStringObjectType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>tickerStreamStringRequestType</code> WsApi.\n"
        + "   */\n"
        + "   String TICKER_STREAM_STRING_REQUEST_TYPE_WS_API = \"tickerStreamStringRequestType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to tickerStreamStringObjectType stream.<br>\n"
        + "   * Subscribe to ticker stream\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeTickerStreamStringObjectType(String)}\n"
        + "   */\n"
        + "  String subscribeTickerStreamStringObjectType(MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest request, WebsocketListener<TickerMessage> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from tickerStreamStringObjectType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeTickerStreamStringObjectType(MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeTickerStreamStringObjectType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to tickerStreamStringRequestType stream.<br>\n"
        + "   * Subscribe to ticker stream\n"
        + "   * \n"
        + "   * @param symbol Symbol to subscribe to ticker stream of\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeTickerStreamStringRequestType(String)}\n"
        + "   */\n"
        + "  String subscribeTickerStreamStringRequestType(String symbol, WebsocketListener<TickerMessage> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from tickerStreamStringRequestType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeTickerStreamStringRequestType(String, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeTickerStreamStringRequestType(String subscriptionId);\n"
        + "}\n"
        + "", 
        apiInterfaceGenerator.generate());
  }
  
  @Test
  public void testGenerateExchangeApiSpecificResponseDataTypes() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor, null);
    Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
        + "\n"
        + "import java.math.BigDecimal;\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "\n"
        + "import com.external.pkg.ExternalObject;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataSubscribeTickerMessage;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApi;\n"
        + "import org.jxapi.netutils.rest.FutureRestResponse;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "\n"
        + "/**\n"
        + " * MyTestExchange MarketData API<br>\n"
        + " * The market data API of MyTestExchange, with different response data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.ExchangeApiInterfaceGenerator\")\n"
        + "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of 'MarketData' API group.\n"
        + "   */\n"
        + "  String ID = \"MarketData\";\n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeInt</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_INT_REST_API = \"getRestResponseDataTypeInt\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeLong</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_LONG_REST_API = \"getRestResponseDataTypeLong\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeBigDecimal</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_BIG_DECIMAL_REST_API = \"getRestResponseDataTypeBigDecimal\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeString</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_STRING_REST_API = \"getRestResponseDataTypeString\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeBoolean</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_BOOLEAN_REST_API = \"getRestResponseDataTypeBoolean\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeObject</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_OBJECT_REST_API = \"getRestResponseDataTypeObject\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeIntList</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_INT_LIST_REST_API = \"getRestResponseDataTypeIntList\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeObjectListMap</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_OBJECT_LIST_MAP_REST_API = \"getRestResponseDataTypeObjectListMap\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestEmptyResponseDataType</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_EMPTY_RESPONSE_DATA_TYPE_REST_API = \"getRestEmptyResponseDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeRawObject</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_RAW_OBJECT_REST_API = \"getRestResponseDataTypeRawObject\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestResponseDataTypeExternalObject</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_RESPONSE_DATA_TYPE_EXTERNAL_OBJECT_REST_API = \"getRestResponseDataTypeExternalObject\";\n"
        + "  /**\n"
        + "   * Name of <code>subscribeTicker</code> WsApi.\n"
        + "   */\n"
        + "   String SUBSCRIBE_TICKER_WS_API = \"subscribeTicker\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>subscribeTickertMapListStream</code> WsApi.\n"
        + "   */\n"
        + "   String SUBSCRIBE_TICKERT_MAP_LIST_STREAM_WS_API = \"subscribeTickertMapListStream\";\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using INT response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed. If successful, will provide response: A random int\n"
        + "   */\n"
        + "  FutureRestResponse<Integer> getRestResponseDataTypeInt();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using LONG response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<Long> getRestResponseDataTypeLong();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using BIGDECIMAL response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<BigDecimal> getRestResponseDataTypeBigDecimal();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using STRING response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<String> getRestResponseDataTypeString();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using BOOLEAN response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<Boolean> getRestResponseDataTypeBoolean();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using OBJECT response data type (default type, explicit here)\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObject();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using INT_LIST response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<List<Integer>> getRestResponseDataTypeIntList();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using OBJECT_LIST_MAP response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<Map<String, List<MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMap();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using empty response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<String> getRestEmptyResponseDataType();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using empty response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<Object> getRestResponseDataTypeRawObject();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using STRING_LIST response data type\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<ExternalObject> getRestResponseDataTypeExternalObject();\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to subscribeTicker stream.<br>\n"
        + "   * Subscribe to stream with OBJECT message type (default, explicit here)\n"
        + "   * \n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeSubscribeTicker(String)}\n"
        + "   */\n"
        + "  String subscribeSubscribeTicker(WebsocketListener<MyTestExchangeMarketDataSubscribeTickerMessage> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from subscribeTicker stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeSubscribeTicker(WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeSubscribeTicker(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to subscribeTickertMapListStream stream.<br>\n"
        + "   * Subscribe to stream with OBJECT_MAP_LIST message type\n"
        + "   * \n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeSubscribeTickertMapListStream(String)}\n"
        + "   */\n"
        + "  String subscribeSubscribeTickertMapListStream(WebsocketListener<List<Map<String, MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage>>> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from subscribeTickertMapListStream stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeSubscribeTickertMapListStream(WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeSubscribeTickertMapListStream(String subscriptionId);\n"
        + "}\n"
        + "", 
        apiInterfaceGenerator.generate());
  }
  
  @Test
  public void testGenerateExchangeApiSpecificRequestDataTypes() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor, null);
    Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
        + "\n"
        + "import java.math.BigDecimal;\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "\n"
        + "import com.external.pkg.ExternalObject;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MultiSymbol;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestRequestDataTypeWithBothPathAndQueryParamsRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
        + "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApi;\n"
        + "import org.jxapi.netutils.rest.FutureRestResponse;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "\n"
        + "/**\n"
        + " * MyTestExchange MarketData API<br>\n"
        + " * The market data API of MyTestExchange, with different request data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.ExchangeApiInterfaceGenerator\")\n"
        + "public interface MyTestExchangeMarketDataApi extends ExchangeApi {\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of 'MarketData' API group.\n"
        + "   */\n"
        + "  String ID = \"MarketData\";\n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeInt</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_INT_REST_API = \"postRestRequestDataTypeInt\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeLong</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_LONG_REST_API = \"postRestRequestDataTypeLong\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeBigDecimal</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_BIG_DECIMAL_REST_API = \"postRestRequestDataTypeBigDecimal\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeStringImplicit</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_STRING_IMPLICIT_REST_API = \"postRestRequestDataTypeStringImplicit\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeIntImplicitAsPathParam</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_INT_IMPLICIT_AS_PATH_PARAM_REST_API = \"postRestRequestDataTypeIntImplicitAsPathParam\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeBoolean</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_BOOLEAN_REST_API = \"postRestRequestDataTypeBoolean\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestNoParameters</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_NO_PARAMETERS_REST_API = \"postRestRequestNoParameters\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeObjectOneParameter</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_OBJECT_ONE_PARAMETER_REST_API = \"postRestRequestDataTypeObjectOneParameter\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeIntListWithDefaultValue</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_INT_LIST_WITH_DEFAULT_VALUE_REST_API = \"postRestRequestDataTypeIntListWithDefaultValue\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeObjectListMap</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_OBJECT_LIST_MAP_REST_API = \"postRestRequestDataTypeObjectListMap\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>deletetRestRequestDataTypeObjectAsBody</code> RestApi.\n"
        + "   */\n"
        + "   String DELETET_REST_REQUEST_DATA_TYPE_OBJECT_AS_BODY_REST_API = \"deletetRestRequestDataTypeObjectAsBody\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>deletetRestRequestDataTypeObjectAsQueryParams</code> RestApi.\n"
        + "   */\n"
        + "   String DELETET_REST_REQUEST_DATA_TYPE_OBJECT_AS_QUERY_PARAMS_REST_API = \"deletetRestRequestDataTypeObjectAsQueryParams\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestRequestDataTypeObjectListMap</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_REQUEST_DATA_TYPE_OBJECT_LIST_MAP_REST_API = \"getRestRequestDataTypeObjectListMap\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestRequestDataTypeEmptyObject</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_REQUEST_DATA_TYPE_EMPTY_OBJECT_REST_API = \"getRestRequestDataTypeEmptyObject\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestRequestDataTypeExternalObject</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_REQUEST_DATA_TYPE_EXTERNAL_OBJECT_REST_API = \"getRestRequestDataTypeExternalObject\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>postRestRequestDataTypeRawObject</code> RestApi.\n"
        + "   */\n"
        + "   String POST_REST_REQUEST_DATA_TYPE_RAW_OBJECT_REST_API = \"postRestRequestDataTypeRawObject\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestRequestDataTypePrimitiveWithMsgField</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_REQUEST_DATA_TYPE_PRIMITIVE_WITH_MSG_FIELD_REST_API = \"getRestRequestDataTypePrimitiveWithMsgField\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestRequestDataTypePrimitiveWithMsgFieldAsPathPAram</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_REQUEST_DATA_TYPE_PRIMITIVE_WITH_MSG_FIELD_AS_PATH_P_ARAM_REST_API = \"getRestRequestDataTypePrimitiveWithMsgFieldAsPathPAram\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>getRestRequestDataTypeWithBothPathAndQueryParams</code> RestApi.\n"
        + "   */\n"
        + "   String GET_REST_REQUEST_DATA_TYPE_WITH_BOTH_PATH_AND_QUERY_PARAMS_REST_API = \"getRestRequestDataTypeWithBothPathAndQueryParams\";\n"
        + "  /**\n"
        + "   * Name of <code>streamWithObjectRequestDataTypeZeroParameters</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_OBJECT_REQUEST_DATA_TYPE_ZERO_PARAMETERS_WS_API = \"streamWithObjectRequestDataTypeZeroParameters\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithObjectRequestDataTypeOneParameter</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_OBJECT_REQUEST_DATA_TYPE_ONE_PARAMETER_WS_API = \"streamWithObjectRequestDataTypeOneParameter\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithIntRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_INT_REQUEST_DATA_TYPE_WS_API = \"streamWithIntRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithLongRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_LONG_REQUEST_DATA_TYPE_WS_API = \"streamWithLongRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithBigDecimalRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_BIG_DECIMAL_REQUEST_DATA_TYPE_WS_API = \"streamWithBigDecimalRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithStringRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_STRING_REQUEST_DATA_TYPE_WS_API = \"streamWithStringRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithBooleanRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_BOOLEAN_REQUEST_DATA_TYPE_WS_API = \"streamWithBooleanRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithStringListRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_STRING_LIST_REQUEST_DATA_TYPE_WS_API = \"streamWithStringListRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithObjectListMapRequestDataType</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_OBJECT_LIST_MAP_REQUEST_DATA_TYPE_WS_API = \"streamWithObjectListMapRequestDataType\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithNullTopicAndNullRequest</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_NULL_TOPIC_AND_NULL_REQUEST_WS_API = \"streamWithNullTopicAndNullRequest\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>streamWithNullTopicAndPrimitiveTypeRequest</code> WsApi.\n"
        + "   */\n"
        + "   String STREAM_WITH_NULL_TOPIC_AND_PRIMITIVE_TYPE_REQUEST_WS_API = \"streamWithNullTopicAndPrimitiveTypeRequest\";\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using INT response data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeInt(Integer request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using LONG response data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeLong(Long request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using BIGDECIMAL response data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeBigDecimal(BigDecimal request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using STRING response data type\n"
        + "   * @param hello Say Hi!\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeStringImplicit(String hello);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using STRING response data type\n"
        + "   * @param id Identifier\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeIntImplicitAsPathParam(Integer id);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using BOOLEAN response data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeBoolean(Boolean request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using POST method (HTTP request expecting a body), and no parameters. One String argument should be generated to pass raw body\n"
        + "   * @param body Raw body request field.\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestNoParameters(String body);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using OBJECT request data type (default, explicit here), and one parameter\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectOneParameter(MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using INT_LIST request data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeIntListWithDefaultValue(List<Integer> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using OBJECT_LIST_MAP request data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectListMap(Map<String, List<SingleSymbol>> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST DELETE endpoint using OBJECT request data type, and request serialized as body\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> deletetRestRequestDataTypeObjectAsBody(Map<String, List<SingleSymbol>> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using OBJECT_LIST_MAP request data type\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> deletetRestRequestDataTypeObjectAsQueryParams(Map<String, List<SingleSymbol>> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using GET (hence url query params) and object list map request type, and sample value with full structure.\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> getRestRequestDataTypeObjectListMap(Map<String, List<MultiSymbol>> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using GET (hence url query params) and empty request object\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> getRestRequestDataTypeEmptyObject();\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using POST (hence request body) and request with object name representing a class with full package name, which is not to be generated\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> getRestRequestDataTypeExternalObject(ExternalObject request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using POST (hence request body) and raw <code>java.lang.Object</code> request object\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> postRestRequestDataTypeRawObject(Object request);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name\n"
        + "   * @param age request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> getRestRequestDataTypePrimitiveWithMsgField(Integer age);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name\n"
        + "   * @param age request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> getRestRequestDataTypePrimitiveWithMsgFieldAsPathPAram(Integer age);\n"
        + "  \n"
        + "  /**\n"
        + "   * A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<GenericResponse> getRestRequestDataTypeWithBothPathAndQueryParams(MyTestExchangeMarketDataGetRestRequestDataTypeWithBothPathAndQueryParamsRequest request);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithObjectRequestDataTypeZeroParameters stream.<br>\n"
        + "   * Subscribe to stream with OBJECT request type (implicit) and no parameters\n"
        + "   * \n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithObjectRequestDataTypeZeroParameters(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithObjectRequestDataTypeZeroParameters(WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithObjectRequestDataTypeZeroParameters stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithObjectRequestDataTypeZeroParameters(WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithObjectRequestDataTypeZeroParameters(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithObjectRequestDataTypeOneParameter stream.<br>\n"
        + "   * Subscribe to stream with OBJECT request type (default, explicit here) and parameter\n"
        + "   * \n"
        + "   * @param symbolObj request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithObjectRequestDataTypeOneParameter(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithObjectRequestDataTypeOneParameter(SingleSymbol symbolObj, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithObjectRequestDataTypeOneParameter stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithObjectRequestDataTypeOneParameter(SingleSymbol, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithObjectRequestDataTypeOneParameter(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithIntRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with INT request type\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithIntRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithIntRequestDataType(Integer request, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithIntRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithIntRequestDataType(Integer, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithIntRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithLongRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with LONG request type\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithLongRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithLongRequestDataType(Long request, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithLongRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithLongRequestDataType(Long, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithLongRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithBigDecimalRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with BIGDECIMAL request type\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithBigDecimalRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithBigDecimalRequestDataType(BigDecimal request, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithBigDecimalRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithBigDecimalRequestDataType(BigDecimal, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithBigDecimalRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithStringRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with STRING request type\n"
        + "   * \n"
        + "   * @param symbol Market symbol\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithStringRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithStringRequestDataType(String symbol, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithStringRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithStringRequestDataType(String, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithStringRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithBooleanRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with BOOLEAN request type\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithBooleanRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithBooleanRequestDataType(Boolean request, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithBooleanRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithBooleanRequestDataType(Boolean, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithBooleanRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithStringListRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with STRING_LIST request type\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithStringListRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithStringListRequestDataType(List<String> request, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithStringListRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithStringListRequestDataType(List<String>, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithStringListRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithObjectListMapRequestDataType stream.<br>\n"
        + "   * Subscribe to stream with OBJECT_LIST_MAP request type. The objectName field is set to a name already defined in other API definition.\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithObjectListMapRequestDataType(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithObjectListMapRequestDataType(Map<String, List<MultiSymbol>> request, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithObjectListMapRequestDataType stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithObjectListMapRequestDataType(Map<String, List<MultiSymbol>>, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithObjectListMapRequestDataType(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithNullTopicAndNullRequest stream.<br>\n"
        + "   * Subscribe to stream with null topic, request and message topic matcher. Remark: No topic matcher situation is realistic only when there is no websocket stream multiplexing, e.g. no 'topic' but a single endpoint handling all messages coming on websocket.\n"
        + "   * \n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithNullTopicAndNullRequest(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithNullTopicAndNullRequest(WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithNullTopicAndNullRequest stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithNullTopicAndNullRequest(WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithNullTopicAndNullRequest(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to streamWithNullTopicAndPrimitiveTypeRequest stream.<br>\n"
        + "   * Subscribe to stream with null topic, and primitive type request, without message topic matcher. The request is used in message topic matcher field template, so generated method implementation will perform subsitution with method request argument\n"
        + "   * \n"
        + "   * @param myTopic request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeStreamWithNullTopicAndPrimitiveTypeRequest(String)}\n"
        + "   */\n"
        + "  String subscribeStreamWithNullTopicAndPrimitiveTypeRequest(String myTopic, WebsocketListener<Ticker> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from streamWithNullTopicAndPrimitiveTypeRequest stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeStreamWithNullTopicAndPrimitiveTypeRequest(String, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeStreamWithNullTopicAndPrimitiveTypeRequest(String subscriptionId);\n"
        + "}\n"
        + "", 
        apiInterfaceGenerator.generate());
  }
  
  @Test
  public void testGenerateExchangeApiConflictingPropertyNames() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromYaml(Paths.get(".", "src", "test", "resources", "exchangeWithEndpointWithConflictingPropertyNames.yaml"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor, null);
    Assert.assertEquals("package org.jxapi.exchanges.conflict.gen.v1;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApi;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictRequest;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictV1MyWsEndpointMessage;\n"
        + "import org.jxapi.netutils.rest.FutureRestResponse;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "\n"
        + "/**\n"
        + " * conflict v1 API<br>\n"
        + " * Version 1 of the Employee API\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.ExchangeApiInterfaceGenerator\")\n"
        + "public interface ConflictV1Api extends ExchangeApi {\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of 'v1' API group.\n"
        + "   */\n"
        + "  String ID = \"v1\";\n"
        + "  /**\n"
        + "   * Name of <code>myRestEndpoint</code> RestApi.\n"
        + "   */\n"
        + "   String MY_REST_ENDPOINT_REST_API = \"myRestEndpoint\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>a</code> RestApi.\n"
        + "   */\n"
        + "   String A_REST_API = \"a\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>A</code> RestApi.\n"
        + "   */\n"
        + "   String A_REST_API_ = \"A\";\n"
        + "  /**\n"
        + "   * Name of <code>myWsEndpoint</code> WsApi.\n"
        + "   */\n"
        + "   String MY_WS_ENDPOINT_WS_API = \"myWsEndpoint\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>a</code> WsApi.\n"
        + "   */\n"
        + "   String A_WS_API = \"a\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Name of <code>A</code> WsApi.\n"
        + "   */\n"
        + "   String A_WS_API_ = \"A\";\n"
        + "  \n"
        + "  /**\n"
        + "   * Get employee details by ID\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed\n"
        + "   */\n"
        + "  FutureRestResponse<String> myRestEndpoint(ConflictRequest request);\n"
        + "  \n"
        + "  /**\n"
        + "   * Rest endpoint 'a' with default value for request\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed. If successful, will provide response: Response for endpoint 'a'\n"
        + "   */\n"
        + "  FutureRestResponse<String> a(Map<String, Long> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * Rest endpoint 'A' with default value for request\n"
        + "   * @param request request\n"
        + "   * @return A {@link FutureRestResponse} that will complete when request submitted asynchronously has been processed. If successful, will provide response: Response for endpoint 'A'\n"
        + "   */\n"
        + "  FutureRestResponse<String> A(List<String> request);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to myWsEndpoint stream.<br>\n"
        + "   * Employee updates websocket\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeMyWsEndpoint(String)}\n"
        + "   * @see <a href=\"https://www.example.com/docs/employee/updates\">Reference documentation</a>\n"
        + "   */\n"
        + "  String subscribeMyWsEndpoint(ConflictRequest request, WebsocketListener<ConflictV1MyWsEndpointMessage> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from myWsEndpoint stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeMyWsEndpoint(ConflictRequest, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeMyWsEndpoint(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to a stream.<br>\n"
        + "   * Websocket endpoint 'a' default value for request\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribea(String)}\n"
        + "   */\n"
        + "  String subscribea(Integer request, WebsocketListener<String> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from a stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribea(Integer, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribea(String subscriptionId);\n"
        + "  \n"
        + "  /**\n"
        + "   * Subscribe to A stream.<br>\n"
        + "   * Websocket endpoint 'A' default value for request\n"
        + "   * \n"
        + "   * @param request request\n"
        + "   * @param listener listener that will receive incoming messages\n"
        + "   * @return client subscriptionId to use for unsubscription using {@link #unsubscribeA(String)}\n"
        + "   */\n"
        + "  String subscribeA(String request, WebsocketListener<String> listener);\n"
        + "  \n"
        + "  /**\n"
        + "   * Unsubscribe from A stream.\n"
        + "   * \n"
        + "   * @param subscriptionId client subscription ID\n"
        + "   * @return <code>true</code> if given <code>subscriptionId</code> was found.\n"
        + "   * @see #subscribeA(String, WebsocketListener)\n"
        + "   */\n"
        + "  boolean unsubscribeA(String subscriptionId);\n"
        + "}\n"
        + "", apiInterfaceGenerator.generate());
  }
}
