package com.scz.jxapi.generator.md.exchange;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;

import com.scz.jxapi.exchange.descriptor.ExchangeApiDescriptor;
import com.scz.jxapi.exchange.descriptor.ExchangeDescriptor;
import com.scz.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import com.scz.jxapi.generator.java.JavaCodeGenerationUtil;
import com.scz.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;

/**
 * Unit test for {@link ExchangeReadmeMdGenerator}
 */
public class ExchangeReameMdGeneratorTest {
	
	private Path srcFolder;
	
	@After
	public void tearDown() throws IOException {
		if (srcFolder != null) {
			JavaCodeGenerationUtil.deletePath(srcFolder);
			srcFolder = null;
		}
	}

	@Test
	public void testGenerateExchangeReadmeFile() throws IOException {
		srcFolder = ClassesGeneratorTestUtil.generateTmpDir();
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java").writeJavaFile(srcFolder);
		File expected = srcFolder.resolve("MyTestExchange_README.md").toFile();
		Assert.assertTrue("File " + expected.getAbsolutePath() + " does not exists", expected.exists());
	}
	
	@Test
	public void testGenerateExchangeReadme() throws IOException {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		String actual = new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java").generate();
		Assert.assertEquals("# MyTestExchange API Java wrapper\n"
				+ "\n"
				+ "A sample Exchange descriptor file\n"
				+ "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
				+ "### Quick start\n"
				+ "\n"
				+ "This wrapper offers Java interfaces for using MyTestExchange API\n"
				+ "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
				+ "``` java\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "\n"
				+ "public void call() {\n"
				+ "  Properties properties = new Properties();\n"
				+ "  // Set relevant configuration properties (see documentation) in 'props'\n"
				+ "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
				+ "  // Access API groups and their endpoints through 'exchange' methods.\n"
				+ "}\n"
				+ "```\n"
				+ "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataExchangeInfoDemo.java\">MyTestExchangeMarketDataExchangeInfoDemo</a> class for full usage example\n"
				+ "\n"
				+ "### Properties\n"
				+ "\n"
				+ "<table>\n"
				+ "  <caption>properties</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Name</th>\n"
				+ "    <th>Type</th>\n"
				+ "    <th>description</th>\n"
				+ "    <th>Default value</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiKey</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API key</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiSecret</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API secret</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "### Constants\n"
				+ "\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
				+ "\n"
				+ "## API Groups\n"
				+ "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
				+ "\n"
				+ "### MarketData\n"
				+ "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
				+ "\n"
				+ "The market data API of MyTestExchange\n"
				+ "\n"
				+ "#### REST endpoints\n\n"
				+ "<table>\n"
				+ "  <caption>MyTestExchange MarketData REST endpoints</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Endpoint</th>\n"
				+ "    <th>Description</th>\n"
				+ "    <th>API Reference</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)\">exchangeInfo</a></td>\n"
				+ "    <td>Fetch market information of symbols that can be traded</td>\n"
				+ "    <td><a href=\"https://docs.myexchange.com/api/rest/marketData/exchangeInfo\">link</a></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#tickers(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickersRequest)\">tickers</a></td>\n"
				+ "    <td>Fetch current tickers</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "#### Websocket endpoints\n\n"
				+ "<table>\n"
				+ "  <caption>MyTestExchange MarketData websocket endpoints</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Subscription method</th>\n"
				+ "    <th>Description</th>\n"
				+ "    <th>API Reference</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest)\">subscribeTickerStream</a></td>\n"
				+ "    <td>Subscribe to ticker stream</td>\n"
				+ "    <td><a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">link</a></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataConstants.html\">MyTestExchangeMarketDataConstants</a>\n"
				+ "",
				actual);
	}
	

	@Test
	public void testGenerateExchangeReadme_AllRequestDataTypes() throws IOException {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		String actual = new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java").generate();
		Assert.assertEquals("# MyTestExchange API Java wrapper\n"
				+ "\n"
				+ "A sample Exchange descriptor file\n"
				+ "### Quick start\n"
				+ "\n"
				+ "This wrapper offers Java interfaces for using MyTestExchange API\n"
				+ "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
				+ "``` java\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "\n"
				+ "public void call() {\n"
				+ "  Properties properties = new Properties();\n"
				+ "  // Set relevant configuration properties (see documentation) in 'props'\n"
				+ "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
				+ "  // Access API groups and their endpoints through 'exchange' methods.\n"
				+ "}\n"
				+ "```\n"
				+ "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo.java\">MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo</a> class for full usage example\n"
				+ "\n"
				+ "## API Groups\n"
				+ "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
				+ "\n"
				+ "### MarketData\n"
				+ "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
				+ "\n"
				+ "The market data API of MyTestExchange, with different request data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
				+ "\n"
				+ "#### REST endpoints\n\n"
				+ "<table>\n"
				+ "  <caption>MyTestExchange MarketData REST endpoints</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Endpoint</th>\n"
				+ "    <th>Description</th>\n"
				+ "    <th>API Reference</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeInt(java.lang.Integer)\">postRestRequestDataTypeInt</a></td>\n"
				+ "    <td>A sample REST endpoint using INT response data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeLong(java.lang.Long)\">postRestRequestDataTypeLong</a></td>\n"
				+ "    <td>A sample REST endpoint using LONG response data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeBigDecimal(java.math.BigDecimal)\">postRestRequestDataTypeBigDecimal</a></td>\n"
				+ "    <td>A sample REST endpoint using BIGDECIMAL response data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeString(java.lang.String)\">postRestRequestDataTypeString</a></td>\n"
				+ "    <td>A sample REST endpoint using STRING response data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeBoolean(java.lang.Boolean)\">postRestRequestDataTypeBoolean</a></td>\n"
				+ "    <td>A sample REST endpoint using BOOLEAN response data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeObjectNoParameters(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeObjectNoParametersRequest)\">postRestRequestDataTypeObjectNoParameters</a></td>\n"
				+ "    <td>A sample REST endpoint using OBJECT request data type (implicit), and no parameters</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeObjectOneParameter(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest)\">postRestRequestDataTypeObjectOneParameter</a></td>\n"
				+ "    <td>A sample REST endpoint using OBJECT request data type (default, explicit here), and one parameter</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeIntList(java.util.List)\">postRestRequestDataTypeIntList</a></td>\n"
				+ "    <td>A sample REST endpoint using INT_LIST request data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeObjectListMap(java.util.Map)\">postRestRequestDataTypeObjectListMap</a></td>\n"
				+ "    <td>A sample REST endpoint using OBJECT_LIST_MAP request data type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypeObjectListMap(java.util.Map)\">getRestRequestDataTypeObjectListMap</a></td>\n"
				+ "    <td>A sample REST endpoint using GET (hence url query params) and object list map request type.</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypeEmptyObject(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestRequestDataTypeEmptyObjectRequest)\">getRestRequestDataTypeEmptyObject</a></td>\n"
				+ "    <td>A sample REST endpoint using GET (hence url query params) and empty request object</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#getRestRequestDataTypePrimitiveWithMsgField(java.lang.Integer)\">getRestRequestDataTypePrimitiveWithMsgField</a></td>\n"
				+ "    <td>A sample REST endpoint using GET (hence url query params) primitive request type, with 'msgField' property defined. That msgField value should be used as query param argument name</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#postRestRequestDataTypeNoParamsButUrlParameters(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeNoParamsButUrlParametersRequest)\">postRestRequestDataTypeNoParamsButUrlParameters</a></td>\n"
				+ "    <td>A sample REST endpoint using POST method (hence no url parameters by default), no arguments, but url parameters through 'urlParameters' property</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "#### Websocket endpoints\n\n"
				+ "<table>\n"
				+ "  <caption>MyTestExchange MarketData websocket endpoints</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Subscription method</th>\n"
				+ "    <th>Description</th>\n"
				+ "    <th>API Reference</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithObjectRequestDataTypeZeroParameters(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersRequest)\">subscribeStreamWithObjectRequestDataTypeZeroParameters</a></td>\n"
				+ "    <td>Subscribe to stream with OBJECT request type (implicit) and no parameters</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithObjectRequestDataTypeOneParameter(com.foo.bar.gen.marketdata.pojo.SingleSymbol)\">subscribeStreamWithObjectRequestDataTypeOneParameter</a></td>\n"
				+ "    <td>Subscribe to stream with OBJECT request type (default, explicit here) and parameter</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithIntRequestDataType(java.lang.Integer)\">subscribeStreamWithIntRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with INT request type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithLongRequestDataType(java.lang.Long)\">subscribeStreamWithLongRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with LONG request type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithBigDecimalRequestDataType(java.math.BigDecimal)\">subscribeStreamWithBigDecimalRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with BIGDECIMAL request type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithStringRequestDataType(java.lang.String)\">subscribeStreamWithStringRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with STRING request type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithBooleanRequestDataType(java.lang.Boolean)\">subscribeStreamWithBooleanRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with BOOLEAN request type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithStringListRequestDataType(java.util.List)\">subscribeStreamWithStringListRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with STRING_LIST request type</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithObjectListMapRequestDataType(java.util.Map)\">subscribeStreamWithObjectListMapRequestDataType</a></td>\n"
				+ "    <td>Subscribe to stream with OBJECT_LIST_MAP request type. The objectName field is set to a name already defined in other API definition.</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithNullTopicAndNullRequest()\">subscribeStreamWithNullTopicAndNullRequest</a></td>\n"
				+ "    <td>Subscribe to stream with null topic, request and message topic matcher. Remark: No topic matcher situation is realistic only when there is no websocket stream multiplexing, e.g. no 'topic' but a single endpoint handling all messages coming on websocket.</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeStreamWithNullTopicAndPrimitiveTypeRequest(java.lang.String)\">subscribeStreamWithNullTopicAndPrimitiveTypeRequest</a></td>\n"
				+ "    <td>Subscribe to stream with null topic, and primitive type request, without message topic matcher. The request is used in message topic matcher field template, so generated method implementation will perform subsitution with method request argument</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "",
				actual);
	}
	
	@Test
	public void testGenerateExchangeReadme_NoExchangeConstants_ApiGroupWithNoWebsocketEndpoints() throws IOException {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		exchange.setConstants(null);
		exchange.getApis().get(0).setWebsocketEndpoints(null);
		String actual = new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master").generate();
		Assert.assertEquals("# MyTestExchange API Java wrapper\n"
				+ "\n"
				+ "A sample Exchange descriptor file\n"
				+ "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
				+ "### Quick start\n"
				+ "\n"
				+ "This wrapper offers Java interfaces for using MyTestExchange API\n"
				+ "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
				+ "``` java\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "\n"
				+ "public void call() {\n"
				+ "  Properties properties = new Properties();\n"
				+ "  // Set relevant configuration properties (see documentation) in 'props'\n"
				+ "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
				+ "  // Access API groups and their endpoints through 'exchange' methods.\n"
				+ "}\n"
				+ "```\n"
				+ "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataExchangeInfoDemo.java\">MyTestExchangeMarketDataExchangeInfoDemo</a> class for full usage example\n"
				+ "\n"
				+ "### Properties\n"
				+ "\n"
				+ "<table>\n"
				+ "  <caption>properties</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Name</th>\n"
				+ "    <th>Type</th>\n"
				+ "    <th>description</th>\n"
				+ "    <th>Default value</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiKey</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API key</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiSecret</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API secret</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "## API Groups\n"
				+ "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
				+ "\n"
				+ "### MarketData\n"
				+ "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
				+ "\n"
				+ "The market data API of MyTestExchange\n"
				+ "\n"
				+ "#### REST endpoints\n\n"
				+ "<table>\n"
				+ "  <caption>MyTestExchange MarketData REST endpoints</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Endpoint</th>\n"
				+ "    <th>Description</th>\n"
				+ "    <th>API Reference</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)\">exchangeInfo</a></td>\n"
				+ "    <td>Fetch market information of symbols that can be traded</td>\n"
				+ "    <td><a href=\"https://docs.myexchange.com/api/rest/marketData/exchangeInfo\">link</a></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#tickers(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickersRequest)\">tickers</a></td>\n"
				+ "    <td>Fetch current tickers</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataConstants.html\">MyTestExchangeMarketDataConstants</a>\n"
				+ "",
				actual);
	}
	
	@Test
	public void testGenerateExchangeReadme_ApiGroupWithNoRestEndpointsAndNoConstants() throws IOException {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		api.setConstants(null);
		api.setRestEndpoints(null);
		String actual = new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java").generate();
		Assert.assertEquals("# MyTestExchange API Java wrapper\n"
				+ "\n"
				+ "A sample Exchange descriptor file\n"
				+ "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
				+ "### Quick start\n"
				+ "\n"
				+ "This wrapper offers Java interfaces for using MyTestExchange API\n"
				+ "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
				+ "``` java\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "\n"
				+ "public void call() {\n"
				+ "  Properties properties = new Properties();\n"
				+ "  // Set relevant configuration properties (see documentation) in 'props'\n"
				+ "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
				+ "  // Access API groups and their endpoints through 'exchange' methods.\n"
				+ "}\n"
				+ "```\n"
				+ "You may have a look at <a href=\"https://myrepo.com/myproject/master/src/main/java/src/test/java/com/foo/bar/gen/marketdata/demo/MyTestExchangeMarketDataTickerStreamDemo.java\">MyTestExchangeMarketDataTickerStreamDemo</a> class for full usage example\n"
				+ "\n"
				+ "### Properties\n"
				+ "\n"
				+ "<table>\n"
				+ "  <caption>properties</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Name</th>\n"
				+ "    <th>Type</th>\n"
				+ "    <th>description</th>\n"
				+ "    <th>Default value</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiKey</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API key</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiSecret</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API secret</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "### Constants\n"
				+ "\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
				+ "\n"
				+ "## API Groups\n"
				+ "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
				+ "\n"
				+ "### MarketData\n"
				+ "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
				+ "\n"
				+ "The market data API of MyTestExchange\n"
				+ "\n"
				+ "#### Websocket endpoints\n\n"
				+ "<table>\n"
				+ "  <caption>MyTestExchange MarketData websocket endpoints</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Subscription method</th>\n"
				+ "    <th>Description</th>\n"
				+ "    <th>API Reference</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td><a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest)\">subscribeTickerStream</a></td>\n"
				+ "    <td>Subscribe to ticker stream</td>\n"
				+ "    <td><a href=\"https://docs.myexchange.com/api/ws/marketData/tickerStream\">link</a></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "",
				actual);
	}
	
	@Test
	public void testGenerateExchangeReadme_NoApiGroup() throws IOException {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		exchange.setApis(null);
		String actual = new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java").generate();
		Assert.assertEquals("# MyTestExchange API Java wrapper\n"
				+ "\n"
				+ "A sample Exchange descriptor file\n"
				+ "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
				+ "### Quick start\n"
				+ "\n"
				+ "This wrapper offers Java interfaces for using MyTestExchange API\n"
				+ "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
				+ "``` java\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "\n"
				+ "public void call() {\n"
				+ "  Properties properties = new Properties();\n"
				+ "  // Set relevant configuration properties (see documentation) in 'props'\n"
				+ "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
				+ "  // Access API groups and their endpoints through 'exchange' methods.\n"
				+ "}\n"
				+ "```\n"
				+ "\n"
				+ "### Properties\n"
				+ "\n"
				+ "<table>\n"
				+ "  <caption>properties</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Name</th>\n"
				+ "    <th>Type</th>\n"
				+ "    <th>description</th>\n"
				+ "    <th>Default value</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiKey</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API key</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiSecret</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API secret</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "### Constants\n"
				+ "\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
				+ "",
				actual);
	}
	
	@Test
	public void testGenerateExchangeReadme_ApiGroupWithNoDescriptionNoRestNoWsEndpoint() throws IOException {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		api.setRestEndpoints(null);
		api.setWebsocketEndpoints(null);
		api.setDescription(null);
		String actual = new ExchangeReadmeMdGenerator(exchange, "https://javadoc.io/myproject/", "https://myrepo.com/myproject/master/src/main/java").generate();
		Assert.assertEquals("# MyTestExchange API Java wrapper\n"
				+ "\n"
				+ "A sample Exchange descriptor file\n"
				+ "See <a href=\"https://docs.myexchange.com/api\">reference documentation</a>\n"
				+ "### Quick start\n"
				+ "\n"
				+ "This wrapper offers Java interfaces for using MyTestExchange API\n"
				+ "Add maven dependency to your project, then you can use the wrapper by instantiating <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> in your code:\n"
				+ "``` java\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "\n"
				+ "public void call() {\n"
				+ "  Properties properties = new Properties();\n"
				+ "  // Set relevant configuration properties (see documentation) in 'props'\n"
				+ "  MyTestExchangeExchange   exchange = new MyTestExchangeExchangeImpl(properties);\n"
				+ "  // Access API groups and their endpoints through 'exchange' methods.\n"
				+ "}\n"
				+ "```\n"
				+ "\n"
				+ "### Properties\n"
				+ "\n"
				+ "<table>\n"
				+ "  <caption>properties</caption>\n"
				+ "  <tr>\n"
				+ "    <th>Name</th>\n"
				+ "    <th>Type</th>\n"
				+ "    <th>description</th>\n"
				+ "    <th>Default value</th>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiKey</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API key</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "  <tr>\n"
				+ "    <td>apiSecret</td>\n"
				+ "    <td>STRING</td>\n"
				+ "    <td>API secret</td>\n"
				+ "    <td></td>\n"
				+ "  </tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "### Constants\n"
				+ "\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeConstants.html\">MyTestExchangeConstants</a>\n"
				+ "\n"
				+ "## API Groups\n"
				+ "APIs are available using the following interfaces accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange.html\">MyTestExchangeExchange</a> interface\n"
				+ "\n"
				+ "### MarketData\n"
				+ "Methods exposed in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataApi.html\">MyTestExchangeMarketDataApi</a> accessible from <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/MyTestExchangeExchange#getMyTestExchangeMarketDataApi().html\">MyTestExchangeExchange#getMyTestExchangeMarketDataApi()</a>\n"
				+ "\n"
				+ "Some useful constants are defined in <a href=\"https://javadoc.io/myproject/com/foo/bar/gen/marketdata/MyTestExchangeMarketDataConstants.html\">MyTestExchangeMarketDataConstants</a>\n"
				+ "",
				actual);
	}
}
