package org.jxapi.generator.java.exchange.api.demo;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.gen.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.gen.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.gen.RestEndpointDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;

/**
 * Unit test for {@link RestEndpointDemoGenerator} 
 */
public class RestEndpointDemoGeneratorTest {

  @Test
  public void testGenerateRestEndpointDemo() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0); 
    RestEndpointDescriptor restEndpointDescriptor = ClassesGeneratorTestUtil.findRestEndpointByName("exchangeInfo", api);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Optional;\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MyTestExchangeMarketDataExchangeInfoRequestDeserializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.StringJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataExchangeInfoDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataExchangeInfoDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type MyTestExchangeMarketDataExchangeInfoRequest using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static MyTestExchangeMarketDataExchangeInfoRequest createRequest(Properties properties) {\n"
        + "    return Optional\n"
        + "      .ofNullable(new MyTestExchangeMarketDataExchangeInfoRequestDeserializer().deserialize(MyTestExchangeDemoProperties.MarketData.Rest.ExchangeInfo.getRequest(properties)))\n"
        + "      .orElse(MyTestExchangeMarketDataExchangeInfoRequest.builder()  \n"
        + "        .symbols(new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance()).deserialize(MyTestExchangeDemoProperties.MarketData.Rest.ExchangeInfo.Request.getSymbols(properties)))\n"
        + "        .apiKey(MyTestExchangeDemoProperties.MarketData.Rest.ExchangeInfo.Request.getApiKey(properties))\n"
        + "        .author(MyTestExchangeDemoProperties.MarketData.Rest.ExchangeInfo.Request.getAuthor(properties))\n"
        + "        .page(MyTestExchangeDemoProperties.MarketData.Rest.ExchangeInfo.Request.getPage(properties))\n"
        + "        .build());\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<MyTestExchangeMarketDataExchangeInfoResponse> execute(MyTestExchangeMarketDataExchangeInfoRequest request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.exchangeInfo() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.exchangeInfo(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createRequest(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        new RestEndpointDemoGenerator(exchange, api, restEndpointDescriptor, EndpointDemoGenUtil.collectDemoConfigProperties(exchange)).generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_RequesTypePrimitiveInt() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeInt", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeInt(java.lang.Integer)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type Integer using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static Integer createRequest(Properties properties) {\n"
        + "    return MyTestExchangeDemoProperties.MarketData.Rest.PostRestRequestDataTypeInt.getRequest(properties);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeInt(java.lang.Integer)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<GenericResponse> execute(Integer request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeInt() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.postRestRequestDataTypeInt(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeInt(java.lang.Integer)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createRequest(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_RequesTypePrimitiveStringWithNamedArg() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeStringImplicit", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeStringImplicit(java.lang.String)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataPostRestRequestDataTypeStringImplicitDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeStringImplicitDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the hello field of type String using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static String createHello(Properties properties) {\n"
        + "    return MyTestExchangeDemoProperties.MarketData.Rest.PostRestRequestDataTypeStringImplicit.getHello(properties);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeStringImplicit(java.lang.String)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<GenericResponse> execute(String request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeStringImplicit() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.postRestRequestDataTypeStringImplicit(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeStringImplicit(java.lang.String)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createHello(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
      generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_NoArgEndpoint() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestNoParameters", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestNoParameters(java.lang.String)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataPostRestRequestNoParametersDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestNoParametersDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the body field of type String using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static String createBody(Properties properties) {\n"
        + "    return MyTestExchangeDemoProperties.MarketData.Rest.PostRestRequestNoParameters.getBody(properties);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestNoParameters(java.lang.String)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<GenericResponse> execute(String request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestNoParameters() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.postRestRequestNoParameters(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestNoParameters(java.lang.String)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createBody(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_RequestTypeObjectListMapWithReferencedObject() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeObjectListMap", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.SingleSymbolDeserializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.MapJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectListMap(java.util.Map)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataPostRestRequestDataTypeObjectListMapDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeObjectListMapDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type Map<String, List<SingleSymbol>> using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static Map<String, List<SingleSymbol>> createRequest(Properties properties) {\n"
        + "    return new MapJsonFieldDeserializer<>(new ListJsonFieldDeserializer<>(new SingleSymbolDeserializer())).deserialize(MyTestExchangeDemoProperties.MarketData.Rest.PostRestRequestDataTypeObjectListMap.getRequest(properties));\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectListMap(java.util.Map)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<GenericResponse> execute(Map<String, List<SingleSymbol>> request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeObjectListMap() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.postRestRequestDataTypeObjectListMap(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectListMap(java.util.Map)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createRequest(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_RequestTypeObjectListMapWithExplicitSampleValue() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("getRestRequestDataTypeObjectListMap", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MultiSymbol;\n"
        + "import com.foo.bar.gen.marketdata.pojo.deserializers.MultiSymbolDeserializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.MapJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#getRestRequestDataTypeObjectListMap(java.util.Map)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataGetRestRequestDataTypeObjectListMapDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataGetRestRequestDataTypeObjectListMapDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type Map<String, List<MultiSymbol>> using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static Map<String, List<MultiSymbol>> createRequest(Properties properties) {\n"
        + "    return new MapJsonFieldDeserializer<>(new ListJsonFieldDeserializer<>(new MultiSymbolDeserializer())).deserialize(MyTestExchangeDemoProperties.MarketData.Rest.GetRestRequestDataTypeObjectListMap.getRequest(properties));\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#getRestRequestDataTypeObjectListMap(java.util.Map)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<GenericResponse> execute(Map<String, List<MultiSymbol>> request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.getRestRequestDataTypeObjectListMap() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.getRestRequestDataTypeObjectListMap(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#getRestRequestDataTypeObjectListMap(java.util.Map)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createRequest(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_RequestTypeIntList() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeIntListWithDefaultValue", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.deserialization.json.field.IntegerJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeIntListWithDefaultValue(java.util.List)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataPostRestRequestDataTypeIntListWithDefaultValueDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeIntListWithDefaultValueDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type List<Integer> using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static List<Integer> createRequest(Properties properties) {\n"
        + "    return new ListJsonFieldDeserializer<>(IntegerJsonFieldDeserializer.getInstance()).deserialize(MyTestExchangeDemoProperties.MarketData.Rest.PostRestRequestDataTypeIntListWithDefaultValue.getRequest(properties));\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeIntListWithDefaultValue(java.util.List)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<GenericResponse> execute(List<Integer> request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeIntListWithDefaultValue() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.postRestRequestDataTypeIntListWithDefaultValue(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeIntListWithDefaultValue(java.util.List)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(createRequest(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_EmptyResponseDataType() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("getRestEmptyResponseDataType", api);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#getRestEmptyResponseDataType()})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataGetRestEmptyResponseDataTypeDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataGetRestEmptyResponseDataTypeDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link MyTestExchangeMarketDataApi#getRestEmptyResponseDataType()}and waits for response.\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<String> execute(Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMarketDataApi();\n"
        + "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.getRestEmptyResponseDataType() API\");\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.getRestEmptyResponseDataType());\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#getRestEmptyResponseDataType()}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      execute(properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  @Test
  public void testGenerateRestEndpointDemo_ConflictingParameterNames() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromYaml(Paths.get(".", "src", "test", "resources", "exchangeWithEndpointWithConflictingPropertyNames.yaml"));
    ExchangeApiDescriptor api = exchange.getApis().get(0);
    RestEndpointDescriptor restEndpoint = api.getRestEndpoints().get(0);
    RestEndpointDemoGenerator generator = createGenerator(exchange, api, restEndpoint);
    Assert.assertEquals("package org.jxapi.exchanges.conflict.gen.v1.demo;\n"
        + "\n"
        + "import java.util.Optional;\n"
        + "import java.util.Properties;\n"
        + "import java.util.concurrent.ExecutionException;\n"
        + "\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeObserver;\n"
        + "import org.jxapi.exchanges.conflict.gen.ConflictDemoProperties;\n"
        + "import org.jxapi.exchanges.conflict.gen.ConflictExchange;\n"
        + "import org.jxapi.exchanges.conflict.gen.ConflictExchangeImpl;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.ConflictV1Api;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictRequest;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictRequestP1_;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.pojo.deserializers.ConflictRequestDeserializer;\n"
        + "import org.jxapi.exchanges.conflict.gen.v1.pojo.deserializers.ConflictRequestP1_Deserializer;\n"
        + "import org.jxapi.netutils.rest.RestResponse;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link ConflictV1Api#myRestEndpoint(org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictRequest)})}<br>\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
        + "public class ConflictV1MyRestEndpointDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(ConflictV1MyRestEndpointDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type ConflictRequest using sample value(s) defined in demo configuration properties.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static ConflictRequest createRequest(Properties properties) {\n"
        + "    return Optional\n"
        + "      .ofNullable(new ConflictRequestDeserializer().deserialize(ConflictDemoProperties.V1.Rest.MyRestEndpoint.getRequest(properties)))\n"
        + "      .orElse(ConflictRequest.builder()  \n"
        + "        .p1(ConflictDemoProperties.V1.Rest.MyRestEndpoint.Request.getp1(properties))\n"
        + "        .P1(ConflictDemoProperties.V1.Rest.MyRestEndpoint.Request.getP1(properties))\n"
        + "        .p1_(ConflictDemoProperties.V1.Rest.MyRestEndpoint.Request.getp1_(properties))\n"
        + "        .P1_(Optional\n"
        + "          .ofNullable(new ConflictRequestP1_Deserializer().deserialize(ConflictDemoProperties.V1.Rest.MyRestEndpoint.Request.getP1_(properties)))\n"
        + "          .orElse(ConflictRequestP1_.builder()  \n"
        + "            .subParam(ConflictDemoProperties.V1.Rest.MyRestEndpoint.Request.P1____.getSubParam(properties))\n"
        + "            .build()))\n"
        + "        .build());\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Submits a call to {@link ConflictV1Api#myRestEndpoint(org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictRequest)}and waits for response.\n"
        + "   * @param request     The request to submit\n"
        + "   * @param configProperties  The configuration properties to instantiate exchange with\n"
        + "   * @param observer API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
        + "   * @return Response data resulting from this API call\n"
        + "   * @throws InterruptedException eventually thrown waiting for response\n"
        + "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
        + "   */\n"
        + "  public static RestResponse<String> execute(ConflictRequest request, Properties configProperties, ExchangeObserver observer) throws InterruptedException, ExecutionException {\n"
        + "    ConflictExchange exchange = new ConflictExchangeImpl(\"test-\" + ConflictExchange.ID, configProperties);\n"
        + "    ConflictV1Api api = exchange.getV1Api();\n"
        + "    log.info(\"Calling org.jxapi.exchanges.conflict.gen.v1.ConflictV1Api.myRestEndpoint() API with request:{}\", request);\n"
        + "    if (observer != null) {\n"
        + "      exchange.subscribeObserver(observer);\n"
        + "    }\n"
        + "    try {\n"
        + "      return DemoUtil.checkResponse(api.myRestEndpoint(request));\n"
        + "    }\n"
        + "    finally {\n"
        + "      if (observer != null) {\n"
        + "        exchange.unsubscribeObserver(observer);\n"
        + "      }\n"
        + "      exchange.dispose();\n"
        + "    }\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs REST endpoint demo snippet calling {@link ConflictV1Api#myRestEndpoint(org.jxapi.exchanges.conflict.gen.v1.pojo.ConflictRequest)}\n"
        + "   * @param args no argument expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(ConflictExchange.ID);\n"
        + "      execute(createRequest(properties),\n"
        + "              properties,\n"
        + "              DemoUtil::logRestApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }
  
  private RestEndpointDemoGenerator createGenerator(
      ExchangeDescriptor exchange, 
      ExchangeApiDescriptor api,
      RestEndpointDescriptor restEndpoint) {
    return new RestEndpointDemoGenerator(exchange, api, restEndpoint, EndpointDemoGenUtil.collectDemoConfigProperties(exchange));
  }
}
