package org.jxapi.generator.java.exchange.api.demo;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.RestEndpointDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;

/**
 * Unit test for {@link RestEndpointDemoGenerator} 
 */
public class RestEndpointDemoGeneratorTest {

	@Test
	public void testGenerateRestEndpointDemo() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0); 
		RestEndpointDescriptor restEndpointDescriptor = ClassesGeneratorTestUtil.findRestEndpointByName("exchangeInfo", api);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
				+ "import org.jxapi.netutils.deserialization.json.field.StringJsonFieldDeserializer;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataExchangeInfoDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataExchangeInfoDemo.class);\n"
				+ "  \n"
				+ "  public static MyTestExchangeMarketDataExchangeInfoRequest createRequest() {\n"
				+ "    MyTestExchangeMarketDataExchangeInfoRequest request = new MyTestExchangeMarketDataExchangeInfoRequest();\n"
				+ "    request.setSymbols(new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance()).deserialize(\"[\\\"BTC\\\", \\\"ETH\\\"]\"));\n"
				+ "    return request;\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)}and waits for response.\n"
				+ "   * @param request     The request to submit\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<MyTestExchangeMarketDataExchangeInfoResponse> execute(MyTestExchangeMarketDataExchangeInfoRequest request, Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.exchangeInfo() API with request:{}\", request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.exchangeInfo(request));\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#exchangeInfo(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest)}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(createRequest(),\n"
				+ "              DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				new RestEndpointDemoGenerator(exchange, api, restEndpointDescriptor).generate());
	}
	
	@Test
	public void testGenerateRestEndpointDemoSpecificRequesTypePrimitiveInt() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeInt", api);
		RestEndpointDemoGenerator generator = new RestEndpointDemoGenerator(exchange, api, restEndpoint);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeInt(java.lang.Integer)})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeIntDemo.class);\n"
				+ "  \n"
				+ "  public static Integer createRequest() {\n"
				+ "    return Integer.valueOf(12345);\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeInt(java.lang.Integer)}and waits for response.\n"
				+ "   * @param request     The request to submit\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<GenericResponse> execute(Integer request, Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeInt() API with request:{}\", request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.postRestRequestDataTypeInt(request));\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeInt(java.lang.Integer)}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(createRequest(),\n"
				+ "              DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
	}
	
	@Test
	public void testGenerateRestEndpointDemoSpecificRequesTypePrimitiveStringWithNamedArg() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeString", api);
		RestEndpointDemoGenerator generator = new RestEndpointDemoGenerator(exchange, api, restEndpoint);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeString(java.lang.String)})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataPostRestRequestDataTypeStringDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeStringDemo.class);\n"
				+ "  \n"
				+ "  public static String createHello() {\n"
				+ "    return \"Hello world!\";\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeString(java.lang.String)}and waits for response.\n"
				+ "   * @param request     The request to submit\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<GenericResponse> execute(String request, Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeString() API with request:{}\", request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.postRestRequestDataTypeString(request));\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeString(java.lang.String)}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(createHello(),\n"
				+ "              DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
	}
	
	@Test
	public void testGenerateRestEndpointDemoNoArgEndpoint() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeObjectNoParameters", api);
		RestEndpointDemoGenerator generator = new RestEndpointDemoGenerator(exchange, api, restEndpoint);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectNoParameters()})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataPostRestRequestDataTypeObjectNoParametersDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeObjectNoParametersDemo.class);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectNoParameters()}and waits for response.\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<GenericResponse> execute(Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeObjectNoParameters() API\");\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.postRestRequestDataTypeObjectNoParameters());\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectNoParameters()}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
	}
	
	@Test
	public void testGenerateRestEndpointSpecificRequestTypeObjectListMapWithReferencedObject() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeObjectListMap", api);
		RestEndpointDemoGenerator generator = new RestEndpointDemoGenerator(exchange, api, restEndpoint);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectListMap(java.util.Map)})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataPostRestRequestDataTypeObjectListMapDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeObjectListMapDemo.class);\n"
				+ "  \n"
				+ "  public static Map<String, List<SingleSymbol>> createRequest() {\n"
				+ "    SingleSymbol requestItem = new SingleSymbol();\n"
				+ "    requestItem.setSymbol(\"BTC_USDT\");\n"
				+ "    return Map.of(\"spot\", List.of(requestItem));\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectListMap(java.util.Map)}and waits for response.\n"
				+ "   * @param request     The request to submit\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<GenericResponse> execute(Map<String, List<SingleSymbol>> request, Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeObjectListMap() API with request:{}\", request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.postRestRequestDataTypeObjectListMap(request));\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeObjectListMap(java.util.Map)}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(createRequest(),\n"
				+ "              DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
	}
	
	@Test
	public void testGenerateRestEndpointRequestTypeIntList() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("postRestRequestDataTypeIntList", api);
		RestEndpointDemoGenerator generator = new RestEndpointDemoGenerator(exchange, api, restEndpoint);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.deserialization.json.field.IntegerJsonFieldDeserializer;\n"
				+ "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeIntList(java.util.List)})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataPostRestRequestDataTypeIntListDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataPostRestRequestDataTypeIntListDemo.class);\n"
				+ "  \n"
				+ "  public static List<Integer> createRequest() {\n"
				+ "    return new ListJsonFieldDeserializer<>(IntegerJsonFieldDeserializer.getInstance()).deserialize(\"[1, 3, 5]\");\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeIntList(java.util.List)}and waits for response.\n"
				+ "   * @param request     The request to submit\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<GenericResponse> execute(List<Integer> request, Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.postRestRequestDataTypeIntList() API with request:{}\", request);\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.postRestRequestDataTypeIntList(request));\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#postRestRequestDataTypeIntList(java.util.List)}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(createRequest(),\n"
				+ "              DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
	}
	
	@Test
	public void testGenerateRestEndpointEmptyResponseDataType() throws Exception {
		ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
		ExchangeApiDescriptor api = exchange.getApis().get(0);
		RestEndpointDescriptor restEndpoint = ClassesGeneratorTestUtil.findRestEndpointByName("getRestEmptyResponseDataType", api);
		RestEndpointDemoGenerator generator = new RestEndpointDemoGenerator(exchange, api, restEndpoint);
		Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
				+ "\n"
				+ "import java.util.Properties;\n"
				+ "import java.util.concurrent.ExecutionException;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
				+ "import javax.annotation.processing.Generated;\n"
				+ "import org.jxapi.exchange.ExchangeApiObserver;\n"
				+ "import org.jxapi.netutils.rest.RestResponse;\n"
				+ "import org.jxapi.util.DemoUtil;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Snippet to test call to {@link MyTestExchangeMarketDataApi#getRestEmptyResponseDataType()})}<br>\n"
				+ " */\n"
				+ "@Generated(\"org.jxapi.generator.java.exchange.api.demo.RestEndpointDemoGenerator\")\n"
				+ "public class MyTestExchangeMarketDataGetRestEmptyResponseDataTypeDemo {\n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataGetRestEmptyResponseDataTypeDemo.class);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Submits a call to {@link MyTestExchangeMarketDataApi#getRestEmptyResponseDataType()}and waits for response.\n"
				+ "   * @param configProperties  The configuration properties to instantiate exchange with\n"
				+ "   * @param apiObserver API observer that will notified of events. Is subscribed before REST API call and unsubscribed right after. Ignored if <code>null</code>\n"
				+ "   * @return Response data resulting from this API call\n"
				+ "   * @throws InterruptedException eventually thrown waiting for response\n"
				+ "   * @throws ExecutionException raised if response is not OK, see {@link RestResponse#isOk()}\n"
				+ "   */\n"
				+ "  public static RestResponse<String> execute(Properties configProperties, ExchangeApiObserver apiObserver) throws InterruptedException, ExecutionException {\n"
				+ "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
				+ "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
				+ "    log.info(\"Calling com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi.getRestEmptyResponseDataType() API\");\n"
				+ "    if (apiObserver != null) {\n"
				+ "      api.subscribeObserver(apiObserver);\n"
				+ "    }\n"
				+ "    try {\n"
				+ "      return DemoUtil.checkResponse(api.getRestEmptyResponseDataType());\n"
				+ "    }\n"
				+ "    finally {\n"
				+ "      if (apiObserver != null) {\n"
				+ "        api.unsubscribeObserver(apiObserver);\n"
				+ "      }\n"
				+ "      exchange.dispose();\n"
				+ "    }\n"
				+ "  }\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Runs REST endpoint demo snippet calling {@link MyTestExchangeMarketDataApi#getRestEmptyResponseDataType()}\n"
				+ "   * @param args no argument expected\n"
				+ "   */\n"
				+ "  public static void main(String[] args) {\n"
				+ "    try {\n"
				+ "      execute(DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID),\n"
				+ "              DemoUtil::logRestApiEvent);\n"
				+ "      System.exit(0);\n"
				+ "    }\n"
				+ "    catch (Throwable t) {\n"
				+ "      log.error(\"Exception raised from main()\", t);\n"
				+ "      System.exit(-1);\n"
				+ "    }\n"
				+ "  }\n"
				+ "}\n", 
				generator.generate());
	}
}
