package org.jxapi.generator.java.exchange.api.demo;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import org.jxapi.exchange.descriptor.ExchangeApiDescriptor;
import org.jxapi.exchange.descriptor.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.WebsocketEndpointDescriptor;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.exchange.ClassesGeneratorTestUtil;

/**
 * Unit test for {@link WebsocketEndpointDemoGenerator}
 */
public class WebsocketEndpointDemoGeneratorTest {
  
  @Test
  public void testGenerateWebsocketEndpointDemoObjectRequest() throws Exception {
    ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptor.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpointDescriptor = exchangeApiDescriptor.getWebsocketEndpoints().get(0);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeDemoProperties;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.MyTestExchangeProperties;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApiObserver;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "import org.jxapi.util.DemoProperties;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest, org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.WebsocketEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataTickerStreamDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataTickerStreamDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type MyTestExchangeMarketDataTickerStreamRequest using sample value(s) defined in the field descriptor.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static MyTestExchangeMarketDataTickerStreamRequest createRequest(Properties properties) {\n"
        + "    MyTestExchangeMarketDataTickerStreamRequest request = new MyTestExchangeMarketDataTickerStreamRequest();\n"
        + "    request.setSymbol(EncodingUtil.substituteArguments(\"${config.wsTickerStreamDemo.symbol}\", \"config.wsTickerStreamDemo.symbol\", MyTestExchangeDemoProperties.WsTickerStreamDemo.getSymbol(properties)));\n"
        + "    request.setApiKey(EncodingUtil.substituteArguments(\"${config.apiKey}\", \"config.apiKey\", MyTestExchangeProperties.getApiKey(properties)));\n"
        + "    return request;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * {@link MyTestExchangeMarketDataApi#subscribeTickerStream(com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest, org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
        + "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
        + "   * @param request                            The subscription request\n"
        + "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
        + "   * @param configProperties                   Exchange configuration properties.\n"
        + "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
        + "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
        + "   */\n"
        + "  public static void subscribe(MyTestExchangeMarketDataTickerStreamRequest request,\n"
        + "                               WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> messageListener,\n"
        + "                               Properties configProperties,\n"
        + "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
        + "    long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
        + "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
        + "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData tickerStream' for {} ms with request:{}\", subscriptionDuration, request);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    String subId = api.subscribeTickerStream(request, messageListener);\n"
        + "    DemoUtil.sleep(subscriptionDuration);\n"
        + "    log.info(\"Unubscribing from 'MyTestExchange MarketData tickerStream' stream\");\n"
        + "    api.unsubscribeTickerStream(subId);\n"
        + "    DemoUtil.sleep(delayBeforeExit);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    exchange.dispose();\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs websocket endpoint 'MyTestExchange MarketData tickerStream' subscription demo.\n"
        + "   * @param args no arguments expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      subscribe(createRequest(properties),\n"
        + "                DemoUtil::logWsMessage,\n"
        + "                properties,\n"
        + "                DemoUtil::logWsApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        createGenerator(exchangeDescriptor, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
  }
  
  @Test
  public void testGenerateWebsocketEndpointDemoSpecificRequesTypePrimitiveStringWithNamedArg() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpointDescriptor = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithStringRequestDataType", exchangeApiDescriptor);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApiObserver;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "import org.jxapi.util.DemoProperties;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeStreamWithStringRequestDataType(java.lang.String, org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.WebsocketEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataStreamWithStringRequestDataTypeDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataStreamWithStringRequestDataTypeDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the symbol field of type String using sample value(s) defined in the field descriptor.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static String createSymbol(Properties properties) {\n"
        + "    return \"BTC_USDT\";\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * {@link MyTestExchangeMarketDataApi#subscribeStreamWithStringRequestDataType(java.lang.String, org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
        + "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
        + "   * @param request                            The subscription request\n"
        + "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
        + "   * @param configProperties                   Exchange configuration properties.\n"
        + "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
        + "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
        + "   */\n"
        + "  public static void subscribe(String request,\n"
        + "                               WebsocketListener<Ticker> messageListener,\n"
        + "                               Properties configProperties,\n"
        + "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
        + "    long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
        + "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
        + "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData streamWithStringRequestDataType' for {} ms with request:{}\", subscriptionDuration, request);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    String subId = api.subscribeStreamWithStringRequestDataType(request, messageListener);\n"
        + "    DemoUtil.sleep(subscriptionDuration);\n"
        + "    log.info(\"Unubscribing from 'MyTestExchange MarketData streamWithStringRequestDataType' stream\");\n"
        + "    api.unsubscribeStreamWithStringRequestDataType(subId);\n"
        + "    DemoUtil.sleep(delayBeforeExit);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    exchange.dispose();\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs websocket endpoint 'MyTestExchange MarketData streamWithStringRequestDataType' subscription demo.\n"
        + "   * @param args no arguments expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      subscribe(createSymbol(properties),\n"
        + "                DemoUtil::logWsMessage,\n"
        + "                properties,\n"
        + "                DemoUtil::logWsApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n", 
        createGenerator(exchange, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
  }
  
  @Test
  public void testGenerateWebsocketEndpointDemoZeroArgs() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpointDescriptor = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithObjectRequestDataTypeZeroParameters", exchangeApiDescriptor);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.Properties;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApiObserver;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "import org.jxapi.util.DemoProperties;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectRequestDataTypeZeroParameters(org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.WebsocketEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataStreamWithObjectRequestDataTypeZeroParametersDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectRequestDataTypeZeroParameters(org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
        + "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
        + "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
        + "   * @param configProperties                   Exchange configuration properties.\n"
        + "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
        + "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
        + "   */\n"
        + "  public static void subscribe(WebsocketListener<Ticker> messageListener,\n"
        + "                               Properties configProperties,\n"
        + "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
        + "    long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
        + "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
        + "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData streamWithObjectRequestDataTypeZeroParameters' for {} ms\", subscriptionDuration);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    String subId = api.subscribeStreamWithObjectRequestDataTypeZeroParameters(messageListener);\n"
        + "    DemoUtil.sleep(subscriptionDuration);\n"
        + "    log.info(\"Unubscribing from 'MyTestExchange MarketData streamWithObjectRequestDataTypeZeroParameters' stream\");\n"
        + "    api.unsubscribeStreamWithObjectRequestDataTypeZeroParameters(subId);\n"
        + "    DemoUtil.sleep(delayBeforeExit);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    exchange.dispose();\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs websocket endpoint 'MyTestExchange MarketData streamWithObjectRequestDataTypeZeroParameters' subscription demo.\n"
        + "   * @param args no arguments expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      subscribe(DemoUtil::logWsMessage,\n"
        + "                properties,\n"
        + "                DemoUtil::logWsApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n", 
        createGenerator(exchange, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
  }
  
  @Test
  public void testGenerateWebsocketEndpointSpecificRequestTypeObjectListMapWithObjectDefinedInDifferentAPI() throws Exception {
    ExchangeDescriptor exchange = ExchangeDescriptorParser.fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
    ExchangeApiDescriptor exchangeApiDescriptor = exchange.getApis().get(0);
    WebsocketEndpointDescriptor websocketEndpointDescriptor = ClassesGeneratorTestUtil.findWebsocketEndpointByName("streamWithObjectListMapRequestDataType", exchangeApiDescriptor);
    Assert.assertEquals("package com.foo.bar.gen.marketdata.demo;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Properties;\n"
        + "\n"
        + "import com.foo.bar.gen.MyTestExchangeExchange;\n"
        + "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
        + "import com.foo.bar.gen.marketdata.MyTestExchangeMarketDataApi;\n"
        + "import com.foo.bar.gen.marketdata.pojo.MultiSymbol;\n"
        + "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
        + "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.exchange.ExchangeApiObserver;\n"
        + "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.MapJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.StringJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.websocket.WebsocketListener;\n"
        + "import org.jxapi.util.DemoProperties;\n"
        + "import org.jxapi.util.DemoUtil;\n"
        + "import org.slf4j.Logger;\n"
        + "import org.slf4j.LoggerFactory;\n"
        + "\n"
        + "/**\n"
        + " * Snippet to test call to {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectListMapRequestDataType(java.util.Map, org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.exchange.api.demo.WebsocketEndpointDemoGenerator\")\n"
        + "public class MyTestExchangeMarketDataStreamWithObjectListMapRequestDataTypeDemo {\n"
        + "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataStreamWithObjectListMapRequestDataTypeDemo.class);\n"
        + "  \n"
        + "  /**\n"
        + "   * Creates a sample value for the request field of type Map<String, List<MultiSymbol>> using sample value(s) defined in the field descriptor.\n"
        + "   * \n"
        + "   * @param properties the configuration properties to use for the sample value generation.\n"
        + "   */\n"
        + "  public static Map<String, List<MultiSymbol>> createRequest(Properties properties) {\n"
        + "    MultiSymbol requestItem = new MultiSymbol();\n"
        + "    requestItem.setSymbolList(new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance()).deserialize(\"[BTC_USDT, ETH_USDT]\"));\n"
        + "    requestItem.setSymbolMap(new MapJsonFieldDeserializer<>(new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance())).deserialize(\"{USDT=[BTC_USDT, ETH]}\"));\n"
        + "    SingleSymbol requestItem_symbolObject = new SingleSymbol();\n"
        + "    requestItem_symbolObject.setSymbol(\"BTC_USDT\");\n"
        + "    requestItem.setSymbolObject(requestItem_symbolObject);\n"
        + "    return Map.of(\"spot\", List.of(requestItem));\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * {@link MyTestExchangeMarketDataApi#subscribeStreamWithObjectListMapRequestDataType(java.util.Map, org.jxapi.netutils.websocket.WebsocketListener)}.\n"
        + "   * <br>Websocket endpoint subscription will be performed using given websocket listener then after waiting for <code>subscriptionDuration</code> delay, unsubscription is performed.\n"
        + "   * Finally waits for <code>delayBeforeExitAfterUnsubscription</code> delay before returning to make sure no more messages are dispatched.\n"
        + "   * @param request                            The subscription request\n"
        + "   * @param messageListener                    The listener that will receive messages dispatched while subscription is active\n"
        + "   * @param configProperties                   Exchange configuration properties.\n"
        + "   * @param apiObserver                       {@link ExchangeApiObserver} (optional, ignored if <code>null</code>) observer will be subscribed to Exchange API exposing websocket endpoint that will be notifed of received websocket events.Useful in particular to get notified of websocket errors.\n"
        + "   * @throws InterruptedException eventually thrown while sleeping for <code>subscriptionDuration</code> or <code>delayBeforeExitAfterUnsubscription</code> delays\n"
        + "   */\n"
        + "  public static void subscribe(Map<String, List<MultiSymbol>> request,\n"
        + "                               WebsocketListener<Ticker> messageListener,\n"
        + "                               Properties configProperties,\n"
        + "                               ExchangeApiObserver apiObserver) throws InterruptedException {\n"
        + "    MyTestExchangeExchange exchange = new MyTestExchangeExchangeImpl(\"test-\" + MyTestExchangeExchange.ID, configProperties);\n"
        + "    MyTestExchangeMarketDataApi api = exchange.getMyTestExchangeMarketDataApi();\n"
        + "    long subscriptionDuration = DemoProperties.getWebsocketSubscriptionDuration(configProperties);\n"
        + "    long delayBeforeExit = DemoProperties.getWebsocketDelayBeforeExit(configProperties);\n"
        + "    log.info(\"Subscribing to websocket API 'MyTestExchange MarketData streamWithObjectListMapRequestDataType' for {} ms with request:{}\", subscriptionDuration, request);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    String subId = api.subscribeStreamWithObjectListMapRequestDataType(request, messageListener);\n"
        + "    DemoUtil.sleep(subscriptionDuration);\n"
        + "    log.info(\"Unubscribing from 'MyTestExchange MarketData streamWithObjectListMapRequestDataType' stream\");\n"
        + "    api.unsubscribeStreamWithObjectListMapRequestDataType(subId);\n"
        + "    DemoUtil.sleep(delayBeforeExit);\n"
        + "    if (apiObserver != null) {\n"
        + "      api.subscribeObserver(apiObserver);\n"
        + "    }\n"
        + "    exchange.dispose();\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Runs websocket endpoint 'MyTestExchange MarketData streamWithObjectListMapRequestDataType' subscription demo.\n"
        + "   * @param args no arguments expected\n"
        + "   */\n"
        + "  public static void main(String[] args) {\n"
        + "    try {\n"
        + "      Properties properties = DemoUtil.loadDemoExchangeProperties(MyTestExchangeExchange.ID);\n"
        + "      subscribe(createRequest(properties),\n"
        + "                DemoUtil::logWsMessage,\n"
        + "                properties,\n"
        + "                DemoUtil::logWsApiEvent);\n"
        + "      System.exit(0);\n"
        + "    }\n"
        + "    catch (Throwable t) {\n"
        + "      log.error(\"Exception raised from main()\", t);\n"
        + "      System.exit(-1);\n"
        + "    }\n"
        + "  }\n"
        + "}\n", 
        createGenerator(exchange, exchangeApiDescriptor, websocketEndpointDescriptor).generate());
  }
  
  private WebsocketEndpointDemoGenerator createGenerator(
      ExchangeDescriptor exchange,
      ExchangeApiDescriptor api, 
      WebsocketEndpointDescriptor websocketEndpoint) {
    return new WebsocketEndpointDemoGenerator(exchange, api, websocketEndpoint, EndpointDemoGenUtil.collectDemoConfigProperties(exchange));
  }

}
