package org.jxapi.generator.java.pojo;

import java.util.List;
import java.util.Map;

import org.junit.Assert;
import org.junit.Test;
import org.jxapi.generator.java.JavaCodeGenUtil;
import org.jxapi.pojo.descriptor.Field;
import org.jxapi.pojo.descriptor.Type;
import org.jxapi.util.PlaceHolderResolver;

/**
 * Unit test for {@link PojoGenerator}
 */
public class PojoGeneratorTest {

  @Test
  public void testGenerate() {
    String typeName = "com.x.MyPojo";
    String typeDescription = "Used in PojoGeneratorTest";
    List<Field> properties = List.of(
      Field.builder().type(Type.LONG).name("id").build(),
      Field.builder().type(Type.INT).name("score").description("Current score, max is ${constants.maxScore}").build(),
      Field.builder().type("STRING_LIST").name("profiles").description("Profile, one of ${constants.profiles}").defaultValue(List.of("${constants.profiles.admin}", "${constants.profiles.regular}")).build(),
      Field.builder().type("OBJECT_LIST").name("foo").msgField("f").description("The foo")
             .property(Field.builder().type(Type.LONG).name("time").description("Creation time").build())
             .property(Field.builder().name("bar").description("The bar, which name can be ${constants.barName}")
                           .property(Field.builder().type(Type.STRING).name("name").build())
                           .build())
             .build(),
      Field.builder().type("OBJECT_LIST_MAP").name("toto").description("Toto")
             .property(Field.builder().type(Type.STRING).name("id").description("Toto ID").build())
             .build()
    );
    PlaceHolderResolver docPlaceHolderResolver = PlaceHolderResolver.create(Map.of("constants.maxScore", "100",
                                                                                   "constants.barName", "Happy hour",
                                                                                   "constants.profiles", "all_profiles"));
    PlaceHolderResolver defaultValuePlaceHolderResolver = PlaceHolderResolver
        .create(Map.of("constants.profiles.admin", "admin_profile", 
                      "constants.profiles.regular", "regular_profile"));
    PojoGenerator generator = new PojoGenerator(
        typeName, 
        typeDescription, 
        properties, 
        List.of("com.x.common.MyInterface"), 
        docPlaceHolderResolver,
        imports -> s -> JavaCodeGenUtil.getQuotedString(defaultValuePlaceHolderResolver.resolve(s)));
    
    Assert.assertEquals("package com.x;\n"
        + "\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.x.common.MyInterface;\n"
        + "import com.x.deserializers.MyPojoDeserializer;\n"
        + "import com.x.serializers.MyPojoSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
        + "import org.jxapi.netutils.deserialization.json.field.StringJsonFieldDeserializer;\n"
        + "import org.jxapi.util.CollectionUtil;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.DeepCloneable;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Used in PojoGeneratorTest\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyPojoSerializer.class)\n"
        + "@JsonDeserialize(using = MyPojoDeserializer.class)\n"
        + "public class MyPojo implements Pojo<MyPojo>, MyInterface {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -7067947056594815436L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyPojo} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Default value for <code>profiles</code>\n"
        + "   */\n"
        + "  public static final List<String> PROFILES_DEFAULT_VALUE = new ListJsonFieldDeserializer<>(StringJsonFieldDeserializer.getInstance()).deserialize(\"[\\\"admin_profile\\\",\\\"regular_profile\\\"]\");\n"
        + "  \n"
        + "  private Long id;\n"
        + "  private Integer score;\n"
        + "  private List<String> profiles = PROFILES_DEFAULT_VALUE;\n"
        + "  private List<MyPojoFoo> foo;\n"
        + "  private Map<String, List<MyPojoToto>> toto;\n"
        + "  \n"
        + "  public Long getId() {\n"
        + "    return id;\n"
        + "  }\n"
        + "  \n"
        + "  public void setId(Long id) {\n"
        + "    this.id = id;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Current score, max is 100\n"
        + "   */\n"
        + "  public Integer getScore() {\n"
        + "    return score;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param score Current score, max is 100\n"
        + "   */\n"
        + "  public void setScore(Integer score) {\n"
        + "    this.score = score;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Profile, one of all_profiles\n"
        + "   */\n"
        + "  public List<String> getProfiles() {\n"
        + "    return profiles;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param profiles Profile, one of all_profiles\n"
        + "   */\n"
        + "  public void setProfiles(List<String> profiles) {\n"
        + "    this.profiles = profiles;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return The foo <br>Message field <strong>f</strong>\n"
        + "   */\n"
        + "  public List<MyPojoFoo> getFoo() {\n"
        + "    return foo;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param foo The foo <br>Message field <strong>f</strong>\n"
        + "   */\n"
        + "  public void setFoo(List<MyPojoFoo> foo) {\n"
        + "    this.foo = foo;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return Toto\n"
        + "   */\n"
        + "  public Map<String, List<MyPojoToto>> getToto() {\n"
        + "    return toto;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param toto Toto\n"
        + "   */\n"
        + "  public void setToto(Map<String, List<MyPojoToto>> toto) {\n"
        + "    this.toto = toto;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyPojo o = (MyPojo) other;\n"
        + "    return Objects.equals(this.id, o.id)\n"
        + "        && Objects.equals(this.score, o.score)\n"
        + "        && Objects.equals(this.profiles, o.profiles)\n"
        + "        && Objects.equals(this.foo, o.foo)\n"
        + "        && Objects.equals(this.toto, o.toto);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyPojo other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.id, other.id);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.score, other.score);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compareLists(this.profiles, other.profiles, CompareUtil::compare);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compareLists(this.foo, other.foo, CompareUtil::compare);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compareMaps(this.toto, other.toto, (l0a, l0b) -> CompareUtil.compareLists(l0a,l0b, CompareUtil::compare));\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(id, score, profiles, foo, toto);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyPojo deepClone() {\n"
        + "    MyPojo clone = new MyPojo();\n"
        + "    clone.id = this.id;\n"
        + "    clone.score = this.score;\n"
        + "    clone.profiles = CollectionUtil.cloneList(this.profiles);\n"
        + "    clone.foo = CollectionUtil.deepCloneList(this.foo, DeepCloneable::deepClone);\n"
        + "    clone.toto = CollectionUtil.deepCloneMap(this.toto, l0 -> CollectionUtil.deepCloneList(l0, DeepCloneable::deepClone));\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyPojo}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private Long id;\n"
        + "    private Integer score;\n"
        + "    private List<String> profiles = PROFILES_DEFAULT_VALUE;\n"
        + "    private List<MyPojoFoo> foo;\n"
        + "    private Map<String, List<MyPojoToto>> toto;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>id</code> field in the builder\n"
        + "     * @return Builder instance\n"
        + "     * @see #setId(Long)\n"
        + "     */\n"
        + "    public Builder id(Long id)  {\n"
        + "      this.id = id;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>score</code> field in the builder\n"
        + "     * @param score Current score, max is 100\n"
        + "     * @return Builder instance\n"
        + "     * @see #setScore(Integer)\n"
        + "     */\n"
        + "    public Builder score(Integer score)  {\n"
        + "      this.score = score;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>profiles</code> field in the builder\n"
        + "     * @param profiles Profile, one of all_profiles\n"
        + "     * @return Builder instance\n"
        + "     * @see #setProfiles(List<String>)\n"
        + "     */\n"
        + "    public Builder profiles(List<String> profiles)  {\n"
        + "      this.profiles = profiles;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add an item to the <code>profiles</code> list.\n"
        + "     * @param item Item to add to current <code>profiles</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyPojo#setProfiles(List)\n"
        + "     */\n"
        + "    public Builder addToProfiles(String item) {\n"
        + "      if (this.profiles == null) {\n"
        + "        this.profiles = CollectionUtil.createList();\n"
        + "      }\n"
        + "      this.profiles.add(item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>foo</code> field in the builder\n"
        + "     * @param foo The foo Message field <strong>f</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setFoo(List<MyPojoFoo>)\n"
        + "     */\n"
        + "    public Builder foo(List<MyPojoFoo> foo)  {\n"
        + "      this.foo = foo;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add an item to the <code>foo</code> list.\n"
        + "     * @param item Item to add to current <code>foo</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyPojo#setFoo(List)\n"
        + "     */\n"
        + "    public Builder addToFoo(MyPojoFoo item) {\n"
        + "      if (this.foo == null) {\n"
        + "        this.foo = CollectionUtil.createList();\n"
        + "      }\n"
        + "      this.foo.add(item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>toto</code> field in the builder\n"
        + "     * @param toto Toto\n"
        + "     * @return Builder instance\n"
        + "     * @see #setToto(Map<String, List<MyPojoToto>>)\n"
        + "     */\n"
        + "    public Builder toto(Map<String, List<MyPojoToto>> toto)  {\n"
        + "      this.toto = toto;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * Will add or update a key/value pair to the <code>toto</code> map.\n"
        + "     * @param item Item to add to current <code>toto</code> list\n"
        + "     * @return Builder instance\n"
        + "     * @see MyPojo#setToto(Map)\n"
        + "     */\n"
        + "    public Builder addToToto(String key, List<MyPojoToto> item) {\n"
        + "      if (this.toto == null) {\n"
        + "        this.toto = CollectionUtil.createMap();\n"
        + "      }\n"
        + "      this.toto.put(key, item);\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyPojo using the values set in this builder\n"
        + "     */\n"
        + "    public MyPojo build() {\n"
        + "      MyPojo res = new MyPojo();\n"
        + "      res.id = this.id;\n"
        + "      res.score = this.score;\n"
        + "      res.profiles = CollectionUtil.cloneList(this.profiles);\n"
        + "      res.foo = CollectionUtil.deepCloneList(this.foo, DeepCloneable::deepClone);\n"
        + "      res.toto = CollectionUtil.deepCloneMap(this.toto, l0 -> CollectionUtil.deepCloneList(l0, DeepCloneable::deepClone));\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
    Assert.assertEquals(properties, generator.getFields());
  }
  
  @Test
  public void testGenerate_ImplicitObjectType() {
    String typeName = "com.x.pojo.MyPojoWithNullAdditionnalBody";
    String typeDescription = "Used in PojoGeneratorTest";
    List<Field> properties = List.of(
      Field.builder()
      .name("myObj")
      .description("identifier")
        .properties(List.of(
            Field.builder().type(Type.LONG).name("id").description("identifier").build()))
      .build()
    );
    PojoGenerator generator = new PojoGenerator(typeName, typeDescription, properties, null, null, null);
    Assert.assertEquals("package com.x.pojo;\n"
        + "\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.x.pojo.deserializers.MyPojoWithNullAdditionnalBodyDeserializer;\n"
        + "import com.x.pojo.serializers.MyPojoWithNullAdditionnalBodySerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Used in PojoGeneratorTest\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyPojoWithNullAdditionnalBodySerializer.class)\n"
        + "@JsonDeserialize(using = MyPojoWithNullAdditionnalBodyDeserializer.class)\n"
        + "public class MyPojoWithNullAdditionnalBody implements Pojo<MyPojoWithNullAdditionnalBody> {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -8553450902608483823L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyPojoWithNullAdditionnalBody} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  private MyPojoWithNullAdditionnalBodyMyObj myObj;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return identifier\n"
        + "   */\n"
        + "  public MyPojoWithNullAdditionnalBodyMyObj getMyObj() {\n"
        + "    return myObj;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param myObj identifier\n"
        + "   */\n"
        + "  public void setMyObj(MyPojoWithNullAdditionnalBodyMyObj myObj) {\n"
        + "    this.myObj = myObj;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    MyPojoWithNullAdditionnalBody o = (MyPojoWithNullAdditionnalBody) other;\n"
        + "    return Objects.equals(this.myObj, o.myObj);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyPojoWithNullAdditionnalBody other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.myObj, other.myObj);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(myObj);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyPojoWithNullAdditionnalBody deepClone() {\n"
        + "    MyPojoWithNullAdditionnalBody clone = new MyPojoWithNullAdditionnalBody();\n"
        + "    clone.myObj = this.myObj != null ? this.myObj.deepClone() : null;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyPojoWithNullAdditionnalBody}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private MyPojoWithNullAdditionnalBodyMyObj myObj;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>myObj</code> field in the builder\n"
        + "     * @param myObj identifier\n"
        + "     * @return Builder instance\n"
        + "     * @see #setMyObj(MyPojoWithNullAdditionnalBodyMyObj)\n"
        + "     */\n"
        + "    public Builder myObj(MyPojoWithNullAdditionnalBodyMyObj myObj)  {\n"
        + "      this.myObj = myObj;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyPojoWithNullAdditionnalBody using the values set in this builder\n"
        + "     */\n"
        + "    public MyPojoWithNullAdditionnalBody build() {\n"
        + "      MyPojoWithNullAdditionnalBody res = new MyPojoWithNullAdditionnalBody();\n"
        + "      res.myObj = this.myObj != null ? this.myObj.deepClone() : null;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
    Assert.assertEquals(properties, generator.getFields());
  }
  
  @Test
  public void testGenerate_NullProperties() {
    String typeName = "com.x.pojo.MyPojoWithNullProperties";
    String typeDescription = "Used in PojoGeneratorTest";
    PojoGenerator generator = new PojoGenerator(typeName, typeDescription, null, null, null, null);
    Assert.assertEquals("package com.x.pojo;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.x.pojo.deserializers.MyPojoWithNullPropertiesDeserializer;\n"
        + "import com.x.pojo.serializers.MyPojoWithNullPropertiesSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Used in PojoGeneratorTest\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyPojoWithNullPropertiesSerializer.class)\n"
        + "@JsonDeserialize(using = MyPojoWithNullPropertiesDeserializer.class)\n"
        + "public class MyPojoWithNullProperties implements Pojo<MyPojoWithNullProperties> {\n"
        + "  \n"
        + "  private static final long serialVersionUID = 739302860581584369L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyPojoWithNullProperties} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  \n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    return true;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyPojoWithNullProperties other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    return 0;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return 31 * getClass().hashCode();\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyPojoWithNullProperties deepClone() {\n"
        + "    return new MyPojoWithNullProperties();\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyPojoWithNullProperties}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyPojoWithNullProperties using the values set in this builder\n"
        + "     */\n"
        + "    public MyPojoWithNullProperties build() {\n"
        + "      return new MyPojoWithNullProperties();\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
    Assert.assertEquals(List.of(), generator.getFields());
  }
  
  @Test
  public void testGeneratePojoCodeMultipleFields() {
    PojoGenerator generator = new PojoGenerator("x.y.z.pojo.Foo", null, null, null, null, null);
    generator.addField(Field.builder().type(Type.STRING).name("name").description("the name").build());
    generator.addField(Field.builder().objectName("Bar").name("bar").objectDescription("The Bar class description").msgField("b").build());
    generator.addField(Field.builder().type(Type.INT).name("a").description("lower case 'a'").defaultValue(1).build());
    generator.addField(Field.builder().type(Type.INT).name("A").description("upper case 'A'").defaultValue(2).build());
    
    Assert.assertEquals("package x.y.z.pojo;\n"
        + "\n"
        + "import java.util.Objects;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.CompareUtil;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "import x.y.z.pojo.deserializers.FooDeserializer;\n"
        + "import x.y.z.pojo.serializers.FooSerializer;\n"
        + "\n"
        + "\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = FooSerializer.class)\n"
        + "@JsonDeserialize(using = FooDeserializer.class)\n"
        + "public class Foo implements Pojo<Foo> {\n"
        + "  \n"
        + "  private static final long serialVersionUID = -9000906500822625072L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link Foo} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Default value for <code>a</code>\n"
        + "   */\n"
        + "  public static final Integer A_DEFAULT_VALUE = Integer.valueOf(\"1\");\n"
        + "  \n"
        + "  /**\n"
        + "   * Default value for <code>A</code>\n"
        + "   */\n"
        + "  public static final Integer A_DEFAULT_VALUE_ = Integer.valueOf(\"2\");\n"
        + "  \n"
        + "  private String name;\n"
        + "  private Bar bar;\n"
        + "  private Integer a = A_DEFAULT_VALUE;\n"
        + "  private Integer A = A_DEFAULT_VALUE_;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return the name\n"
        + "   */\n"
        + "  public String getName() {\n"
        + "    return name;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param name the name\n"
        + "   */\n"
        + "  public void setName(String name) {\n"
        + "    this.name = name;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return <br>Message field <strong>b</strong>\n"
        + "   */\n"
        + "  public Bar getBar() {\n"
        + "    return bar;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param bar <br>Message field <strong>b</strong>\n"
        + "   */\n"
        + "  public void setBar(Bar bar) {\n"
        + "    this.bar = bar;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return lower case 'a'\n"
        + "   */\n"
        + "  public Integer geta() {\n"
        + "    return a;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param a lower case 'a'\n"
        + "   */\n"
        + "  public void seta(Integer a) {\n"
        + "    this.a = a;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @return upper case 'A'\n"
        + "   */\n"
        + "  public Integer getA() {\n"
        + "    return A;\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * @param A upper case 'A'\n"
        + "   */\n"
        + "  public void setA(Integer A) {\n"
        + "    this.A = A;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    Foo o = (Foo) other;\n"
        + "    return Objects.equals(this.name, o.name)\n"
        + "        && Objects.equals(this.bar, o.bar)\n"
        + "        && Objects.equals(this.a, o.a)\n"
        + "        && Objects.equals(this.A, o.A);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(Foo other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    int res = 0;\n"
        + "    res = CompareUtil.compare(this.name, other.name);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.bar, other.bar);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.a, other.a);\n"
        + "    if (res != 0) {\n"
        + "      return res;\n"
        + "    }\n"
        + "    res = CompareUtil.compare(this.A, other.A);\n"
        + "    return res;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return Objects.hash(name, bar, a, A);\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public Foo deepClone() {\n"
        + "    Foo clone = new Foo();\n"
        + "    clone.name = this.name;\n"
        + "    clone.bar = this.bar != null ? this.bar.deepClone() : null;\n"
        + "    clone.a = this.a;\n"
        + "    clone.A = this.A;\n"
        + "    return clone;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link Foo}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    private String name;\n"
        + "    private Bar bar;\n"
        + "    private Integer a = A_DEFAULT_VALUE;\n"
        + "    private Integer A = A_DEFAULT_VALUE_;\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>name</code> field in the builder\n"
        + "     * @param name the name\n"
        + "     * @return Builder instance\n"
        + "     * @see #setName(String)\n"
        + "     */\n"
        + "    public Builder name(String name)  {\n"
        + "      this.name = name;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>bar</code> field in the builder\n"
        + "     * @param bar Message field <strong>b</strong>\n"
        + "     * @return Builder instance\n"
        + "     * @see #setBar(Bar)\n"
        + "     */\n"
        + "    public Builder bar(Bar bar)  {\n"
        + "      this.bar = bar;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>a</code> field in the builder\n"
        + "     * @param a lower case 'a'\n"
        + "     * @return Builder instance\n"
        + "     * @see #seta(Integer)\n"
        + "     */\n"
        + "    public Builder a(Integer a)  {\n"
        + "      this.a = a;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * Will set the value of <code>A</code> field in the builder\n"
        + "     * @param A upper case 'A'\n"
        + "     * @return Builder instance\n"
        + "     * @see #setA(Integer)\n"
        + "     */\n"
        + "    public Builder A(Integer A)  {\n"
        + "      this.A = A;\n"
        + "      return this;\n"
        + "    }\n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of Foo using the values set in this builder\n"
        + "     */\n"
        + "    public Foo build() {\n"
        + "      Foo res = new Foo();\n"
        + "      res.name = this.name;\n"
        + "      res.bar = this.bar != null ? this.bar.deepClone() : null;\n"
        + "      res.a = this.a;\n"
        + "      res.A = this.A;\n"
        + "      return res;\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
    Assert.assertEquals(4, generator.getFields().size());
  }
  
  @Test
  public void testGenerateZeroFieldsPojo() {
    String typeName = "com.x.MyPojo";
    String typeDescription = "Used in PojoGeneratorTest";
    List<Field> properties = List.of();
    PojoGenerator generator = new PojoGenerator(
        typeName, 
        typeDescription, 
        properties, 
        List.of("com.x.common.MyInterface"), 
        null, 
        null);
    Assert.assertEquals("package com.x;\n"
        + "\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;\n"
        + "import com.fasterxml.jackson.databind.annotation.JsonSerialize;\n"
        + "import com.x.common.MyInterface;\n"
        + "import com.x.deserializers.MyPojoDeserializer;\n"
        + "import com.x.serializers.MyPojoSerializer;\n"
        + "import javax.annotation.processing.Generated;\n"
        + "import org.jxapi.util.EncodingUtil;\n"
        + "import org.jxapi.util.Pojo;\n"
        + "\n"
        + "/**\n"
        + " * Used in PojoGeneratorTest\n"
        + " */\n"
        + "@Generated(\"org.jxapi.generator.java.pojo.PojoGenerator\")\n"
        + "@JsonSerialize(using = MyPojoSerializer.class)\n"
        + "@JsonDeserialize(using = MyPojoDeserializer.class)\n"
        + "public class MyPojo implements Pojo<MyPojo>, MyInterface {\n"
        + "  \n"
        + "  private static final long serialVersionUID = 4951740427938809377L;\n"
        + "  \n"
        + "  /**\n"
        + "   * @return A new builder to build {@link MyPojo} objects\n"
        + "   */\n"
        + "  public static Builder builder() {\n"
        + "    return new Builder();\n"
        + "  }\n"
        + "  \n"
        + "  \n"
        + "  \n"
        + "  @Override\n"
        + "  public boolean equals(Object other) {\n"
        + "    if (other == null) {\n"
        + "      return false;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return true;\n"
        + "    }\n"
        + "    if (!getClass().equals(other.getClass()))\n"
        + "      return false;\n"
        + "    return true;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int compareTo(MyPojo other) {\n"
        + "    if (other == null) {\n"
        + "      return 1;\n"
        + "    }\n"
        + "    if (this == other) {\n"
        + "      return 0;\n"
        + "    }\n"
        + "    return 0;\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public int hashCode() {\n"
        + "    return 31 * getClass().hashCode();\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public MyPojo deepClone() {\n"
        + "    return new MyPojo();\n"
        + "  }\n"
        + "  \n"
        + "  @Override\n"
        + "  public String toString() {\n"
        + "    return EncodingUtil.pojoToString(this);\n"
        + "  }\n"
        + "  \n"
        + "  /**\n"
        + "   * Builder for {@link MyPojo}\n"
        + "   */\n"
        + "  @Generated(\"org.jxapi.generator.java.JavaTypeGenerator\")\n"
        + "  public static class Builder {\n"
        + "    \n"
        + "    \n"
        + "    \n"
        + "    /**\n"
        + "     * @return a new instance of MyPojo using the values set in this builder\n"
        + "     */\n"
        + "    public MyPojo build() {\n"
        + "      return new MyPojo();\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
        + "", 
        generator.generate());
  }

}
