package org.jxapi.generator.java.exchange.properties;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import org.junit.Assert;
import org.junit.Test;
import org.jxapi.exchange.descriptor.ConfigPropertyDescriptor;
import org.jxapi.exchange.descriptor.Constant;
import org.jxapi.exchange.descriptor.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.Type;
import org.jxapi.exchange.descriptor.parser.ExchangeDescriptorParser;
import org.jxapi.generator.java.exchange.api.demo.EndpointDemoGenUtil;

/**
 * Unit test for {@link PropertiesClassGenerator}
 */
public class PropertiesClassGeneratorTest {

    @Test
    public void testGenerate_NoGroup() {
        ConfigPropertyDescriptor stringProp = ConfigPropertyDescriptor.create("myString", Type.STRING, "My String property, for instance ${constants.stringPropDefaultValue}", "${constants.stringPropDefaultValue}");
        ConfigPropertyDescriptor stringPropWithNoDescriptionNoDefaultValue = ConfigPropertyDescriptor.create("myStringWithNoDescriptionNoDefaultValue", Type.STRING, null, null);
        ConfigPropertyDescriptor intProp = ConfigPropertyDescriptor.create("myInt", Type.INT, "My int property", "${constants.intPropDefaultValue}");
        ConfigPropertyDescriptor longProp = ConfigPropertyDescriptor.create("myLong", Type.LONG, "My long property", 1234567890123456L);
        ConfigPropertyDescriptor boolProp = ConfigPropertyDescriptor.create("myBool", Type.BOOLEAN, "My boolean property", true);
        ConfigPropertyDescriptor bigDecimalProp = ConfigPropertyDescriptor.create("myBigDecimal", Type.BIGDECIMAL, "My BigDecimal property", 1.2345);
        ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
        exchangeDescriptor.setId("myExchange");
        exchangeDescriptor.setBasePackage("com.x.y.exchange");
        exchangeDescriptor.setDescription("My exchange description");
        Constant c1 = Constant.create("stringPropDefaultValue", Type.STRING, "Sample string value", "fooVal");
        Constant c2 = Constant.create("intPropDefaultValue", Type.INT, "Sample int value", 42);
        exchangeDescriptor.setConstants(List.of(c1, c2));
        PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, 
            List.of(stringProp, 
                stringPropWithNoDescriptionNoDefaultValue, 
                intProp, 
                longProp, 
                boolProp, 
                bigDecimalProp),
            "demo");
        String expected =  "package com.x.y;\n"
            + "\n"
            + "import java.math.BigDecimal;\n"
            + "import java.util.List;\n"
            + "import java.util.Properties;\n"
            + "\n"
            + "import com.x.y.exchange.MyExchangeConstants;\n"
            + "import javax.annotation.processing.Generated;\n"
            + "import org.jxapi.exchange.descriptor.Type;\n"
            + "import org.jxapi.util.CollectionUtil;\n"
            + "import org.jxapi.util.ConfigProperty;\n"
            + "import org.jxapi.util.DefaultConfigProperty;\n"
            + "import org.jxapi.util.EncodingUtil;\n"
            + "import org.jxapi.util.PropertiesUtil;\n"
            + "\n"
            + "/**\n"
            + " * Configurable demo properties for <strong>myExchange</strong> exchange:<br>\n"
            + " * <table>\n"
            + " *   <caption>myExchange properties</caption>\n"
            + " *   <tr>\n"
            + " *     <th>Name</th>\n"
            + " *     <th>Type</th>\n"
            + " *     <th>Description</th>\n"
            + " *     <th>Default value</th>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myString</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td>My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myStringWithNoDescriptionNoDefaultValue</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td></td>\n"
            + " *     <td></td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myInt</td>\n"
            + " *     <td>INT</td>\n"
            + " *     <td>My int property</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myLong</td>\n"
            + " *     <td>LONG</td>\n"
            + " *     <td>My long property</td>\n"
            + " *     <td>1234567890123456</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBool</td>\n"
            + " *     <td>BOOLEAN</td>\n"
            + " *     <td>My boolean property</td>\n"
            + " *     <td>true</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBigDecimal</td>\n"
            + " *     <td>BIGDECIMAL</td>\n"
            + " *     <td>My BigDecimal property</td>\n"
            + " *     <td>1.2345</td>\n"
            + " *   </tr>\n"
            + " * </table>\n"
            + " * <br>\n"
            + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
            + " * @see ConfigProperty\n"
            + " */\n"
            + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "public class MyProperties {\n"
            + "  \n"
            + "  private MyProperties(){}\n"
            + "  \n"
            + "  /**\n"
            + "   * My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_STRING = DefaultConfigProperty.create(\n"
            + "    \"demo.myString\",\n"
            + "    Type.STRING,\n"
            + "    \"My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\",\n"
            + "    EncodingUtil.substituteArguments(\"${constants.stringPropDefaultValue}\", \"constants.stringPropDefaultValue\", MyExchangeConstants.STRING_PROP_DEFAULT_VALUE));\n"
            + "  \n"
            + "  \n"
            + "  public static final ConfigProperty MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE = DefaultConfigProperty.create(\n"
            + "    \"demo.myStringWithNoDescriptionNoDefaultValue\",\n"
            + "    Type.STRING,\n"
            + "    null,\n"
            + "    null);\n"
            + "  \n"
            + "  /**\n"
            + "   * My int property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_INT = DefaultConfigProperty.create(\n"
            + "    \"demo.myInt\",\n"
            + "    Type.INT,\n"
            + "    \"My int property\",\n"
            + "    EncodingUtil.substituteArguments(\"${constants.intPropDefaultValue}\", \"constants.intPropDefaultValue\", MyExchangeConstants.INT_PROP_DEFAULT_VALUE));\n"
            + "  \n"
            + "  /**\n"
            + "   * My long property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_LONG = DefaultConfigProperty.create(\n"
            + "    \"demo.myLong\",\n"
            + "    Type.LONG,\n"
            + "    \"My long property\",\n"
            + "    \"1234567890123456\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My boolean property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BOOL = DefaultConfigProperty.create(\n"
            + "    \"demo.myBool\",\n"
            + "    Type.BOOLEAN,\n"
            + "    \"My boolean property\",\n"
            + "    \"true\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My BigDecimal property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BIG_DECIMAL = DefaultConfigProperty.create(\n"
            + "    \"demo.myBigDecimal\",\n"
            + "    Type.BIGDECIMAL,\n"
            + "    \"My BigDecimal property\",\n"
            + "    \"1.2345\");\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myString' property.\n"
            + "   * @param properties Properties to look for value of 'myString' property into.\n"
            + "   * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "   */\n"
            + "  public static String getMyString(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myStringWithNoDescriptionNoDefaultValue' property.\n"
            + "   * @param properties Properties to look for value of 'myStringWithNoDescriptionNoDefaultValue' property into.\n"
            + "   * @return Value found in properties or <code>null</code> if not found.\n"
            + "   */\n"
            + "  public static String getMyStringWithNoDescriptionNoDefaultValue(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myInt' property.\n"
            + "   * @param properties Properties to look for value of 'myInt' property into.\n"
            + "   * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "   */\n"
            + "  public static Integer getMyInt(Properties properties) {return PropertiesUtil.getInt(properties, MY_INT);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myLong' property.\n"
            + "   * @param properties Properties to look for value of 'myLong' property into.\n"
            + "   * @return Value found in properties or default value <i>1234567890123456</i> if not found.\n"
            + "   */\n"
            + "  public static Long getMyLong(Properties properties) {return PropertiesUtil.getLong(properties, MY_LONG);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBool' property.\n"
            + "   * @param properties Properties to look for value of 'myBool' property into.\n"
            + "   * @return Value found in properties or default value <i>true</i> if not found.\n"
            + "   */\n"
            + "  public static Boolean isMyBool(Properties properties) {return PropertiesUtil.getBoolean(properties, MY_BOOL);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBigDecimal' property.\n"
            + "   * @param properties Properties to look for value of 'myBigDecimal' property into.\n"
            + "   * @return Value found in properties or default value <i>1.2345</i> if not found.\n"
            + "   */\n"
            + "  public static BigDecimal getMyBigDecimal(Properties properties) {return PropertiesUtil.getBigDecimal(properties, MY_BIG_DECIMAL);}\n"
            + "  /**\n"
            + "   * List of all configuration properties defined in this class\n"
            + "   */\n"
            + "  public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "    List.of(\n"
            + "      MY_STRING,\n"
            + "      MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE,\n"
            + "      MY_INT,\n"
            + "      MY_LONG,\n"
            + "      MY_BOOL,\n"
            + "      MY_BIG_DECIMAL))));\n"
            + "}\n"
            + "";
        Assert.assertEquals(expected, gen.generate());
    }
    
    @Test
    public void testGenerate_WithGroups() {
        ConfigPropertyDescriptor stringProp = ConfigPropertyDescriptor.create("myString", Type.STRING, "My String property, for instance ${constants.stringPropDefaultValue}", "${constants.stringPropDefaultValue}");
        ConfigPropertyDescriptor stringPropWithNoDescriptionNoDefaultValue = ConfigPropertyDescriptor.create("myStringWithNoDescriptionNoDefaultValue", Type.STRING, null, null);
        ConfigPropertyDescriptor intProp = ConfigPropertyDescriptor.create("myInt", Type.INT, "My int property", "${constants.intPropDefaultValue}");
        ConfigPropertyDescriptor intListProp = ConfigPropertyDescriptor.create("myIntList", Type.fromTypeName("INT_LIST"), "My int list property", "[1,2,3]");
        ConfigPropertyDescriptor longProp = ConfigPropertyDescriptor.create("myLong", Type.LONG, "My long property", 1234567890123456L);
        ConfigPropertyDescriptor boolProp = ConfigPropertyDescriptor.create("myBool", Type.BOOLEAN, "My boolean property", true);
        ConfigPropertyDescriptor bigDecimalProp = ConfigPropertyDescriptor.create("myBigDecimal", Type.BIGDECIMAL, "My BigDecimal property", 1.2345);
        ConfigPropertyDescriptor groupProp1 = ConfigPropertyDescriptor.createGroup("myGroup1", "My group1 description", List.of(stringPropWithNoDescriptionNoDefaultValue, intProp, intListProp));
        ConfigPropertyDescriptor groupProp21 = ConfigPropertyDescriptor.createGroup("myGroup21", "My group nested in group2 description", List.of(longProp));
        ConfigPropertyDescriptor groupProp2 = ConfigPropertyDescriptor.createGroup("myGroup2", "My group2 description", List.of(groupProp21, boolProp));
        ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
        exchangeDescriptor.setId("myExchange");
        exchangeDescriptor.setBasePackage("com.x.y.exchange");
        exchangeDescriptor.setDescription("My exchange description");
        Constant c1 = Constant.create("stringPropDefaultValue", Type.STRING, "Sample string value", "fooVal");
        Constant c2 = Constant.create("intPropDefaultValue", Type.INT, "Sample int value", 42);
        exchangeDescriptor.setConstants(List.of(c1, c2));
        PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, 
            List.of(stringProp, 
                groupProp1,
                groupProp2,
                bigDecimalProp),
            null);
        String expected =  "package com.x.y;\n"
            + "\n"
            + "import java.math.BigDecimal;\n"
            + "import java.util.List;\n"
            + "import java.util.Properties;\n"
            + "\n"
            + "import com.x.y.exchange.MyExchangeConstants;\n"
            + "import javax.annotation.processing.Generated;\n"
            + "import org.jxapi.exchange.descriptor.Type;\n"
            + "import org.jxapi.util.CollectionUtil;\n"
            + "import org.jxapi.util.ConfigProperty;\n"
            + "import org.jxapi.util.DefaultConfigProperty;\n"
            + "import org.jxapi.util.EncodingUtil;\n"
            + "import org.jxapi.util.PropertiesUtil;\n"
            + "\n"
            + "/**\n"
            + " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
            + " * <table>\n"
            + " *   <caption>myExchange properties</caption>\n"
            + " *   <tr>\n"
            + " *     <th>Name</th>\n"
            + " *     <th>Type</th>\n"
            + " *     <th>Description</th>\n"
            + " *     <th>Default value</th>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myString</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td>My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup1.myStringWithNoDescriptionNoDefaultValue</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td></td>\n"
            + " *     <td></td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup1.myInt</td>\n"
            + " *     <td>INT</td>\n"
            + " *     <td>My int property</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup1.myIntList</td>\n"
            + " *     <td>INT_LIST</td>\n"
            + " *     <td>My int list property</td>\n"
            + " *     <td>[1,2,3]</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup2.myGroup21.myLong</td>\n"
            + " *     <td>LONG</td>\n"
            + " *     <td>My long property</td>\n"
            + " *     <td>1234567890123456</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup2.myBool</td>\n"
            + " *     <td>BOOLEAN</td>\n"
            + " *     <td>My boolean property</td>\n"
            + " *     <td>true</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBigDecimal</td>\n"
            + " *     <td>BIGDECIMAL</td>\n"
            + " *     <td>My BigDecimal property</td>\n"
            + " *     <td>1.2345</td>\n"
            + " *   </tr>\n"
            + " * </table>\n"
            + " * <br>\n"
            + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
            + " * @see ConfigProperty\n"
            + " */\n"
            + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "public class MyProperties {\n"
            + "  \n"
            + "  private MyProperties(){}\n"
            + "  \n"
            + "  /**\n"
            + "   * My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_STRING = DefaultConfigProperty.create(\n"
            + "    \"myString\",\n"
            + "    Type.STRING,\n"
            + "    \"My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\",\n"
            + "    EncodingUtil.substituteArguments(\"${constants.stringPropDefaultValue}\", \"constants.stringPropDefaultValue\", MyExchangeConstants.STRING_PROP_DEFAULT_VALUE));\n"
            + "  \n"
            + "  /**\n"
            + "   * My group1 description\n"
            + "   */\n"
            + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "  public static class MyGroup1 {\n"
            + "    \n"
            + "    private MyGroup1(){}\n"
            + "    \n"
            + "    \n"
            + "    public static final ConfigProperty MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE = DefaultConfigProperty.create(\n"
            + "      \"myGroup1.myStringWithNoDescriptionNoDefaultValue\",\n"
            + "      Type.STRING,\n"
            + "      null,\n"
            + "      null);\n"
            + "    \n"
            + "    /**\n"
            + "     * My int property\n"
            + "     */\n"
            + "    public static final ConfigProperty MY_INT = DefaultConfigProperty.create(\n"
            + "      \"myGroup1.myInt\",\n"
            + "      Type.INT,\n"
            + "      \"My int property\",\n"
            + "      EncodingUtil.substituteArguments(\"${constants.intPropDefaultValue}\", \"constants.intPropDefaultValue\", MyExchangeConstants.INT_PROP_DEFAULT_VALUE));\n"
            + "    \n"
            + "    /**\n"
            + "     * My int list property\n"
            + "     */\n"
            + "    public static final ConfigProperty MY_INT_LIST = DefaultConfigProperty.create(\n"
            + "      \"myGroup1.myIntList\",\n"
            + "      Type.STRING,\n"
            + "      \"My int list property\",\n"
            + "      \"[1,2,3]\");\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myStringWithNoDescriptionNoDefaultValue' property.\n"
            + "     * @param properties Properties to look for value of 'myStringWithNoDescriptionNoDefaultValue' property into.\n"
            + "     * @return Value found in properties or <code>null</code> if not found.\n"
            + "     */\n"
            + "    public static String getMyStringWithNoDescriptionNoDefaultValue(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE);}\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myInt' property.\n"
            + "     * @param properties Properties to look for value of 'myInt' property into.\n"
            + "     * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "     */\n"
            + "    public static Integer getMyInt(Properties properties) {return PropertiesUtil.getInt(properties, MY_INT);}\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myIntList' property.\n"
            + "     * @param properties Properties to look for value of 'myIntList' property into.\n"
            + "     * @return Value found in properties or default value <i>\"[1,2,3]\"</i> if not found.\n"
            + "     */\n"
            + "    public static String getMyIntList(Properties properties) {return PropertiesUtil.getString(properties, MY_INT_LIST);}\n"
            + "    /**\n"
            + "     * List of all configuration properties defined in this class\n"
            + "     */\n"
            + "    public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "      List.of(\n"
            + "        MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE,\n"
            + "        MY_INT,\n"
            + "        MY_INT_LIST))));\n"
            + "  }\n"
            + "  \n"
            + "  /**\n"
            + "   * My group2 description\n"
            + "   */\n"
            + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "  public static class MyGroup2 {\n"
            + "    \n"
            + "    private MyGroup2(){}\n"
            + "    \n"
            + "    /**\n"
            + "     * My group nested in group2 description\n"
            + "     */\n"
            + "    @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "    public static class MyGroup21 {\n"
            + "      \n"
            + "      private MyGroup21(){}\n"
            + "      \n"
            + "      /**\n"
            + "       * My long property\n"
            + "       */\n"
            + "      public static final ConfigProperty MY_LONG = DefaultConfigProperty.create(\n"
            + "        \"myGroup2.myGroup21.myLong\",\n"
            + "        Type.LONG,\n"
            + "        \"My long property\",\n"
            + "        \"1234567890123456\");\n"
            + "      \n"
            + "      /**\n"
            + "       * Retrieves value of 'myLong' property.\n"
            + "       * @param properties Properties to look for value of 'myLong' property into.\n"
            + "       * @return Value found in properties or default value <i>1234567890123456</i> if not found.\n"
            + "       */\n"
            + "      public static Long getMyLong(Properties properties) {return PropertiesUtil.getLong(properties, MY_LONG);}\n"
            + "      /**\n"
            + "       * List of all configuration properties defined in this class\n"
            + "       */\n"
            + "      public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "        List.of(\n"
            + "          MY_LONG))));\n"
            + "    }\n"
            + "    \n"
            + "    /**\n"
            + "     * My boolean property\n"
            + "     */\n"
            + "    public static final ConfigProperty MY_BOOL = DefaultConfigProperty.create(\n"
            + "      \"myGroup2.myBool\",\n"
            + "      Type.BOOLEAN,\n"
            + "      \"My boolean property\",\n"
            + "      \"true\");\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myBool' property.\n"
            + "     * @param properties Properties to look for value of 'myBool' property into.\n"
            + "     * @return Value found in properties or default value <i>true</i> if not found.\n"
            + "     */\n"
            + "    public static Boolean isMyBool(Properties properties) {return PropertiesUtil.getBoolean(properties, MY_BOOL);}\n"
            + "    /**\n"
            + "     * List of all configuration properties defined in this class\n"
            + "     */\n"
            + "    public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "      MyGroup21.ALL,\n"
            + "      List.of(\n"
            + "        MY_BOOL))));\n"
            + "  }\n"
            + "  \n"
            + "  /**\n"
            + "   * My BigDecimal property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BIG_DECIMAL = DefaultConfigProperty.create(\n"
            + "    \"myBigDecimal\",\n"
            + "    Type.BIGDECIMAL,\n"
            + "    \"My BigDecimal property\",\n"
            + "    \"1.2345\");\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myString' property.\n"
            + "   * @param properties Properties to look for value of 'myString' property into.\n"
            + "   * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "   */\n"
            + "  public static String getMyString(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBigDecimal' property.\n"
            + "   * @param properties Properties to look for value of 'myBigDecimal' property into.\n"
            + "   * @return Value found in properties or default value <i>1.2345</i> if not found.\n"
            + "   */\n"
            + "  public static BigDecimal getMyBigDecimal(Properties properties) {return PropertiesUtil.getBigDecimal(properties, MY_BIG_DECIMAL);}\n"
            + "  /**\n"
            + "   * List of all configuration properties defined in this class\n"
            + "   */\n"
            + "  public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "    List.of(\n"
            + "      MY_STRING\n"
            + "    ),\n"
            + "    MyGroup1.ALL,\n"
            + "    MyGroup2.ALL,\n"
            + "    List.of(\n"
            + "      MY_BIG_DECIMAL))));\n"
            + "}\n"
            + "";
        Assert.assertEquals(expected, gen.generate());
    }
    
    @Test
    public void testGenerate_EmptyProperties() {
      ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
      exchangeDescriptor.setId("myExchange");
      exchangeDescriptor.setBasePackage("com.x.y.exchange");
      PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, List.of(), "");
      Assert.assertEquals("package com.x.y;\n"
          + "\n"
          + "import java.util.List;\n"
          + "\n"
          + "import javax.annotation.processing.Generated;\n"
          + "import org.jxapi.util.ConfigProperty;\n"
          + "\n"
          + "/**\n"
          + " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
          + " * <table>\n"
          + " *   <caption>myExchange properties</caption>\n"
          + " *   <tr>\n"
          + " *     <th>Name</th>\n"
          + " *     <th>Type</th>\n"
          + " *     <th>Description</th>\n"
          + " *     <th>Default value</th>\n"
          + " *   </tr>\n"
          + " * </table>\n"
          + " * <br>\n"
          + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
          + " * @see ConfigProperty\n"
          + " */\n"
          + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "public class MyProperties {\n"
          + "  \n"
          + "  private MyProperties(){}\n"
          + "  /**\n"
          + "   * List of all configuration properties defined in this class\n"
          + "   */\n"
          + "  public static final List<ConfigProperty> ALL = List.of();\n"
          + "}\n"
          + "", gen.generate());
    }
    
    @Test
    public void testGenerateProperties_WithConflictingPropertyNames() {
      ConfigPropertyDescriptor p1 = ConfigPropertyDescriptor.create("p1", Type.STRING, null, null);
      ConfigPropertyDescriptor p1Up = ConfigPropertyDescriptor.create("P1", Type.STRING, null, null);
      ConfigPropertyDescriptor p1Underscore = ConfigPropertyDescriptor.create("p1_", Type.STRING, null, null);
      ConfigPropertyDescriptor subAll = ConfigPropertyDescriptor.create("all", Type.STRING, "all speciific prop for P1_ group properties", null);
      ConfigPropertyDescriptor p1UpUnderscore = ConfigPropertyDescriptor.createGroup("P1_", null, List.of(subAll));
      ConfigPropertyDescriptor all = ConfigPropertyDescriptor.create("all", Type.STRING, "all speciific prop", null);
      ConfigPropertyDescriptor allUnderscore = ConfigPropertyDescriptor.create("all_", Type.STRING, "all_ specific prop", null);
      
      List<ConfigPropertyDescriptor> allProps = List.of(p1, p1Up, p1Underscore, p1UpUnderscore, all, allUnderscore);
      ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
      exchangeDescriptor.setId("myExchange");
      exchangeDescriptor.setBasePackage("com.x.y.exchange");
      PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, allProps, "demo");
      Assert.assertEquals("package com.x.y;\n"
          + "\n"
          + "import java.util.List;\n"
          + "import java.util.Properties;\n"
          + "\n"
          + "import javax.annotation.processing.Generated;\n"
          + "import org.jxapi.exchange.descriptor.Type;\n"
          + "import org.jxapi.util.CollectionUtil;\n"
          + "import org.jxapi.util.ConfigProperty;\n"
          + "import org.jxapi.util.DefaultConfigProperty;\n"
          + "import org.jxapi.util.PropertiesUtil;\n"
          + "\n"
          + "/**\n"
          + " * Configurable demo properties for <strong>myExchange</strong> exchange:<br>\n"
          + " * <table>\n"
          + " *   <caption>myExchange properties</caption>\n"
          + " *   <tr>\n"
          + " *     <th>Name</th>\n"
          + " *     <th>Type</th>\n"
          + " *     <th>Description</th>\n"
          + " *     <th>Default value</th>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>p1</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td></td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>P1</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td></td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>p1_</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td></td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>P1_.all</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>all speciific prop for P1_ group properties</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>all</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>all speciific prop</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>all_</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>all_ specific prop</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " * </table>\n"
          + " * <br>\n"
          + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
          + " * @see ConfigProperty\n"
          + " */\n"
          + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "public class MyProperties {\n"
          + "  \n"
          + "  private MyProperties(){}\n"
          + "  \n"
          + "  \n"
          + "  public static final ConfigProperty P1 = DefaultConfigProperty.create(\n"
          + "    \"demo.p1\",\n"
          + "    Type.STRING,\n"
          + "    null,\n"
          + "    null);\n"
          + "  \n"
          + "  \n"
          + "  public static final ConfigProperty P1_ = DefaultConfigProperty.create(\n"
          + "    \"demo.P1\",\n"
          + "    Type.STRING,\n"
          + "    null,\n"
          + "    null);\n"
          + "  \n"
          + "  \n"
          + "  public static final ConfigProperty P1__ = DefaultConfigProperty.create(\n"
          + "    \"demo.p1_\",\n"
          + "    Type.STRING,\n"
          + "    null,\n"
          + "    null);\n"
          + "  \n"
          + "  \n"
          + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "  public static class P1___ {\n"
          + "    \n"
          + "    private P1___(){}\n"
          + "    \n"
          + "    /**\n"
          + "     * all speciific prop for P1_ group properties\n"
          + "     */\n"
          + "    public static final ConfigProperty ALL = DefaultConfigProperty.create(\n"
          + "      \"demo.P1_.all\",\n"
          + "      Type.STRING,\n"
          + "      \"all speciific prop for P1_ group properties\",\n"
          + "      null);\n"
          + "    \n"
          + "    /**\n"
          + "     * Retrieves value of 'all' property.\n"
          + "     * @param properties Properties to look for value of 'all' property into.\n"
          + "     * @return Value found in properties or <code>null</code> if not found.\n"
          + "     */\n"
          + "    public static String getAll(Properties properties) {return PropertiesUtil.getString(properties, ALL);}\n"
          + "    /**\n"
          + "     * List of all configuration properties defined in this class\n"
          + "     */\n"
          + "    public static final List<ConfigProperty> ALL_ = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "      List.of(\n"
          + "        ALL))));\n"
          + "  }\n"
          + "  \n"
          + "  /**\n"
          + "   * all speciific prop\n"
          + "   */\n"
          + "  public static final ConfigProperty ALL = DefaultConfigProperty.create(\n"
          + "    \"demo.all\",\n"
          + "    Type.STRING,\n"
          + "    \"all speciific prop\",\n"
          + "    null);\n"
          + "  \n"
          + "  /**\n"
          + "   * all_ specific prop\n"
          + "   */\n"
          + "  public static final ConfigProperty ALL_ = DefaultConfigProperty.create(\n"
          + "    \"demo.all_\",\n"
          + "    Type.STRING,\n"
          + "    \"all_ specific prop\",\n"
          + "    null);\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'p1' property.\n"
          + "   * @param properties Properties to look for value of 'p1' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getp1(Properties properties) {return PropertiesUtil.getString(properties, P1);}\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'P1' property.\n"
          + "   * @param properties Properties to look for value of 'P1' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getP1(Properties properties) {return PropertiesUtil.getString(properties, P1_);}\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'p1_' property.\n"
          + "   * @param properties Properties to look for value of 'p1_' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getp1_(Properties properties) {return PropertiesUtil.getString(properties, P1__);}\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'all' property.\n"
          + "   * @param properties Properties to look for value of 'all' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getAll(Properties properties) {return PropertiesUtil.getString(properties, ALL);}\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'all_' property.\n"
          + "   * @param properties Properties to look for value of 'all_' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getAll_(Properties properties) {return PropertiesUtil.getString(properties, ALL_);}\n"
          + "  /**\n"
          + "   * List of all configuration properties defined in this class\n"
          + "   */\n"
          + "  public static final List<ConfigProperty> ALL__ = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "    List.of(\n"
          + "      P1,\n"
          + "      P1_,\n"
          + "      P1__\n"
          + "    ),\n"
          + "    P1___.ALL_,\n"
          + "    List.of(\n"
          + "      ALL,\n"
          + "      ALL_))));\n"
          + "}\n"
          + "", gen.generate());
    }
    
    @Test
    public void testGenerateProperties_ConflictExchangeProps() throws IOException {
      Path srcTestResourcesFolder = Paths.get(".", "src", "test", "resources");
      Path exchangeDescriptorFile = srcTestResourcesFolder.resolve("exchangeWithEndpointWithConflictingPropertyNames.yaml");
      ExchangeDescriptor exchangeDescriptor = ExchangeDescriptorParser.fromYaml(exchangeDescriptorFile);
      PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor,  EndpointDemoGenUtil.collectDemoConfigProperties(exchangeDescriptor), "");
      Assert.assertEquals("package com.x.y;\n"
          + "\n"
          + "import java.math.BigDecimal;\n"
          + "import java.util.List;\n"
          + "import java.util.Properties;\n"
          + "\n"
          + "import javax.annotation.processing.Generated;\n"
          + "import org.jxapi.exchange.descriptor.Type;\n"
          + "import org.jxapi.exchanges.conflict.gen.ConflictConstants;\n"
          + "import org.jxapi.util.CollectionUtil;\n"
          + "import org.jxapi.util.ConfigProperty;\n"
          + "import org.jxapi.util.DefaultConfigProperty;\n"
          + "import org.jxapi.util.EncodingUtil;\n"
          + "import org.jxapi.util.PropertiesUtil;\n"
          + "\n"
          + "/**\n"
          + " * Configurable properties for <strong>conflict</strong> exchange:<br>\n"
          + " * <table>\n"
          + " *   <caption>conflict properties</caption>\n"
          + " *   <tr>\n"
          + " *     <th>Name</th>\n"
          + " *     <th>Type</th>\n"
          + " *     <th>Description</th>\n"
          + " *     <th>Default value</th>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.rest.myRestEndpoint.request</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>Demo configuration property for myRestEndpoint.request field as raw JSON string value.</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.rest.myRestEndpoint.request.p1</td>\n"
          + " *     <td>INT</td>\n"
          + " *     <td>Demo configuration property for request.p1 field.<p>\n"
          + " *     p1 parameter</td>\n"
          + " *     <td>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1}</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.rest.myRestEndpoint.request.P1</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>Demo configuration property for request.P1 field.<p>\n"
          + " *     P1 parameter (note the uppercase 'P'). Its  value should be one of the values of the {@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___} constant group</td>\n"
          + " *     <td>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___#BAR}</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.rest.myRestEndpoint.request.p1_</td>\n"
          + " *     <td>LONG</td>\n"
          + " *     <td>Demo configuration property for request.p1_ field.<p>\n"
          + " *     p1_ parameter (note the underscore)</td>\n"
          + " *     <td>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1_}</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.rest.myRestEndpoint.request.P1_</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>Demo configuration property for request.P1_ field as raw JSON string value.<p>\n"
          + " *     P1_ parameter (note the uppercase 'P' and underscore)</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.rest.myRestEndpoint.request.P1_.subParam</td>\n"
          + " *     <td>BIGDECIMAL</td>\n"
          + " *     <td>Demo configuration property for P1_.subParam field.<p>\n"
          + " *     subParam parameter</td>\n"
          + " *     <td>12.35</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.ws.myWsEndpoint.request</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>Demo configuration property for myWsEndpoint.request field as raw JSON string value.</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.ws.myWsEndpoint.request.p1</td>\n"
          + " *     <td>INT</td>\n"
          + " *     <td>Demo configuration property for request.p1 field.<p>\n"
          + " *     p1 parameter</td>\n"
          + " *     <td>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1}</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.ws.myWsEndpoint.request.P1</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>Demo configuration property for request.P1 field.<p>\n"
          + " *     P1 parameter (note the uppercase 'P'). Its  value should be one of the values of the {@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___} constant group</td>\n"
          + " *     <td>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___#BAR}</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.ws.myWsEndpoint.request.p1_</td>\n"
          + " *     <td>LONG</td>\n"
          + " *     <td>Demo configuration property for request.p1_ field.<p>\n"
          + " *     p1_ parameter (note the underscore)</td>\n"
          + " *     <td>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1_}</td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.ws.myWsEndpoint.request.P1_</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td>Demo configuration property for request.P1_ field as raw JSON string value.<p>\n"
          + " *     P1_ parameter (note the uppercase 'P' and underscore)</td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>v1.ws.myWsEndpoint.request.P1_.subParam</td>\n"
          + " *     <td>BIGDECIMAL</td>\n"
          + " *     <td>Demo configuration property for P1_.subParam field.<p>\n"
          + " *     subParam parameter</td>\n"
          + " *     <td>12.35</td>\n"
          + " *   </tr>\n"
          + " * </table>\n"
          + " * <br>\n"
          + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
          + " * @see ConfigProperty\n"
          + " */\n"
          + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "public class MyProperties {\n"
          + "  \n"
          + "  private MyProperties(){}\n"
          + "  \n"
          + "  /**\n"
          + "   * Configuration properties for v1 API group endpoints demo snippets\n"
          + "   */\n"
          + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "  public static class V1 {\n"
          + "    \n"
          + "    private V1(){}\n"
          + "    \n"
          + "    /**\n"
          + "     * Configuration properties for REST endpoints demo snippets of v1 API group\n"
          + "     */\n"
          + "    @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "    public static class Rest {\n"
          + "      \n"
          + "      private Rest(){}\n"
          + "      \n"
          + "      /**\n"
          + "       * Configuration properties for REST myRestEndpoint endpoint of v1 API group\n"
          + "       */\n"
          + "      @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "      public static class MyRestEndpoint {\n"
          + "        \n"
          + "        private MyRestEndpoint(){}\n"
          + "        \n"
          + "        /**\n"
          + "         * Demo configuration property for myRestEndpoint.request field as raw JSON string value.\n"
          + "         */\n"
          + "        public static final ConfigProperty REQUEST = DefaultConfigProperty.create(\n"
          + "          \"v1.rest.myRestEndpoint.request\",\n"
          + "          Type.STRING,\n"
          + "          \"Demo configuration property for myRestEndpoint.request field as raw JSON string value.\",\n"
          + "          null);\n"
          + "        \n"
          + "        /**\n"
          + "         * Demo configuration properties for myRestEndpoint.request field object instance.\n"
          + "         */\n"
          + "        @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "        public static class Request {\n"
          + "          \n"
          + "          private Request(){}\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.p1 field.<p>\n"
          + "           * p1 parameter\n"
          + "           */\n"
          + "          public static final ConfigProperty P1 = DefaultConfigProperty.create(\n"
          + "            \"v1.rest.myRestEndpoint.request.p1\",\n"
          + "            Type.INT,\n"
          + "            \"Demo configuration property for request.p1 field.<p>\\np1 parameter\",\n"
          + "            EncodingUtil.substituteArguments(\"${constants.c1}\", \"constants.c1\", ConflictConstants.C1));\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.P1 field.<p>\n"
          + "           * P1 parameter (note the uppercase 'P'). Its  value should be one of the values of the {@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___} constant group\n"
          + "           */\n"
          + "          public static final ConfigProperty P1_ = DefaultConfigProperty.create(\n"
          + "            \"v1.rest.myRestEndpoint.request.P1\",\n"
          + "            Type.STRING,\n"
          + "            \"Demo configuration property for request.P1 field.<p>\\nP1 parameter (note the uppercase 'P'). Its  value should be one of the values of the {@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___} constant group\",\n"
          + "            EncodingUtil.substituteArguments(\"${constants.C1_.bar}\", \"constants.C1_.bar\", ConflictConstants.C1___.BAR));\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.p1_ field.<p>\n"
          + "           * p1_ parameter (note the underscore)\n"
          + "           */\n"
          + "          public static final ConfigProperty P1__ = DefaultConfigProperty.create(\n"
          + "            \"v1.rest.myRestEndpoint.request.p1_\",\n"
          + "            Type.LONG,\n"
          + "            \"Demo configuration property for request.p1_ field.<p>\\np1_ parameter (note the underscore)\",\n"
          + "            EncodingUtil.substituteArguments(\"${constants.c1_}\", \"constants.c1_\", ConflictConstants.C1__));\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.P1_ field as raw JSON string value.<p>\n"
          + "           * P1_ parameter (note the uppercase 'P' and underscore)\n"
          + "           */\n"
          + "          public static final ConfigProperty P1___ = DefaultConfigProperty.create(\n"
          + "            \"v1.rest.myRestEndpoint.request.P1_\",\n"
          + "            Type.STRING,\n"
          + "            \"Demo configuration property for request.P1_ field as raw JSON string value.<p>\\nP1_ parameter (note the uppercase 'P' and underscore)\",\n"
          + "            null);\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration properties for request.P1_ field object instance.<p>\n"
          + "           * P1_ parameter (note the uppercase 'P' and underscore)\n"
          + "           */\n"
          + "          @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "          public static class P1____ {\n"
          + "            \n"
          + "            private P1____(){}\n"
          + "            \n"
          + "            /**\n"
          + "             * Demo configuration property for P1_.subParam field.<p>\n"
          + "             * subParam parameter\n"
          + "             */\n"
          + "            public static final ConfigProperty SUB_PARAM = DefaultConfigProperty.create(\n"
          + "              \"v1.rest.myRestEndpoint.request.P1_.subParam\",\n"
          + "              Type.BIGDECIMAL,\n"
          + "              \"Demo configuration property for P1_.subParam field.<p>\\nsubParam parameter\",\n"
          + "              \"12.35\");\n"
          + "            \n"
          + "            /**\n"
          + "             * Retrieves value of 'subParam' property.\n"
          + "             * @param properties Properties to look for value of 'subParam' property into.\n"
          + "             * @return Value found in properties or default value <i>12.35</i> if not found.\n"
          + "             */\n"
          + "            public static BigDecimal getSubParam(Properties properties) {return PropertiesUtil.getBigDecimal(properties, SUB_PARAM);}\n"
          + "            /**\n"
          + "             * List of all configuration properties defined in this class\n"
          + "             */\n"
          + "            public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "              List.of(\n"
          + "                SUB_PARAM))));\n"
          + "          }\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'p1' property.\n"
          + "           * @param properties Properties to look for value of 'p1' property into.\n"
          + "           * @return Value found in properties or default value <i>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1}</i> if not found.\n"
          + "           */\n"
          + "          public static Integer getp1(Properties properties) {return PropertiesUtil.getInt(properties, P1);}\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'P1' property.\n"
          + "           * @param properties Properties to look for value of 'P1' property into.\n"
          + "           * @return Value found in properties or default value <i>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___#BAR}</i> if not found.\n"
          + "           */\n"
          + "          public static String getP1(Properties properties) {return PropertiesUtil.getString(properties, P1_);}\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'p1_' property.\n"
          + "           * @param properties Properties to look for value of 'p1_' property into.\n"
          + "           * @return Value found in properties or default value <i>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1_}</i> if not found.\n"
          + "           */\n"
          + "          public static Long getp1_(Properties properties) {return PropertiesUtil.getLong(properties, P1__);}\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'P1_' property.\n"
          + "           * @param properties Properties to look for value of 'P1_' property into.\n"
          + "           * @return Value found in properties or <code>null</code> if not found.\n"
          + "           */\n"
          + "          public static String getP1_(Properties properties) {return PropertiesUtil.getString(properties, P1___);}\n"
          + "          /**\n"
          + "           * List of all configuration properties defined in this class\n"
          + "           */\n"
          + "          public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "            List.of(\n"
          + "              P1,\n"
          + "              P1_,\n"
          + "              P1__,\n"
          + "              P1___\n"
          + "            ),\n"
          + "            P1____.ALL)));\n"
          + "        }\n"
          + "        \n"
          + "        /**\n"
          + "         * Retrieves value of 'request' property.\n"
          + "         * @param properties Properties to look for value of 'request' property into.\n"
          + "         * @return Value found in properties or <code>null</code> if not found.\n"
          + "         */\n"
          + "        public static String getRequest(Properties properties) {return PropertiesUtil.getString(properties, REQUEST);}\n"
          + "        /**\n"
          + "         * List of all configuration properties defined in this class\n"
          + "         */\n"
          + "        public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "          List.of(\n"
          + "            REQUEST\n"
          + "          ),\n"
          + "          Request.ALL)));\n"
          + "      }\n"
          + "      /**\n"
          + "       * List of all configuration properties defined in this class\n"
          + "       */\n"
          + "      public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "        MyRestEndpoint.ALL)));\n"
          + "    }\n"
          + "    \n"
          + "    /**\n"
          + "     * Configuration properties for websocket endpoints demo snippets of v1 API group\n"
          + "     */\n"
          + "    @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "    public static class Ws {\n"
          + "      \n"
          + "      private Ws(){}\n"
          + "      \n"
          + "      /**\n"
          + "       * Configuration properties for websocket myWsEndpoint endpoint of v1 API group\n"
          + "       */\n"
          + "      @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "      public static class MyWsEndpoint {\n"
          + "        \n"
          + "        private MyWsEndpoint(){}\n"
          + "        \n"
          + "        /**\n"
          + "         * Demo configuration property for myWsEndpoint.request field as raw JSON string value.\n"
          + "         */\n"
          + "        public static final ConfigProperty REQUEST = DefaultConfigProperty.create(\n"
          + "          \"v1.ws.myWsEndpoint.request\",\n"
          + "          Type.STRING,\n"
          + "          \"Demo configuration property for myWsEndpoint.request field as raw JSON string value.\",\n"
          + "          null);\n"
          + "        \n"
          + "        /**\n"
          + "         * Demo configuration properties for myWsEndpoint.request field object instance.\n"
          + "         */\n"
          + "        @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "        public static class Request {\n"
          + "          \n"
          + "          private Request(){}\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.p1 field.<p>\n"
          + "           * p1 parameter\n"
          + "           */\n"
          + "          public static final ConfigProperty P1 = DefaultConfigProperty.create(\n"
          + "            \"v1.ws.myWsEndpoint.request.p1\",\n"
          + "            Type.INT,\n"
          + "            \"Demo configuration property for request.p1 field.<p>\\np1 parameter\",\n"
          + "            EncodingUtil.substituteArguments(\"${constants.c1}\", \"constants.c1\", ConflictConstants.C1));\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.P1 field.<p>\n"
          + "           * P1 parameter (note the uppercase 'P'). Its  value should be one of the values of the {@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___} constant group\n"
          + "           */\n"
          + "          public static final ConfigProperty P1_ = DefaultConfigProperty.create(\n"
          + "            \"v1.ws.myWsEndpoint.request.P1\",\n"
          + "            Type.STRING,\n"
          + "            \"Demo configuration property for request.P1 field.<p>\\nP1 parameter (note the uppercase 'P'). Its  value should be one of the values of the {@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___} constant group\",\n"
          + "            EncodingUtil.substituteArguments(\"${constants.C1_.bar}\", \"constants.C1_.bar\", ConflictConstants.C1___.BAR));\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.p1_ field.<p>\n"
          + "           * p1_ parameter (note the underscore)\n"
          + "           */\n"
          + "          public static final ConfigProperty P1__ = DefaultConfigProperty.create(\n"
          + "            \"v1.ws.myWsEndpoint.request.p1_\",\n"
          + "            Type.LONG,\n"
          + "            \"Demo configuration property for request.p1_ field.<p>\\np1_ parameter (note the underscore)\",\n"
          + "            EncodingUtil.substituteArguments(\"${constants.c1_}\", \"constants.c1_\", ConflictConstants.C1__));\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration property for request.P1_ field as raw JSON string value.<p>\n"
          + "           * P1_ parameter (note the uppercase 'P' and underscore)\n"
          + "           */\n"
          + "          public static final ConfigProperty P1___ = DefaultConfigProperty.create(\n"
          + "            \"v1.ws.myWsEndpoint.request.P1_\",\n"
          + "            Type.STRING,\n"
          + "            \"Demo configuration property for request.P1_ field as raw JSON string value.<p>\\nP1_ parameter (note the uppercase 'P' and underscore)\",\n"
          + "            null);\n"
          + "          \n"
          + "          /**\n"
          + "           * Demo configuration properties for request.P1_ field object instance.<p>\n"
          + "           * P1_ parameter (note the uppercase 'P' and underscore)\n"
          + "           */\n"
          + "          @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "          public static class P1____ {\n"
          + "            \n"
          + "            private P1____(){}\n"
          + "            \n"
          + "            /**\n"
          + "             * Demo configuration property for P1_.subParam field.<p>\n"
          + "             * subParam parameter\n"
          + "             */\n"
          + "            public static final ConfigProperty SUB_PARAM = DefaultConfigProperty.create(\n"
          + "              \"v1.ws.myWsEndpoint.request.P1_.subParam\",\n"
          + "              Type.BIGDECIMAL,\n"
          + "              \"Demo configuration property for P1_.subParam field.<p>\\nsubParam parameter\",\n"
          + "              \"12.35\");\n"
          + "            \n"
          + "            /**\n"
          + "             * Retrieves value of 'subParam' property.\n"
          + "             * @param properties Properties to look for value of 'subParam' property into.\n"
          + "             * @return Value found in properties or default value <i>12.35</i> if not found.\n"
          + "             */\n"
          + "            public static BigDecimal getSubParam(Properties properties) {return PropertiesUtil.getBigDecimal(properties, SUB_PARAM);}\n"
          + "            /**\n"
          + "             * List of all configuration properties defined in this class\n"
          + "             */\n"
          + "            public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "              List.of(\n"
          + "                SUB_PARAM))));\n"
          + "          }\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'p1' property.\n"
          + "           * @param properties Properties to look for value of 'p1' property into.\n"
          + "           * @return Value found in properties or default value <i>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1}</i> if not found.\n"
          + "           */\n"
          + "          public static Integer getp1(Properties properties) {return PropertiesUtil.getInt(properties, P1);}\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'P1' property.\n"
          + "           * @param properties Properties to look for value of 'P1' property into.\n"
          + "           * @return Value found in properties or default value <i>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants.C1___#BAR}</i> if not found.\n"
          + "           */\n"
          + "          public static String getP1(Properties properties) {return PropertiesUtil.getString(properties, P1_);}\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'p1_' property.\n"
          + "           * @param properties Properties to look for value of 'p1_' property into.\n"
          + "           * @return Value found in properties or default value <i>{@link org.jxapi.exchanges.conflict.gen.ConflictConstants#C1_}</i> if not found.\n"
          + "           */\n"
          + "          public static Long getp1_(Properties properties) {return PropertiesUtil.getLong(properties, P1__);}\n"
          + "          \n"
          + "          /**\n"
          + "           * Retrieves value of 'P1_' property.\n"
          + "           * @param properties Properties to look for value of 'P1_' property into.\n"
          + "           * @return Value found in properties or <code>null</code> if not found.\n"
          + "           */\n"
          + "          public static String getP1_(Properties properties) {return PropertiesUtil.getString(properties, P1___);}\n"
          + "          /**\n"
          + "           * List of all configuration properties defined in this class\n"
          + "           */\n"
          + "          public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "            List.of(\n"
          + "              P1,\n"
          + "              P1_,\n"
          + "              P1__,\n"
          + "              P1___\n"
          + "            ),\n"
          + "            P1____.ALL)));\n"
          + "        }\n"
          + "        \n"
          + "        /**\n"
          + "         * Retrieves value of 'request' property.\n"
          + "         * @param properties Properties to look for value of 'request' property into.\n"
          + "         * @return Value found in properties or <code>null</code> if not found.\n"
          + "         */\n"
          + "        public static String getRequest(Properties properties) {return PropertiesUtil.getString(properties, REQUEST);}\n"
          + "        /**\n"
          + "         * List of all configuration properties defined in this class\n"
          + "         */\n"
          + "        public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "          List.of(\n"
          + "            REQUEST\n"
          + "          ),\n"
          + "          Request.ALL)));\n"
          + "      }\n"
          + "      /**\n"
          + "       * List of all configuration properties defined in this class\n"
          + "       */\n"
          + "      public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "        MyWsEndpoint.ALL)));\n"
          + "    }\n"
          + "    /**\n"
          + "     * List of all configuration properties defined in this class\n"
          + "     */\n"
          + "    public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "      Rest.ALL,\n"
          + "      Ws.ALL)));\n"
          + "  }\n"
          + "  /**\n"
          + "   * List of all configuration properties defined in this class\n"
          + "   */\n"
          + "  public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "    V1.ALL)));\n"
          + "}\n"
          + "", gen.generate());
    }
}
