package org.jxapi.generator.java.exchange.properties;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;
import org.jxapi.exchange.descriptor.ConfigPropertyDescriptor;
import org.jxapi.exchange.descriptor.Constant;
import org.jxapi.exchange.descriptor.ExchangeDescriptor;
import org.jxapi.exchange.descriptor.Type;

/**
 * Unit test for {@link PropertiesClassGenerator}
 */
public class PropertiesClassGeneratorTest {

    @Test
    public void testGenerate_NoGroup() {
        ConfigPropertyDescriptor stringProp = ConfigPropertyDescriptor.create("myString", Type.STRING, "My String property, for instance ${constants.stringPropDefaultValue}", "${constants.stringPropDefaultValue}");
        ConfigPropertyDescriptor stringPropWithNoDescriptionNoDefaultValue = ConfigPropertyDescriptor.create("myStringWithNoDescriptionNoDefaultValue", Type.STRING, null, null);
        ConfigPropertyDescriptor intProp = ConfigPropertyDescriptor.create("myInt", Type.INT, "My int property", "${constants.intPropDefaultValue}");
        ConfigPropertyDescriptor longProp = ConfigPropertyDescriptor.create("myLong", Type.LONG, "My long property", 1234567890123456L);
        ConfigPropertyDescriptor boolProp = ConfigPropertyDescriptor.create("myBool", Type.BOOLEAN, "My boolean property", true);
        ConfigPropertyDescriptor bigDecimalProp = ConfigPropertyDescriptor.create("myBigDecimal", Type.BIGDECIMAL, "My BigDecimal property", 1.2345);
        ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
        exchangeDescriptor.setId("myExchange");
        exchangeDescriptor.setBasePackage("com.x.y.exchange");
        exchangeDescriptor.setDescription("My exchange description");
        Constant c1 = Constant.create("stringPropDefaultValue", Type.STRING, "Sample string value", "fooVal");
        Constant c2 = Constant.create("intPropDefaultValue", Type.INT, "Sample int value", 42);
        exchangeDescriptor.setConstants(List.of(c1, c2));
        PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, 
            List.of(stringProp, 
                stringPropWithNoDescriptionNoDefaultValue, 
                intProp, 
                longProp, 
                boolProp, 
                bigDecimalProp),
            "demo");
        String expected =  "package com.x.y;\n"
            + "\n"
            + "import java.math.BigDecimal;\n"
            + "import java.util.List;\n"
            + "import java.util.Properties;\n"
            + "\n"
            + "import com.x.y.exchange.MyExchangeConstants;\n"
            + "import javax.annotation.processing.Generated;\n"
            + "import org.jxapi.exchange.descriptor.Type;\n"
            + "import org.jxapi.util.CollectionUtil;\n"
            + "import org.jxapi.util.ConfigProperty;\n"
            + "import org.jxapi.util.DefaultConfigProperty;\n"
            + "import org.jxapi.util.EncodingUtil;\n"
            + "import org.jxapi.util.PropertiesUtil;\n"
            + "\n"
            + "/**\n"
            + " * Configurable demo properties for <strong>myExchange</strong> exchange:<br>\n"
            + " * <table>\n"
            + " *   <caption>myExchange properties</caption>\n"
            + " *   <tr>\n"
            + " *     <th>Name</th>\n"
            + " *     <th>Type</th>\n"
            + " *     <th>Description</th>\n"
            + " *     <th>Default value</th>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myString</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td>My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myStringWithNoDescriptionNoDefaultValue</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td></td>\n"
            + " *     <td></td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myInt</td>\n"
            + " *     <td>INT</td>\n"
            + " *     <td>My int property</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myLong</td>\n"
            + " *     <td>LONG</td>\n"
            + " *     <td>My long property</td>\n"
            + " *     <td>1234567890123456</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBool</td>\n"
            + " *     <td>BOOLEAN</td>\n"
            + " *     <td>My boolean property</td>\n"
            + " *     <td>true</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBigDecimal</td>\n"
            + " *     <td>BIGDECIMAL</td>\n"
            + " *     <td>My BigDecimal property</td>\n"
            + " *     <td>1.2345</td>\n"
            + " *   </tr>\n"
            + " * </table>\n"
            + " * <br>\n"
            + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
            + " * @see ConfigProperty\n"
            + " */\n"
            + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "public class MyProperties {\n"
            + "  \n"
            + "  private MyProperties(){}\n"
            + "  \n"
            + "  /**\n"
            + "   * My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_STRING = DefaultConfigProperty.create(\n"
            + "    \"demo.myString\",\n"
            + "    Type.STRING,\n"
            + "    \"My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\",\n"
            + "    EncodingUtil.substituteArguments(\"${constants.stringPropDefaultValue}\", \"constants.stringPropDefaultValue\", MyExchangeConstants.STRING_PROP_DEFAULT_VALUE));\n"
            + "  \n"
            + "  \n"
            + "  public static final ConfigProperty MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE = DefaultConfigProperty.create(\n"
            + "    \"demo.myStringWithNoDescriptionNoDefaultValue\",\n"
            + "    Type.STRING,\n"
            + "    null,\n"
            + "    null);\n"
            + "  \n"
            + "  /**\n"
            + "   * My int property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_INT = DefaultConfigProperty.create(\n"
            + "    \"demo.myInt\",\n"
            + "    Type.INT,\n"
            + "    \"My int property\",\n"
            + "    EncodingUtil.substituteArguments(\"${constants.intPropDefaultValue}\", \"constants.intPropDefaultValue\", MyExchangeConstants.INT_PROP_DEFAULT_VALUE));\n"
            + "  \n"
            + "  /**\n"
            + "   * My long property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_LONG = DefaultConfigProperty.create(\n"
            + "    \"demo.myLong\",\n"
            + "    Type.LONG,\n"
            + "    \"My long property\",\n"
            + "    \"1234567890123456\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My boolean property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BOOL = DefaultConfigProperty.create(\n"
            + "    \"demo.myBool\",\n"
            + "    Type.BOOLEAN,\n"
            + "    \"My boolean property\",\n"
            + "    \"true\");\n"
            + "  \n"
            + "  /**\n"
            + "   * My BigDecimal property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BIG_DECIMAL = DefaultConfigProperty.create(\n"
            + "    \"demo.myBigDecimal\",\n"
            + "    Type.BIGDECIMAL,\n"
            + "    \"My BigDecimal property\",\n"
            + "    \"1.2345\");\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myString' property.\n"
            + "   * @param properties Properties to look for value of 'myString' property into.\n"
            + "   * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "   */\n"
            + "  public static String getMyString(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myStringWithNoDescriptionNoDefaultValue' property.\n"
            + "   * @param properties Properties to look for value of 'myStringWithNoDescriptionNoDefaultValue' property into.\n"
            + "   * @return Value found in properties or <code>null</code> if not found.\n"
            + "   */\n"
            + "  public static String getMyStringWithNoDescriptionNoDefaultValue(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myInt' property.\n"
            + "   * @param properties Properties to look for value of 'myInt' property into.\n"
            + "   * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "   */\n"
            + "  public static Integer getMyInt(Properties properties) {return PropertiesUtil.getInt(properties, MY_INT);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myLong' property.\n"
            + "   * @param properties Properties to look for value of 'myLong' property into.\n"
            + "   * @return Value found in properties or default value <i>1234567890123456</i> if not found.\n"
            + "   */\n"
            + "  public static Long getMyLong(Properties properties) {return PropertiesUtil.getLong(properties, MY_LONG);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBool' property.\n"
            + "   * @param properties Properties to look for value of 'myBool' property into.\n"
            + "   * @return Value found in properties or default value <i>true</i> if not found.\n"
            + "   */\n"
            + "  public static Boolean isMyBool(Properties properties) {return PropertiesUtil.getBoolean(properties, MY_BOOL);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBigDecimal' property.\n"
            + "   * @param properties Properties to look for value of 'myBigDecimal' property into.\n"
            + "   * @return Value found in properties or default value <i>1.2345</i> if not found.\n"
            + "   */\n"
            + "  public static BigDecimal getMyBigDecimal(Properties properties) {return PropertiesUtil.getBigDecimal(properties, MY_BIG_DECIMAL);}\n"
            + "  /**\n"
            + "   * List of all configuration properties defined in this class\n"
            + "   */\n"
            + "  public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "    List.of(\n"
            + "      MY_STRING,\n"
            + "      MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE,\n"
            + "      MY_INT,\n"
            + "      MY_LONG,\n"
            + "      MY_BOOL,\n"
            + "      MY_BIG_DECIMAL))));\n"
            + "}\n"
            + "";
        Assert.assertEquals(expected, gen.generate());
    }
    
    @Test
    public void testGenerate_WithGroups() {
        ConfigPropertyDescriptor stringProp = ConfigPropertyDescriptor.create("myString", Type.STRING, "My String property, for instance ${constants.stringPropDefaultValue}", "${constants.stringPropDefaultValue}");
        ConfigPropertyDescriptor stringPropWithNoDescriptionNoDefaultValue = ConfigPropertyDescriptor.create("myStringWithNoDescriptionNoDefaultValue", Type.STRING, null, null);
        ConfigPropertyDescriptor intProp = ConfigPropertyDescriptor.create("myInt", Type.INT, "My int property", "${constants.intPropDefaultValue}");
        ConfigPropertyDescriptor intListProp = ConfigPropertyDescriptor.create("myIntList", Type.fromTypeName("INT_LIST"), "My int list property", "[1,2,3]");
        ConfigPropertyDescriptor longProp = ConfigPropertyDescriptor.create("myLong", Type.LONG, "My long property", 1234567890123456L);
        ConfigPropertyDescriptor boolProp = ConfigPropertyDescriptor.create("myBool", Type.BOOLEAN, "My boolean property", true);
        ConfigPropertyDescriptor bigDecimalProp = ConfigPropertyDescriptor.create("myBigDecimal", Type.BIGDECIMAL, "My BigDecimal property", 1.2345);
        ConfigPropertyDescriptor groupProp1 = ConfigPropertyDescriptor.createGroup("myGroup1", "My group1 description", List.of(stringPropWithNoDescriptionNoDefaultValue, intProp, intListProp));
        ConfigPropertyDescriptor groupProp21 = ConfigPropertyDescriptor.createGroup("myGroup21", "My group nested in group2 description", List.of(longProp));
        ConfigPropertyDescriptor groupProp2 = ConfigPropertyDescriptor.createGroup("myGroup2", "My group2 description", List.of(groupProp21, boolProp));
        ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
        exchangeDescriptor.setId("myExchange");
        exchangeDescriptor.setBasePackage("com.x.y.exchange");
        exchangeDescriptor.setDescription("My exchange description");
        Constant c1 = Constant.create("stringPropDefaultValue", Type.STRING, "Sample string value", "fooVal");
        Constant c2 = Constant.create("intPropDefaultValue", Type.INT, "Sample int value", 42);
        exchangeDescriptor.setConstants(List.of(c1, c2));
        PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, 
            List.of(stringProp, 
                groupProp1,
                groupProp2,
                bigDecimalProp),
            null);
        String expected =  "package com.x.y;\n"
            + "\n"
            + "import java.math.BigDecimal;\n"
            + "import java.util.List;\n"
            + "import java.util.Properties;\n"
            + "\n"
            + "import com.x.y.exchange.MyExchangeConstants;\n"
            + "import javax.annotation.processing.Generated;\n"
            + "import org.jxapi.exchange.descriptor.Type;\n"
            + "import org.jxapi.util.CollectionUtil;\n"
            + "import org.jxapi.util.ConfigProperty;\n"
            + "import org.jxapi.util.DefaultConfigProperty;\n"
            + "import org.jxapi.util.EncodingUtil;\n"
            + "import org.jxapi.util.PropertiesUtil;\n"
            + "\n"
            + "/**\n"
            + " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
            + " * <table>\n"
            + " *   <caption>myExchange properties</caption>\n"
            + " *   <tr>\n"
            + " *     <th>Name</th>\n"
            + " *     <th>Type</th>\n"
            + " *     <th>Description</th>\n"
            + " *     <th>Default value</th>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myString</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td>My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup1.myStringWithNoDescriptionNoDefaultValue</td>\n"
            + " *     <td>STRING</td>\n"
            + " *     <td></td>\n"
            + " *     <td></td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup1.myInt</td>\n"
            + " *     <td>INT</td>\n"
            + " *     <td>My int property</td>\n"
            + " *     <td>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup1.myIntList</td>\n"
            + " *     <td>INT_LIST</td>\n"
            + " *     <td>My int list property</td>\n"
            + " *     <td>[1,2,3]</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup2.myGroup21.myLong</td>\n"
            + " *     <td>LONG</td>\n"
            + " *     <td>My long property</td>\n"
            + " *     <td>1234567890123456</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myGroup2.myBool</td>\n"
            + " *     <td>BOOLEAN</td>\n"
            + " *     <td>My boolean property</td>\n"
            + " *     <td>true</td>\n"
            + " *   </tr>\n"
            + " *   <tr>\n"
            + " *     <td>myBigDecimal</td>\n"
            + " *     <td>BIGDECIMAL</td>\n"
            + " *     <td>My BigDecimal property</td>\n"
            + " *     <td>1.2345</td>\n"
            + " *   </tr>\n"
            + " * </table>\n"
            + " * <br>\n"
            + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
            + " * @see ConfigProperty\n"
            + " */\n"
            + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "public class MyProperties {\n"
            + "  \n"
            + "  private MyProperties(){}\n"
            + "  \n"
            + "  /**\n"
            + "   * My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_STRING = DefaultConfigProperty.create(\n"
            + "    \"myString\",\n"
            + "    Type.STRING,\n"
            + "    \"My String property, for instance {@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}\",\n"
            + "    EncodingUtil.substituteArguments(\"${constants.stringPropDefaultValue}\", \"constants.stringPropDefaultValue\", MyExchangeConstants.STRING_PROP_DEFAULT_VALUE));\n"
            + "  \n"
            + "  /**\n"
            + "   * My group1 description\n"
            + "   */\n"
            + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "  public static class MyGroup1 {\n"
            + "    \n"
            + "    private MyGroup1(){}\n"
            + "    \n"
            + "    \n"
            + "    public static final ConfigProperty MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE = DefaultConfigProperty.create(\n"
            + "      \"myGroup1.myStringWithNoDescriptionNoDefaultValue\",\n"
            + "      Type.STRING,\n"
            + "      null,\n"
            + "      null);\n"
            + "    \n"
            + "    /**\n"
            + "     * My int property\n"
            + "     */\n"
            + "    public static final ConfigProperty MY_INT = DefaultConfigProperty.create(\n"
            + "      \"myGroup1.myInt\",\n"
            + "      Type.INT,\n"
            + "      \"My int property\",\n"
            + "      EncodingUtil.substituteArguments(\"${constants.intPropDefaultValue}\", \"constants.intPropDefaultValue\", MyExchangeConstants.INT_PROP_DEFAULT_VALUE));\n"
            + "    \n"
            + "    /**\n"
            + "     * My int list property\n"
            + "     */\n"
            + "    public static final ConfigProperty MY_INT_LIST = DefaultConfigProperty.create(\n"
            + "      \"myGroup1.myIntList\",\n"
            + "      Type.STRING,\n"
            + "      \"My int list property\",\n"
            + "      \"[1,2,3]\");\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myStringWithNoDescriptionNoDefaultValue' property.\n"
            + "     * @param properties Properties to look for value of 'myStringWithNoDescriptionNoDefaultValue' property into.\n"
            + "     * @return Value found in properties or <code>null</code> if not found.\n"
            + "     */\n"
            + "    public static String getMyStringWithNoDescriptionNoDefaultValue(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE);}\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myInt' property.\n"
            + "     * @param properties Properties to look for value of 'myInt' property into.\n"
            + "     * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#INT_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "     */\n"
            + "    public static Integer getMyInt(Properties properties) {return PropertiesUtil.getInt(properties, MY_INT);}\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myIntList' property.\n"
            + "     * @param properties Properties to look for value of 'myIntList' property into.\n"
            + "     * @return Value found in properties or default value <i>\"[1,2,3]\"</i> if not found.\n"
            + "     */\n"
            + "    public static String getMyIntList(Properties properties) {return PropertiesUtil.getString(properties, MY_INT_LIST);}\n"
            + "    /**\n"
            + "     * List of all configuration properties defined in this class\n"
            + "     */\n"
            + "    public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "      List.of(\n"
            + "        MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE,\n"
            + "        MY_INT,\n"
            + "        MY_INT_LIST))));\n"
            + "  }\n"
            + "  \n"
            + "  /**\n"
            + "   * My group2 description\n"
            + "   */\n"
            + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "  public static class MyGroup2 {\n"
            + "    \n"
            + "    private MyGroup2(){}\n"
            + "    \n"
            + "    /**\n"
            + "     * My group nested in group2 description\n"
            + "     */\n"
            + "    @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
            + "    public static class MyGroup21 {\n"
            + "      \n"
            + "      private MyGroup21(){}\n"
            + "      \n"
            + "      /**\n"
            + "       * My long property\n"
            + "       */\n"
            + "      public static final ConfigProperty MY_LONG = DefaultConfigProperty.create(\n"
            + "        \"myGroup2.myGroup21.myLong\",\n"
            + "        Type.LONG,\n"
            + "        \"My long property\",\n"
            + "        \"1234567890123456\");\n"
            + "      \n"
            + "      /**\n"
            + "       * Retrieves value of 'myLong' property.\n"
            + "       * @param properties Properties to look for value of 'myLong' property into.\n"
            + "       * @return Value found in properties or default value <i>1234567890123456</i> if not found.\n"
            + "       */\n"
            + "      public static Long getMyLong(Properties properties) {return PropertiesUtil.getLong(properties, MY_LONG);}\n"
            + "      /**\n"
            + "       * List of all configuration properties defined in this class\n"
            + "       */\n"
            + "      public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "        List.of(\n"
            + "          MY_LONG))));\n"
            + "    }\n"
            + "    \n"
            + "    /**\n"
            + "     * My boolean property\n"
            + "     */\n"
            + "    public static final ConfigProperty MY_BOOL = DefaultConfigProperty.create(\n"
            + "      \"myGroup2.myBool\",\n"
            + "      Type.BOOLEAN,\n"
            + "      \"My boolean property\",\n"
            + "      \"true\");\n"
            + "    \n"
            + "    /**\n"
            + "     * Retrieves value of 'myBool' property.\n"
            + "     * @param properties Properties to look for value of 'myBool' property into.\n"
            + "     * @return Value found in properties or default value <i>true</i> if not found.\n"
            + "     */\n"
            + "    public static Boolean isMyBool(Properties properties) {return PropertiesUtil.getBoolean(properties, MY_BOOL);}\n"
            + "    /**\n"
            + "     * List of all configuration properties defined in this class\n"
            + "     */\n"
            + "    public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "      MyGroup21.ALL,\n"
            + "      List.of(\n"
            + "        MY_BOOL))));\n"
            + "  }\n"
            + "  \n"
            + "  /**\n"
            + "   * My BigDecimal property\n"
            + "   */\n"
            + "  public static final ConfigProperty MY_BIG_DECIMAL = DefaultConfigProperty.create(\n"
            + "    \"myBigDecimal\",\n"
            + "    Type.BIGDECIMAL,\n"
            + "    \"My BigDecimal property\",\n"
            + "    \"1.2345\");\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myString' property.\n"
            + "   * @param properties Properties to look for value of 'myString' property into.\n"
            + "   * @return Value found in properties or default value <i>{@link com.x.y.exchange.MyExchangeConstants#STRING_PROP_DEFAULT_VALUE}</i> if not found.\n"
            + "   */\n"
            + "  public static String getMyString(Properties properties) {return PropertiesUtil.getString(properties, MY_STRING);}\n"
            + "  \n"
            + "  /**\n"
            + "   * Retrieves value of 'myBigDecimal' property.\n"
            + "   * @param properties Properties to look for value of 'myBigDecimal' property into.\n"
            + "   * @return Value found in properties or default value <i>1.2345</i> if not found.\n"
            + "   */\n"
            + "  public static BigDecimal getMyBigDecimal(Properties properties) {return PropertiesUtil.getBigDecimal(properties, MY_BIG_DECIMAL);}\n"
            + "  /**\n"
            + "   * List of all configuration properties defined in this class\n"
            + "   */\n"
            + "  public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
            + "    List.of(\n"
            + "      MY_STRING\n"
            + "    ),\n"
            + "    MyGroup1.ALL,\n"
            + "    MyGroup2.ALL,\n"
            + "    List.of(\n"
            + "      MY_BIG_DECIMAL))));\n"
            + "}\n"
            + "";
        Assert.assertEquals(expected, gen.generate());
    }
    
    @Test
    public void testGenerate_EmptyProperties() {
      ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
      exchangeDescriptor.setId("myExchange");
      exchangeDescriptor.setBasePackage("com.x.y.exchange");
      PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, List.of(), "");
      Assert.assertEquals("package com.x.y;\n"
          + "\n"
          + "import java.util.List;\n"
          + "\n"
          + "import javax.annotation.processing.Generated;\n"
          + "import org.jxapi.util.ConfigProperty;\n"
          + "\n"
          + "/**\n"
          + " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
          + " * <table>\n"
          + " *   <caption>myExchange properties</caption>\n"
          + " *   <tr>\n"
          + " *     <th>Name</th>\n"
          + " *     <th>Type</th>\n"
          + " *     <th>Description</th>\n"
          + " *     <th>Default value</th>\n"
          + " *   </tr>\n"
          + " * </table>\n"
          + " * <br>\n"
          + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
          + " * @see ConfigProperty\n"
          + " */\n"
          + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "public class MyProperties {\n"
          + "  \n"
          + "  private MyProperties(){}\n"
          + "  /**\n"
          + "   * List of all configuration properties defined in this class\n"
          + "   */\n"
          + "  public static final List<ConfigProperty> ALL = List.of();\n"
          + "}\n"
          + "", gen.generate());
    }
    
    @Test
    public void testGenerateProperties_WithConflictingPropertyNames() {
      ConfigPropertyDescriptor p1 = ConfigPropertyDescriptor.create("p1", Type.STRING, null, null);
      ConfigPropertyDescriptor p1Up = ConfigPropertyDescriptor.create("P1", Type.STRING, null, null);
      ConfigPropertyDescriptor p1Underscore = ConfigPropertyDescriptor.create("p1_", Type.STRING, null, null);
      ConfigPropertyDescriptor p1UpUnderscore = ConfigPropertyDescriptor.createGroup("P1_", null, List.of());
      List<ConfigPropertyDescriptor> allProps = List.of(p1, p1Up, p1Underscore, p1UpUnderscore);
      ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptor();
      exchangeDescriptor.setId("myExchange");
      exchangeDescriptor.setBasePackage("com.x.y.exchange");
      PropertiesClassGenerator gen = new PropertiesClassGenerator("com.x.y.MyProperties", exchangeDescriptor, allProps, "demo");
      Assert.assertEquals("package com.x.y;\n"
          + "\n"
          + "import java.util.List;\n"
          + "import java.util.Properties;\n"
          + "\n"
          + "import javax.annotation.processing.Generated;\n"
          + "import org.jxapi.exchange.descriptor.Type;\n"
          + "import org.jxapi.util.CollectionUtil;\n"
          + "import org.jxapi.util.ConfigProperty;\n"
          + "import org.jxapi.util.DefaultConfigProperty;\n"
          + "import org.jxapi.util.PropertiesUtil;\n"
          + "\n"
          + "/**\n"
          + " * Configurable demo properties for <strong>myExchange</strong> exchange:<br>\n"
          + " * <table>\n"
          + " *   <caption>myExchange properties</caption>\n"
          + " *   <tr>\n"
          + " *     <th>Name</th>\n"
          + " *     <th>Type</th>\n"
          + " *     <th>Description</th>\n"
          + " *     <th>Default value</th>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>p1</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td></td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>P1</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td></td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " *   <tr>\n"
          + " *     <td>p1_</td>\n"
          + " *     <td>STRING</td>\n"
          + " *     <td></td>\n"
          + " *     <td></td>\n"
          + " *   </tr>\n"
          + " * </table>\n"
          + " * <br>\n"
          + " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties.\n"
          + " * @see ConfigProperty\n"
          + " */\n"
          + "@Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "public class MyProperties {\n"
          + "  \n"
          + "  private MyProperties(){}\n"
          + "  \n"
          + "  \n"
          + "  public static final ConfigProperty P1 = DefaultConfigProperty.create(\n"
          + "    \"demo.p1\",\n"
          + "    Type.STRING,\n"
          + "    null,\n"
          + "    null);\n"
          + "  \n"
          + "  \n"
          + "  public static final ConfigProperty P1_ = DefaultConfigProperty.create(\n"
          + "    \"demo.P1\",\n"
          + "    Type.STRING,\n"
          + "    null,\n"
          + "    null);\n"
          + "  \n"
          + "  \n"
          + "  public static final ConfigProperty P1__ = DefaultConfigProperty.create(\n"
          + "    \"demo.p1_\",\n"
          + "    Type.STRING,\n"
          + "    null,\n"
          + "    null);\n"
          + "  \n"
          + "  \n"
          + "  @Generated(\"org.jxapi.generator.java.exchange.properties.PropertiesClassGenerator\")\n"
          + "  public static class P1___ {\n"
          + "    \n"
          + "    private P1___(){}\n"
          + "    /**\n"
          + "     * List of all configuration properties defined in this class\n"
          + "     */\n"
          + "    public static final List<ConfigProperty> ALL = List.of();\n"
          + "  }\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'p1' property.\n"
          + "   * @param properties Properties to look for value of 'p1' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getp1(Properties properties) {return PropertiesUtil.getString(properties, P1);}\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'P1' property.\n"
          + "   * @param properties Properties to look for value of 'P1' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getP1(Properties properties) {return PropertiesUtil.getString(properties, P1_);}\n"
          + "  \n"
          + "  /**\n"
          + "   * Retrieves value of 'p1_' property.\n"
          + "   * @param properties Properties to look for value of 'p1_' property into.\n"
          + "   * @return Value found in properties or <code>null</code> if not found.\n"
          + "   */\n"
          + "  public static String getp1_(Properties properties) {return PropertiesUtil.getString(properties, P1__);}\n"
          + "  /**\n"
          + "   * List of all configuration properties defined in this class\n"
          + "   */\n"
          + "  public static final List<ConfigProperty> ALL = List.copyOf(CollectionUtil.mergeLists(List.of(\n"
          + "    List.of(\n"
          + "      P1,\n"
          + "      P1_,\n"
          + "      P1__\n"
          + "    ),\n"
          + "    P1_.ALL)));\n"
          + "}\n"
          + "", gen.generate());
    }
}
