package com.scz.jxapi.generator.exchange;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

/**
 * Unit test for {@link ExchangeApiInterfaceImplementationGenerator}
 */
public class ExchangeApiInterfaceImplementationGeneratorTest {

	@Test
	public void testGenerateExchangeApi() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.BarWebsocketEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataTickerStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketMessageTopicMatcherField;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final BarWebsocketEndpointFactory websocketEndpointFactory = new BarWebsocketEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeMarketDataExchangeInfoRequest, MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  private final WebsocketEndpoint<MyTestExchangeMarketDataTickerStreamRequest, MyTestExchangeMarketDataTickerStreamMessage> tickerStreamWs;\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.websocketEndpointFactory.setApi(this);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeMarketDataExchangeInfoResponseDeserializer());\n"
				+ "    this.tickerStreamWs = websocketEndpointFactory.createWebsocketEndpoint(new MyTestExchangeMarketDataTickerStreamMessageDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return exchangeInfoApi.call(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStream(MyTestExchangeMarketDataTickerStreamRequest request, WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStream:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestExchangeMarketDataTickerStreamRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"ticker\", \"symbol\", \"\" + request.getSymbol() + \"\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return tickerStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithGlobalRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(1);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.trading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.trading.deserializers.MyTestExchangeTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.trading.pojo.MyTestExchangeTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.trading.pojo.MyTestExchangeTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeTradingApiImpl implements MyTestExchangeTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"globalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_TRADING1 = RateLimitRule.createRule(\"Trading1\", 10000, 250);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(RATE_LIMIT_GLOBAL_WEIGHT_RULE, RATE_LIMIT_TRADING1);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler = new RequestThrottler(\"MyTestExchangeTrading\");\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeTradingExchangeInfoRequest, MyTestExchangeTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeTradingApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(2);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futuresmarketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.deserializers.MyTestExchangeFuturesMarketDataExchangeInfo2ResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.deserializers.MyTestExchangeFuturesMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfo2Request;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfo2Response;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesMarketDataApiImpl implements MyTestExchangeFuturesMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT = RateLimitRule.createRule(\"exchangeInfoRateLimit\", 3000, 30);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO2_API = List.of(RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler = new RequestThrottler(\"MyTestExchangeFuturesMarketData\");\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesMarketDataExchangeInfoRequest, MyTestExchangeFuturesMarketDataExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesMarketDataExchangeInfo2Request, MyTestExchangeFuturesMarketDataExchangeInfo2Response> exchangeInfo2Api;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesMarketDataExchangeInfoResponseDeserializer());\n"
				+ "    this.exchangeInfo2Api = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesMarketDataExchangeInfo2ResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesMarketDataExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesMarketDataExchangeInfo2Response> exchangeInfo2(MyTestExchangeFuturesMarketDataExchangeInfo2Request request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo2 > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo2\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO2_API), exchangeInfo2Api);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithBothApiGlobalAndEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(3);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"globalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_FUTURES_TRADING1 = RateLimitRule.createRule(\"FuturesTrading1\", 10000, 250);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO1 = RateLimitRule.createRule(\"exchangeInfo1\", 3000, 30);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_CUSTOM_RULE = RateLimitRule.createWeightedRule(\"customRule\", 1500, 300);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(RATE_LIMIT_GLOBAL_WEIGHT_RULE, RATE_LIMIT_FUTURES_TRADING1, RATE_LIMIT_EXCHANGE_INFO1, RATE_LIMIT_CUSTOM_RULE);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler = new RequestThrottler(\"MyTestExchangeFuturesTrading\");\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesTradingExchangeInfoRequest, MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithBothExchangeGlobalAndApiGlobalAndEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestWithRateLimitRulesAtExchangeLevelDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_API_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"apiGlobalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_FUTURES_TRADING1 = RateLimitRule.createRule(\"FuturesTrading1\", 10000, 250);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO1 = RateLimitRule.createRule(\"exchangeInfo1\", 3000, 30);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_CUSTOM_RULE = RateLimitRule.createWeightedRule(\"customRule\", 1500, 300);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(MyTestExchangeExchangeImpl.RATE_LIMIT_EXCHANGE_GLOBAL_RULE, RATE_LIMIT_API_GLOBAL_WEIGHT_RULE, RATE_LIMIT_FUTURES_TRADING1, RATE_LIMIT_EXCHANGE_INFO1, RATE_LIMIT_CUSTOM_RULE);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesTradingExchangeInfoRequest, MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(Properties properties, RequestThrottler requestThrottler) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.requestThrottler = requestThrottler;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testExchangeApiInterfaceImplementationGeneratorTestOnlyExchangeLevelWeightedLimitRateRuleExchangeDescriptor() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestOnlyExchangeLevelWeightedLimitRateRuleExchangeDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(MyTestExchangeExchangeImpl.RATE_LIMIT_EXCHANGE_GLOBAL_RULE);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesTradingExchangeInfoRequest, MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(Properties properties, RequestThrottler requestThrottler) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.requestThrottler = requestThrottler;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoWsEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoWebsocketEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestCEXMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestCEXMarketDataApiImpl implements MyTestCEXMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestCEXMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataExchangeInfoRequest, MyTestCEXMarketDataExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestCEXMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestCEXMarketDataExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestCEXMarketDataExchangeInfoResponse> exchangeInfo(MyTestCEXMarketDataExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return exchangeInfoApi.call(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoRestEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoRestEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarWebsocketEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataTickerStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketMessageTopicMatcherField;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestCEXMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestCEXMarketDataApiImpl implements MyTestCEXMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestCEXMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarWebsocketEndpointFactory websocketEndpointFactory = new BarWebsocketEndpointFactory();\n"
				+ "  private final WebsocketEndpoint<MyTestCEXMarketDataTickerStreamRequest, MyTestCEXMarketDataTickerStreamMessage> tickerStreamWs;\n"
				+ "  \n"
				+ "  public MyTestCEXMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.websocketEndpointFactory.setApi(this);\n"
				+ "    this.tickerStreamWs = websocketEndpointFactory.createWebsocketEndpoint(new MyTestCEXMarketDataTickerStreamMessageDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStream(MyTestCEXMarketDataTickerStreamRequest request, WebsocketListener<MyTestCEXMarketDataTickerStreamMessage> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStream:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestCEXMarketDataTickerStreamRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"ticker\", \"symbol\", \"\" + request.getSymbol() + \"\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return tickerStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificResponseDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.BarWebsocketEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataGetRestResponseDataTypeObjectResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataSubscribeTickerMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataSubscribeTickertMapListStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeBigDecimalRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeBooleanRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeIntListRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeIntRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeLongRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeObjectRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeObjectResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeStringRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataSubscribeTickerMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataSubscribeTickerRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataSubscribeTickertMapListStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataSubscribeTickertMapListStreamRequest;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawBigDecimalMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawBooleanMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawIntegerMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawLongMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawStringMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.IntegerJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.MapJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketMessageTopicMatcherField;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestCEXMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestCEXMarketDataApiImpl implements MyTestCEXMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestCEXMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final BarWebsocketEndpointFactory websocketEndpointFactory = new BarWebsocketEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeIntRequest, Integer> getRestResponseDataTypeIntApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeLongRequest, Long> getRestResponseDataTypeLongApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeBigDecimalRequest, BigDecimal> getRestResponseDataTypeBigDecimalApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeStringRequest, String> getRestResponseDataTypeStringApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeBooleanRequest, Boolean> getRestResponseDataTypeBooleanApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeObjectRequest, MyTestCEXMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObjectApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeIntListRequest, List<Integer>> getRestResponseDataTypeIntListApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapRequest, Map<String, List<MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMapApi;\n"
				+ "  private final WebsocketEndpoint<MyTestCEXMarketDataSubscribeTickerRequest, MyTestCEXMarketDataSubscribeTickerMessage> subscribeTickerWs;\n"
				+ "  private final WebsocketEndpoint<MyTestCEXMarketDataSubscribeTickertMapListStreamRequest, List<Map<String, MyTestCEXMarketDataSubscribeTickertMapListStreamMessage>>> subscribeTickertMapListStreamWs;\n"
				+ "  \n"
				+ "  public MyTestCEXMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.websocketEndpointFactory.setApi(this);\n"
				+ "    this.getRestResponseDataTypeIntApi = restEndpointFactory.createRestEndpoint(RawIntegerMessageDeserializer.getInstance());\n"
				+ "    this.getRestResponseDataTypeLongApi = restEndpointFactory.createRestEndpoint(RawLongMessageDeserializer.getInstance());\n"
				+ "    this.getRestResponseDataTypeBigDecimalApi = restEndpointFactory.createRestEndpoint(RawBigDecimalMessageDeserializer.getInstance());\n"
				+ "    this.getRestResponseDataTypeStringApi = restEndpointFactory.createRestEndpoint(RawStringMessageDeserializer.getInstance());\n"
				+ "    this.getRestResponseDataTypeBooleanApi = restEndpointFactory.createRestEndpoint(RawBooleanMessageDeserializer.getInstance());\n"
				+ "    this.getRestResponseDataTypeObjectApi = restEndpointFactory.createRestEndpoint(new MyTestCEXMarketDataGetRestResponseDataTypeObjectResponseDeserializer());\n"
				+ "    this.getRestResponseDataTypeIntListApi = restEndpointFactory.createRestEndpoint(new ListJsonFieldDeserializer<>(IntegerJsonFieldDeserializer.getInstance()));\n"
				+ "    this.getRestResponseDataTypeObjectListMapApi = restEndpointFactory.createRestEndpoint(new MapJsonFieldDeserializer<>(new ListJsonFieldDeserializer<>(new MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponseDeserializer())));\n"
				+ "    this.subscribeTickerWs = websocketEndpointFactory.createWebsocketEndpoint(new MyTestCEXMarketDataSubscribeTickerMessageDeserializer());\n"
				+ "    this.subscribeTickertMapListStreamWs = websocketEndpointFactory.createWebsocketEndpoint(new ListJsonFieldDeserializer<>(new MapJsonFieldDeserializer<>(new MyTestCEXMarketDataSubscribeTickertMapListStreamMessageDeserializer())));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Integer> getRestResponseDataTypeInt(MyTestCEXMarketDataGetRestResponseDataTypeIntRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeInt > \" + request);\n"
				+ "    return getRestResponseDataTypeIntApi.call(RestRequest.create(\"https://com.sample.mycex/getInt\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Long> getRestResponseDataTypeLong(MyTestCEXMarketDataGetRestResponseDataTypeLongRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeLong > \" + request);\n"
				+ "    return getRestResponseDataTypeLongApi.call(RestRequest.create(\"https://com.sample.mycex/getLong\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<BigDecimal> getRestResponseDataTypeBigDecimal(MyTestCEXMarketDataGetRestResponseDataTypeBigDecimalRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeBigDecimal > \" + request);\n"
				+ "    return getRestResponseDataTypeBigDecimalApi.call(RestRequest.create(\"https://com.sample.mycex/getBigDecimal\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<String> getRestResponseDataTypeString(MyTestCEXMarketDataGetRestResponseDataTypeStringRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeString > \" + request);\n"
				+ "    return getRestResponseDataTypeStringApi.call(RestRequest.create(\"https://com.sample.mycex/getString\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Boolean> getRestResponseDataTypeBoolean(MyTestCEXMarketDataGetRestResponseDataTypeBooleanRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeBoolean > \" + request);\n"
				+ "    return getRestResponseDataTypeBooleanApi.call(RestRequest.create(\"https://com.sample.mycex/getBigDecimal\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestCEXMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObject(MyTestCEXMarketDataGetRestResponseDataTypeObjectRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeObject > \" + request);\n"
				+ "    return getRestResponseDataTypeObjectApi.call(RestRequest.create(\"https://com.sample.mycex/getBigDecimal\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<List<Integer>> getRestResponseDataTypeIntList(MyTestCEXMarketDataGetRestResponseDataTypeIntListRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeIntList > \" + request);\n"
				+ "    return getRestResponseDataTypeIntListApi.call(RestRequest.create(\"https://com.sample.mycex/getBigDecimal\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Map<String, List<MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMap(MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeObjectListMap > \" + request);\n"
				+ "    return getRestResponseDataTypeObjectListMapApi.call(RestRequest.create(\"https://com.sample.mycex/getBigDecimal\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeSubscribeTicker(MyTestCEXMarketDataSubscribeTickerRequest request, WebsocketListener<MyTestCEXMarketDataSubscribeTickerMessage> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeSubscribeTicker:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestCEXMarketDataSubscribeTickerRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"tickerMapList\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return subscribeTickerWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeSubscribeTicker(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeSubscribeTicker: subscriptionId:\" + subscriptionId);\n"
				+ "    return subscribeTickerWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeSubscribeTickertMapListStream(MyTestCEXMarketDataSubscribeTickertMapListStreamRequest request, WebsocketListener<List<Map<String, MyTestCEXMarketDataSubscribeTickertMapListStreamMessage>>> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeSubscribeTickertMapListStream:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestCEXMarketDataSubscribeTickertMapListStreamRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"tickerMapList\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return subscribeTickertMapListStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeSubscribeTickertMapListStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeSubscribeTickertMapListStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return subscribeTickertMapListStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificRequestDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.BarWebsocketEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.GenericResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.TickerDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataPostRestRequestDataTypeObjectListMapRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataPostRestRequestDataTypeObjectNoParametersRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataStreamWithObjectListMapRequestDataTypeRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataStreamWithObjectRequestDataTypeOneParameterRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataStreamWithObjectRequestDataTypeZeroParametersRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketMessageTopicMatcherField;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestCEXMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestCEXMarketDataApiImpl implements MyTestCEXMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestCEXMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final BarWebsocketEndpointFactory websocketEndpointFactory = new BarWebsocketEndpointFactory();\n"
				+ "  private final RestEndpoint<Integer, GenericResponse> postRestRequestDataTypeIntApi;\n"
				+ "  private final RestEndpoint<Long, GenericResponse> postRestRequestDataTypeLongApi;\n"
				+ "  private final RestEndpoint<BigDecimal, GenericResponse> postRestRequestDataTypeBigDecimalApi;\n"
				+ "  private final RestEndpoint<String, GenericResponse> postRestRequestDataTypeStringApi;\n"
				+ "  private final RestEndpoint<Boolean, GenericResponse> postRestRequestDataTypeBooleanApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataPostRestRequestDataTypeObjectNoParametersRequest, GenericResponse> postRestRequestDataTypeObjectNoParametersApi;\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataPostRestRequestDataTypeObjectNoParametersRequest, GenericResponse> postRestRequestDataTypeObjectNoParametersApi;\n"
				+ "  private final RestEndpoint<List<Integer>, GenericResponse> postRestRequestDataTypeIntListApi;\n"
				+ "  private final RestEndpoint<Map<String, List<MyTestCEXMarketDataPostRestRequestDataTypeObjectListMapRequest>>, GenericResponse> postRestRequestDataTypeObjectListMapApi;\n"
				+ "  private final WebsocketEndpoint<MyTestCEXMarketDataStreamWithObjectRequestDataTypeZeroParametersRequest, Ticker> streamWithObjectRequestDataTypeZeroParametersWs;\n"
				+ "  private final WebsocketEndpoint<MyTestCEXMarketDataStreamWithObjectRequestDataTypeOneParameterRequest, Ticker> streamWithObjectRequestDataTypeOneParameterWs;\n"
				+ "  private final WebsocketEndpoint<Integer, Ticker> streamWithIntRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Long, Ticker> streamWithLongRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Long, Ticker> streamWithBigDecimalRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<String, Ticker> streamWithStringRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Boolean, Ticker> streamWithBooleanRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<List<String>, Ticker> streamWithStringListRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Map<String, List<MyTestCEXMarketDataStreamWithObjectListMapRequestDataTypeRequest>>, Ticker> streamWithObjectListMapRequestDataTypeWs;\n"
				+ "  \n"
				+ "  public MyTestCEXMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.websocketEndpointFactory.setApi(this);\n"
				+ "    this.postRestRequestDataTypeIntApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeLongApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeBigDecimalApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeStringApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeBooleanApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeObjectNoParametersApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeObjectNoParametersApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeIntListApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.postRestRequestDataTypeObjectListMapApi = restEndpointFactory.createRestEndpoint(new GenericResponseDeserializer());\n"
				+ "    this.streamWithObjectRequestDataTypeZeroParametersWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithObjectRequestDataTypeOneParameterWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithIntRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithLongRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithBigDecimalRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithStringRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithBooleanRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithStringListRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "    this.streamWithObjectListMapRequestDataTypeWs = websocketEndpointFactory.createWebsocketEndpoint(new TickerDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeInt(Integer request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeInt > \" + request);\n"
				+ "    return postRestRequestDataTypeIntApi.call(RestRequest.create(\"https://com.sample.mycex/postInt\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeLong(Long request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeLong > \" + request);\n"
				+ "    return postRestRequestDataTypeLongApi.call(RestRequest.create(\"https://com.sample.mycex/postLong\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeBigDecimal(BigDecimal request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeBigDecimal > \" + request);\n"
				+ "    return postRestRequestDataTypeBigDecimalApi.call(RestRequest.create(\"https://com.sample.mycex/postBigDecimal\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeString(String request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeString > \" + request);\n"
				+ "    return postRestRequestDataTypeStringApi.call(RestRequest.create(\"https://com.sample.mycex/postString\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeBoolean(Boolean request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeBoolean > \" + request);\n"
				+ "    return postRestRequestDataTypeBooleanApi.call(RestRequest.create(\"https://com.sample.mycex/postBoolean\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectNoParameters(MyTestCEXMarketDataPostRestRequestDataTypeObjectNoParametersRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeObjectNoParameters > \" + request);\n"
				+ "    return postRestRequestDataTypeObjectNoParametersApi.call(RestRequest.create(\"https://com.sample.mycex/postBigDecimal\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectNoParameters(MyTestCEXMarketDataPostRestRequestDataTypeObjectNoParametersRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeObjectNoParameters > \" + request);\n"
				+ "    return postRestRequestDataTypeObjectNoParametersApi.call(RestRequest.create(\"https://com.sample.mycex/postBigDecimal\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeIntList(List<Integer> request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeIntList > \" + request);\n"
				+ "    return postRestRequestDataTypeIntListApi.call(RestRequest.create(\"https://com.sample.mycex/postBigDecimal\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectListMap(Map<String, List<MyTestCEXMarketDataPostRestRequestDataTypeObjectListMapRequest>> request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeObjectListMap > \" + request);\n"
				+ "    return postRestRequestDataTypeObjectListMapApi.call(RestRequest.create(\"https://com.sample.mycex/postBigDecimal\", \"POST\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithObjectRequestDataTypeZeroParameters(MyTestCEXMarketDataStreamWithObjectRequestDataTypeZeroParametersRequest request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithObjectRequestDataTypeZeroParameters:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestCEXMarketDataStreamWithObjectRequestDataTypeZeroParametersRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithObjectRequestDataTypeZeroParametersTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithObjectRequestDataTypeZeroParametersWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithObjectRequestDataTypeZeroParameters(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithObjectRequestDataTypeZeroParameters: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithObjectRequestDataTypeZeroParametersWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithObjectRequestDataTypeOneParameter(MyTestCEXMarketDataStreamWithObjectRequestDataTypeOneParameterRequest request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithObjectRequestDataTypeOneParameter:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestCEXMarketDataStreamWithObjectRequestDataTypeOneParameterRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithObjectRequestDataTypeZeroParametersTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithObjectRequestDataTypeOneParameterWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithObjectRequestDataTypeOneParameter(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithObjectRequestDataTypeOneParameter: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithObjectRequestDataTypeOneParameterWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithIntRequestDataType(Integer request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithIntRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<Integer> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithIntRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithIntRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithIntRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithIntRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithIntRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithLongRequestDataType(Long request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithLongRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<Long> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithLongRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithLongRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithLongRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithLongRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithLongRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithBigDecimalRequestDataType(Long request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithBigDecimalRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<Long> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithBigDecimalRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithBigDecimalRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithBigDecimalRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithBigDecimalRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithBigDecimalRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithStringRequestDataType(String request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithStringRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<String> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithStringRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithStringRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithStringRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithStringRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithStringRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithBooleanRequestDataType(Boolean request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithBooleanRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<Boolean> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithBooleanRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithBooleanRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithBooleanRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithBooleanRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithBooleanRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithStringListRequestDataType(List<String> request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithStringListRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<List<String>> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithBooleanRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithStringListRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithStringListRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithStringListRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithStringListRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithObjectListMapRequestDataType(Map<String, List<MyTestCEXMarketDataStreamWithObjectListMapRequestDataTypeRequest>> request, WebsocketListener<Ticker> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithObjectListMapRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<Map<String, List<MyTestCEXMarketDataStreamWithObjectListMapRequestDataTypeRequest>>> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"streamWithObjectListMapRequestDataTypeTopic\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return streamWithObjectListMapRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithObjectListMapRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithObjectListMapRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithObjectListMapRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
}
