package com.scz.jxapi.generator.exchange;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;


/**
 * Unit test for {@link ExchangeApiInterfaceGenerator}
 */
public class ExchangeApiInterfaceGeneratorTest {

	@Test
	public void testGenerateExchangeApi() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testCEXDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickersResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.HasProperties;\n"
				+ "\n"
				+ "/**\n"
				+ " * MarketData CEX MarketData API</br>\n"
				+ " * The market data API of MyTestCEX\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestCEXMarketDataApi extends HasProperties {\n"
				+ "  /**\n"
				+ "   * Fetch market information of symbols that can be traded\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestCEXMarketDataExchangeInfoResponse> exchangeInfo(MyTestCEXMarketDataExchangeInfoRequest request);\n"
				+ "  /**\n"
				+ "   * Fetch current tickers\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestCEXMarketDataTickersResponse> tickers();\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to tickerStream stream.<br/>\n"
				+ "   * Subscribe to ticker stream\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeTickerStream(MyTestCEXMarketDataTickerStreamRequest request, WebsocketListener<MyTestCEXMarketDataTickerStreamMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from tickerStream stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeTickerStream()\n"
				+ "   */\n"
				+ "  boolean unsubscribeTickerStream(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoWsEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoWebsocketEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.util.HasProperties;\n"
				+ "\n"
				+ "/**\n"
				+ " * MarketData CEX MarketData API</br>\n"
				+ " * The market data API of MyTestCEX, , with only 1 REST endpoint and no websocket endpoint\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestCEXMarketDataApi extends HasProperties {\n"
				+ "  /**\n"
				+ "   * Fetch market information of symbols that can be traded\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestCEXMarketDataExchangeInfoResponse> exchangeInfo(MyTestCEXMarketDataExchangeInfoRequest request);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoRestEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoRestEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.HasProperties;\n"
				+ "\n"
				+ "/**\n"
				+ " * MarketData CEX MarketData API</br>\n"
				+ " * The market data API of MyTestCEX\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestCEXMarketDataApi extends HasProperties {\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to tickerStream stream.<br/>\n"
				+ "   * Subscribe to ticker stream\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeTickerStream(MyTestCEXMarketDataTickerStreamRequest request, WebsocketListener<MyTestCEXMarketDataTickerStreamMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from tickerStream stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeTickerStream()\n"
				+ "   */\n"
				+ "  boolean unsubscribeTickerStream(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificResponseDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataGetRestResponseDataTypeObjectResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataSubscribeTickerMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataSubscribeTickertMapListStreamMessage;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.HasProperties;\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "\n"
				+ "/**\n"
				+ " * MarketData CEX MarketData API</br>\n"
				+ " * The market data API of MyTestCEX, , with different response data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestCEXMarketDataApi extends HasProperties {\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT response data type\n"
				+ "   * @return A random int\n"
				+ "   */\n"
				+ "  FutureRestResponse<Integer> getRestResponseDataTypeInt();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using LONG response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<Long> getRestResponseDataTypeLong();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BIGDECIMAL response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<BigDecimal> getRestResponseDataTypeBigDecimal();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using STRING response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<String> getRestResponseDataTypeString();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BOOLEAN response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<Boolean> getRestResponseDataTypeBoolean();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT response data type (default type, explicit here)\n"
				+ "   */\n"
				+ "  FutureRestResponse<MyTestCEXMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObject();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT_LIST response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<List<Integer>> getRestResponseDataTypeIntList();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT_LIST_MAP response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<Map<String, List<MyTestCEXMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMap();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using empty response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<String> getRestEmptyResponseDataType();\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to subscribeTicker stream.<br/>\n"
				+ "   * Subscribe to stream with OBJECT message type (default, explicit here)\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeSubscribeTicker(WebsocketListener<MyTestCEXMarketDataSubscribeTickerMessage> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from subscribeTicker stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeSubscribeTicker()\n"
				+ "   */\n"
				+ "  boolean unsubscribeSubscribeTicker(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to subscribeTickertMapListStream stream.<br/>\n"
				+ "   * Subscribe to stream with OBJECT_MAP_LIST message type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeSubscribeTickertMapListStream(WebsocketListener<List<Map<String, MyTestCEXMarketDataSubscribeTickertMapListStreamMessage>>> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from subscribeTickertMapListStream stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeSubscribeTickertMapListStream()\n"
				+ "   */\n"
				+ "  boolean unsubscribeSubscribeTickertMapListStream(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificRequestDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceGenerator apiInterfaceGenerator = new ExchangeApiInterfaceGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataPostRestRequestDataTypeObjectOneParameterRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.util.HasProperties;\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "\n"
				+ "/**\n"
				+ " * MarketData CEX MarketData API</br>\n"
				+ " * The market data API of MyTestCEX, , with different request data types for websocket and REST endpoints. Remark: Only OBJECT (default) and STRING are usually used, but any data type is supported\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public interface MyTestCEXMarketDataApi extends HasProperties {\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeInt(Integer request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using LONG response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeLong(Long request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BIGDECIMAL response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeBigDecimal(BigDecimal request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using STRING response data type\n"
				+ "   * @param hello Say Hi!\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeString(String hello);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using BOOLEAN response data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeBoolean(Boolean request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT request data type (implicit), and no parameters\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectNoParameters();\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT request data type (default, explicit here), and one parameter\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectOneParameter(MyTestCEXMarketDataPostRestRequestDataTypeObjectOneParameterRequest request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using INT_LIST request data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeIntList(List<Integer> request);\n"
				+ "  /**\n"
				+ "   * A sample REST endpoint using OBJECT_LIST_MAP request data type\n"
				+ "   */\n"
				+ "  FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectListMap(Map<String, List<SingleSymbol>> request);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithObjectRequestDataTypeZeroParameters stream.<br/>\n"
				+ "   * Subscribe to stream with OBJECT request type (implicit) and no parameters\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithObjectRequestDataTypeZeroParameters(WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithObjectRequestDataTypeZeroParameters stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithObjectRequestDataTypeZeroParameters()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithObjectRequestDataTypeZeroParameters(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithObjectRequestDataTypeOneParameter stream.<br/>\n"
				+ "   * Subscribe to stream with OBJECT request type (default, explicit here) and parameter\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithObjectRequestDataTypeOneParameter(SingleSymbol request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithObjectRequestDataTypeOneParameter stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithObjectRequestDataTypeOneParameter()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithObjectRequestDataTypeOneParameter(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithIntRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with INT request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithIntRequestDataType(Integer request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithIntRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithIntRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithIntRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithLongRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with LONG request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithLongRequestDataType(Long request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithLongRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithLongRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithLongRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithBigDecimalRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with BIGDECIMAL request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithBigDecimalRequestDataType(BigDecimal request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithBigDecimalRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithBigDecimalRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithBigDecimalRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithStringRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with STRING request type\n"
				+ "   * \n"
				+ "   * @param request Market symbol\n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithStringRequestDataType(String request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithStringRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithStringRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithStringRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithBooleanRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with BOOLEAN request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithBooleanRequestDataType(Boolean request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithBooleanRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithBooleanRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithBooleanRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithStringListRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with STRING_LIST request type\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithStringListRequestDataType(List<String> request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithStringListRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithStringListRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithStringListRequestDataType(String subscriptionId);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Subscribe to streamWithObjectListMapRequestDataType stream.<br/>\n"
				+ "   * Subscribe to stream with OBJECT_LIST_MAP request type. The objectName field is set to a name already defined in other API definition.\n"
				+ "   * \n"
				+ "   * @return client subscriptionId to use for unsubscription\n"
				+ "   */\n"
				+ "  String subscribeStreamWithObjectListMapRequestDataType(Map<String, List<SingleSymbol>> request, WebsocketListener<Ticker> listener);\n"
				+ "  \n"
				+ "  /**\n"
				+ "   * Unsubscribe from streamWithObjectListMapRequestDataType stream.\n"
				+ "   * \n"
				+ "   * @param subscriptionId ID of subscription returned by #subscribeStreamWithObjectListMapRequestDataType()\n"
				+ "   */\n"
				+ "  boolean unsubscribeStreamWithObjectListMapRequestDataType(String subscriptionId);\n"
				+ "}\n", 
				apiInterfaceGenerator.generate());
	}
}
