package com.scz.jxapi.generator.exchange;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

/**
 * Unit test for {@link ExchangeApiInterfaceImplementationGenerator}
 */
public class ExchangeApiInterfaceImplementationGeneratorTest {

	@Test
	public void testGenerateExchangeApi() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.BarWebsocketEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataTickerStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketMessageTopicMatcherField;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final BarWebsocketEndpointFactory websocketEndpointFactory = new BarWebsocketEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeMarketDataExchangeInfoRequest, MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  private final WebsocketEndpoint<MyTestExchangeMarketDataTickerStreamRequest, MyTestExchangeMarketDataTickerStreamMessage> tickerStreamWs;\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.websocketEndpointFactory.setApi(this);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeMarketDataExchangeInfoResponseDeserializer());\n"
				+ "    this.tickerStreamWs = websocketEndpointFactory.createWebsocketEndpoint(new MyTestExchangeMarketDataTickerStreamMessageDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return exchangeInfoApi.call(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStream(MyTestExchangeMarketDataTickerStreamRequest request, WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStream:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestExchangeMarketDataTickerStreamRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"ticker\", \"symbol\", \"\" + request.getSymbol() + \"\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return tickerStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithGlobalRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(1);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.trading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.trading.deserializers.MyTestExchangeTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.trading.pojo.MyTestExchangeTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.trading.pojo.MyTestExchangeTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeTradingApiImpl implements MyTestExchangeTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"globalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_TRADING1 = RateLimitRule.createRule(\"Trading1\", 10000, 250);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(RATE_LIMIT_GLOBAL_WEIGHT_RULE, RATE_LIMIT_TRADING1);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler = new RequestThrottler(\"MyTestExchangeTrading\");\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeTradingExchangeInfoRequest, MyTestExchangeTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeTradingApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(2);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futuresmarketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.deserializers.MyTestExchangeFuturesMarketDataExchangeInfo2ResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.deserializers.MyTestExchangeFuturesMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfo2Request;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfo2Response;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesMarketDataApiImpl implements MyTestExchangeFuturesMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT = RateLimitRule.createRule(\"exchangeInfoRateLimit\", 3000, 30);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO2_API = List.of(RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler = new RequestThrottler(\"MyTestExchangeFuturesMarketData\");\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesMarketDataExchangeInfoRequest, MyTestExchangeFuturesMarketDataExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesMarketDataExchangeInfo2Request, MyTestExchangeFuturesMarketDataExchangeInfo2Response> exchangeInfo2Api;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesMarketDataExchangeInfoResponseDeserializer());\n"
				+ "    this.exchangeInfo2Api = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesMarketDataExchangeInfo2ResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesMarketDataExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesMarketDataExchangeInfo2Response> exchangeInfo2(MyTestExchangeFuturesMarketDataExchangeInfo2Request request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo2 > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo2\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO2_API), exchangeInfo2Api);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithBothApiGlobalAndEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(3);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"globalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_FUTURES_TRADING1 = RateLimitRule.createRule(\"FuturesTrading1\", 10000, 250);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO1 = RateLimitRule.createRule(\"exchangeInfo1\", 3000, 30);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_CUSTOM_RULE = RateLimitRule.createWeightedRule(\"customRule\", 1500, 300);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(RATE_LIMIT_GLOBAL_WEIGHT_RULE, RATE_LIMIT_FUTURES_TRADING1, RATE_LIMIT_EXCHANGE_INFO1, RATE_LIMIT_CUSTOM_RULE);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler = new RequestThrottler(\"MyTestExchangeFuturesTrading\");\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesTradingExchangeInfoRequest, MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithBothExchangeGlobalAndApiGlobalAndEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestWithRateLimitRulesAtExchangeLevelDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_API_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"apiGlobalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_FUTURES_TRADING1 = RateLimitRule.createRule(\"FuturesTrading1\", 10000, 250);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO1 = RateLimitRule.createRule(\"exchangeInfo1\", 3000, 30);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_CUSTOM_RULE = RateLimitRule.createWeightedRule(\"customRule\", 1500, 300);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(MyTestExchangeExchangeImpl.RATE_LIMIT_EXCHANGE_GLOBAL_RULE, RATE_LIMIT_API_GLOBAL_WEIGHT_RULE, RATE_LIMIT_FUTURES_TRADING1, RATE_LIMIT_EXCHANGE_INFO1, RATE_LIMIT_CUSTOM_RULE);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesTradingExchangeInfoRequest, MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(Properties properties, RequestThrottler requestThrottler) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.requestThrottler = requestThrottler;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testExchangeApiInterfaceImplementationGeneratorTestOnlyExchangeLevelWeightedLimitRateRuleExchangeDescriptor() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestOnlyExchangeLevelWeightedLimitRateRuleExchangeDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO_API = List.of(MyTestExchangeExchangeImpl.RATE_LIMIT_EXCHANGE_GLOBAL_RULE);\n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final RequestThrottler requestThrottler;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestExchangeFuturesTradingExchangeInfoRequest, MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(Properties properties, RequestThrottler requestThrottler) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.requestThrottler = requestThrottler;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return requestThrottler.submit(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request, RATE_LIMITS_EXCHANGE_INFO_API, 60), exchangeInfoApi);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoWsEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoWebsocketEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarRestEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.RestEndpoint;\n"
				+ "import com.scz.jxapi.netutils.rest.RestRequest;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestCEXMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestCEXMarketDataApiImpl implements MyTestCEXMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestCEXMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarRestEndpointFactory restEndpointFactory = new BarRestEndpointFactory();\n"
				+ "  private final RestEndpoint<MyTestCEXMarketDataExchangeInfoRequest, MyTestCEXMarketDataExchangeInfoResponse> exchangeInfoApi;\n"
				+ "  \n"
				+ "  public MyTestCEXMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.restEndpointFactory.setProperties(properties);\n"
				+ "    this.exchangeInfoApi = restEndpointFactory.createRestEndpoint(new MyTestCEXMarketDataExchangeInfoResponseDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestCEXMarketDataExchangeInfoResponse> exchangeInfo(MyTestCEXMarketDataExchangeInfoRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return exchangeInfoApi.call(RestRequest.create(\"https://com.sample.mycex/exchangeInfo\", \"GET\", request));\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoRestEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoRestEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.BarWebsocketEndpointFactory;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestCEXMarketDataTickerStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestCEXMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketMessageTopicMatcherField;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestCEXMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestCEXMarketDataApiImpl implements MyTestCEXMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestCEXMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  \n"
				+ "  private final Properties properties;\n"
				+ "  private final BarWebsocketEndpointFactory websocketEndpointFactory = new BarWebsocketEndpointFactory();\n"
				+ "  private final WebsocketEndpoint<MyTestCEXMarketDataTickerStreamRequest, MyTestCEXMarketDataTickerStreamMessage> tickerStreamWs;\n"
				+ "  \n"
				+ "  public MyTestCEXMarketDataApiImpl(Properties properties) {\n"
				+ "    this.properties = properties;\n"
				+ "    this.websocketEndpointFactory.setApi(this);\n"
				+ "    this.tickerStreamWs = websocketEndpointFactory.createWebsocketEndpoint(new MyTestCEXMarketDataTickerStreamMessageDeserializer());\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public Properties getProperties() {\n"
				+ "    return this.properties;\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStream(MyTestCEXMarketDataTickerStreamRequest request, WebsocketListener<MyTestCEXMarketDataTickerStreamMessage> listener) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStream:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest<MyTestCEXMarketDataTickerStreamRequest> websocketSubscribeRequest = new WebsocketSubscribeRequest<>();\n"
				+ "    websocketSubscribeRequest.setMessageTopicMatcher(new DefaultWebsocketMessageTopicMatcher(WebsocketMessageTopicMatcherField.createList(\"topic\", \"ticker\", \"symbol\", \"\" + request.getSymbol() + \"\")));\n"
				+ "    websocketSubscribeRequest.setParameters(request);\n"
				+ "    return tickerStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
}
