package com.scz.jxapi.generator.java.exchange.constants;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;

import com.scz.jxapi.exchange.descriptor.ConfigProperty;
import com.scz.jxapi.exchange.descriptor.Type;

/**
 * Unit test for {@link PropertiesInterfaceGenerator}
 */
public class PropertiesInterfaceGeneratorTest {

	@Test
    public void testGenerate() {
        ConfigProperty stringProp = ConfigProperty.create("myString", Type.STRING, "My String property", "foo");
        ConfigProperty stringPropWithNoDescriptionNoDefaultValue = ConfigProperty.create("myStringWithNoDescriptionNoDefaultValue", Type.STRING, null, null);
        ConfigProperty intProp = ConfigProperty.create("myInt", Type.INT, "My int property", 42);
        ConfigProperty longProp = ConfigProperty.create("myLong", Type.LONG, "My long property", 1234567890123456L);
        ConfigProperty boolProp = ConfigProperty.create("myBool", Type.BOOLEAN, "My boolean property", true);
        ConfigProperty bigDecimalProp = ConfigProperty.create("myBigDecimal", Type.BIGDECIMAL, "My BigDecimal property", 1.2345);
        PropertiesInterfaceGenerator gen = new PropertiesInterfaceGenerator("com.x.y.MyProperties", "myExchange", 
        		List.of(stringProp, 
        				stringPropWithNoDescriptionNoDefaultValue, 
        				intProp, 
        				longProp, 
        				boolProp, 
        				bigDecimalProp));
        String expected =  "package com.x.y;\n"
        		+ "\n"
        		+ "import java.math.BigDecimal;\n"
        		+ "import java.util.Properties;\n"
        		+ "\n"
        		+ "import com.scz.jxapi.util.PropertiesUtil;\n"
        		+ "\n"
        		+ "/**\n"
        		+ " * Configurable properties for <strong>myExchange</strong> exchange:<br>\n"
        		+ " * <table>\n"
        		+ " *   <tr>\n"
        		+ " *     <th>Name</th>\n"
        		+ " *     <th>Type</th>\n"
        		+ " *     <th>Description</th>\n"
        		+ " *     <th>Default value</th>\n"
        		+ " *   </tr>\n"
        		+ " *   <tr>\n"
        		+ " *     <td>myString</td>\n"
        		+ " *     <td>STRING</td>\n"
        		+ " *     <td>My String property</td>\n"
        		+ " *     <td>foo</td>\n"
        		+ " *   </tr>\n"
        		+ " *   <tr>\n"
        		+ " *     <td>myStringWithNoDescriptionNoDefaultValue</td>\n"
        		+ " *     <td>STRING</td>\n"
        		+ " *     <td></td>\n"
        		+ " *     <td></td>\n"
        		+ " *   </tr>\n"
        		+ " *   <tr>\n"
        		+ " *     <td>myInt</td>\n"
        		+ " *     <td>INT</td>\n"
        		+ " *     <td>My int property</td>\n"
        		+ " *     <td>42</td>\n"
        		+ " *   </tr>\n"
        		+ " *   <tr>\n"
        		+ " *     <td>myLong</td>\n"
        		+ " *     <td>LONG</td>\n"
        		+ " *     <td>My long property</td>\n"
        		+ " *     <td>1234567890123456</td>\n"
        		+ " *   </tr>\n"
        		+ " *   <tr>\n"
        		+ " *     <td>myBool</td>\n"
        		+ " *     <td>BOOLEAN</td>\n"
        		+ " *     <td>My boolean property</td>\n"
        		+ " *     <td>true</td>\n"
        		+ " *   </tr>\n"
        		+ " *   <tr>\n"
        		+ " *     <td>myBigDecimal</td>\n"
        		+ " *     <td>BIGDECIMAL</td>\n"
        		+ " *     <td>My BigDecimal property</td>\n"
        		+ " *     <td>1.2345</td>\n"
        		+ " *   </tr>\n"
        		+ " * </table><br>\n"
        		+ " * Exposes helper methods are available to retrieve value of each of these properties with right type, returning default value if not present in properties\n"
        		+ " */\n"
        		+ "public interface MyProperties {\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * 'myString' property key.<br>\n"
        		+ "   * My String property<br>\n"
        		+ "   * Property value type:STRING\n"
        		+ "   */\n"
        		+ "  String MY_STRING_PROPERTY = \"myString\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * {@link #MY_STRING_PROPERTY} property default value\n"
        		+ "   */\n"
        		+ "  String MY_STRING_DEFAULT_VALUE = \"foo\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * 'myStringWithNoDescriptionNoDefaultValue' property key.<br>\n"
        		+ "   * Property value type:STRING\n"
        		+ "   */\n"
        		+ "  String MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE_PROPERTY = \"myStringWithNoDescriptionNoDefaultValue\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * 'myInt' property key.<br>\n"
        		+ "   * My int property<br>\n"
        		+ "   * Property value type:INT\n"
        		+ "   */\n"
        		+ "  String MY_INT_PROPERTY = \"myInt\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * {@link #MY_INT_PROPERTY} property default value\n"
        		+ "   */\n"
        		+ "  Integer MY_INT_DEFAULT_VALUE = Integer.valueOf(42);\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * 'myLong' property key.<br>\n"
        		+ "   * My long property<br>\n"
        		+ "   * Property value type:LONG\n"
        		+ "   */\n"
        		+ "  String MY_LONG_PROPERTY = \"myLong\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * {@link #MY_LONG_PROPERTY} property default value\n"
        		+ "   */\n"
        		+ "  Long MY_LONG_DEFAULT_VALUE = Long.valueOf(\"1234567890123456\");\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * 'myBool' property key.<br>\n"
        		+ "   * My boolean property<br>\n"
        		+ "   * Property value type:BOOLEAN\n"
        		+ "   */\n"
        		+ "  String MY_BOOL_PROPERTY = \"myBool\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * {@link #MY_BOOL_PROPERTY} property default value\n"
        		+ "   */\n"
        		+ "  Boolean MY_BOOL_DEFAULT_VALUE = Boolean.valueOf(true);\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * 'myBigDecimal' property key.<br>\n"
        		+ "   * My BigDecimal property<br>\n"
        		+ "   * Property value type:BIGDECIMAL\n"
        		+ "   */\n"
        		+ "  String MY_BIG_DECIMAL_PROPERTY = \"myBigDecimal\";\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * {@link #MY_BIG_DECIMAL_PROPERTY} property default value\n"
        		+ "   */\n"
        		+ "  BigDecimal MY_BIG_DECIMAL_DEFAULT_VALUE = new BigDecimal(\"1.2345\");\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * Retrieves value of 'myString' property.\n"
        		+ "   * @param properties Properties to look for value of 'myString' property into.@return Value found in properties or default value 'foo' if not found.\n"
        		+ "   */\n"
        		+ "  default String getMyString(Properties properties) {return PropertiesUtil.getStringProperty(properties, MY_STRING_PROPERTY, MY_STRING_DEFAULT_VALUE);}\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * Retrieves value of 'myStringWithNoDescriptionNoDefaultValue' property.\n"
        		+ "   * @param properties Properties to look for value of 'myStringWithNoDescriptionNoDefaultValue' property into.@return Value found in properties or <code>null</code> if not found.\n"
        		+ "   */\n"
        		+ "  default String getMyStringWithNoDescriptionNoDefaultValue(Properties properties) {return PropertiesUtil.getStringProperty(properties, MY_STRING_WITH_NO_DESCRIPTION_NO_DEFAULT_VALUE_PROPERTY, null);}\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * Retrieves value of 'myInt' property.\n"
        		+ "   * @param properties Properties to look for value of 'myInt' property into.@return Value found in properties or default value '42' if not found.\n"
        		+ "   */\n"
        		+ "  default Integer getMyInt(Properties properties) {return PropertiesUtil.getIntProperty(properties, MY_INT_PROPERTY, MY_INT_DEFAULT_VALUE);}\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * Retrieves value of 'myLong' property.\n"
        		+ "   * @param properties Properties to look for value of 'myLong' property into.@return Value found in properties or default value '1234567890123456' if not found.\n"
        		+ "   */\n"
        		+ "  default Long getMyLong(Properties properties) {return PropertiesUtil.getLongProperty(properties, MY_LONG_PROPERTY, MY_LONG_DEFAULT_VALUE);}\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * Retrieves value of 'myBool' property.\n"
        		+ "   * @param properties Properties to look for value of 'myBool' property into.@return Value found in properties or default value 'true' if not found.\n"
        		+ "   */\n"
        		+ "  default Boolean isMyBool(Properties properties) {return PropertiesUtil.getBooleanProperty(properties, MY_BOOL_PROPERTY, MY_BOOL_DEFAULT_VALUE);}\n"
        		+ "  \n"
        		+ "  /**\n"
        		+ "   * Retrieves value of 'myBigDecimal' property.\n"
        		+ "   * @param properties Properties to look for value of 'myBigDecimal' property into.@return Value found in properties or default value '1.2345' if not found.\n"
        		+ "   */\n"
        		+ "  default BigDecimal getMyBigDecimal(Properties properties) {return PropertiesUtil.getBigDecimalProperty(properties, MY_BIG_DECIMAL_PROPERTY, MY_BIG_DECIMAL_DEFAULT_VALUE);}\n"
        		+ "}\n";
        Assert.assertEquals(expected, gen.generate());
    }
}
