package com.scz.jxapi.generator.exchange.api;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import com.scz.jxapi.exchange.descriptor.ExchangeApiDescriptor;
import com.scz.jxapi.exchange.descriptor.ExchangeDescriptor;
import com.scz.jxapi.exchange.descriptor.ExchangeDescriptorParser;

/**
 * Unit test for {@link ExchangeApiInterfaceImplementationGenerator}
 */
public class ExchangeApiInterfaceImplementationGeneratorTest {

	@Test
	public void testGenerateExchangeApi() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataTickerStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamRequest;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl extends AbstractExchangeApi implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private final MessageDeserializer<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeMarketDataExchangeInfoResponseDeserializer();\n"
				+ "  private final WebsocketEndpoint<MyTestExchangeMarketDataTickerStreamMessage> tickerStreamWs;\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.MarketDataInterceptorFactory\");\n"
				+ "    this.websocketManager = createWebsocketManager(\"wss://com.foo.exchange/ws\", \"com.foo.bar.BarWebsocketFactory\", \"com.foo.bar.BarWebsocketHookFactory\");\n"
				+ "    this.tickerStreamWs = createWebsocketEndpoint(TICKER_STREAM_WS_API, new MyTestExchangeMarketDataTickerStreamMessageDeserializer());\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, null, 0), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStream(MyTestExchangeMarketDataTickerStreamRequest request, WebsocketListener<MyTestExchangeMarketDataTickerStreamMessage> listener) {\n"
				+ "    String topic = EncodingUtil.substituteArguments(\"${symbol}@ticker\", \"symbol\", request.getSymbol());\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStream:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"ticker\", \"symbol\", \"\" + request.getSymbol()));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return tickerStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithGlobalRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(1);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.trading;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.trading.deserializers.MyTestExchangeTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.trading.pojo.MyTestExchangeTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.trading.pojo.MyTestExchangeTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeTradingApiImpl extends AbstractExchangeApi implements MyTestExchangeTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"globalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_TRADING1 = RateLimitRule.createRule(\"Trading1\", 10000, 250);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO = List.of(RATE_LIMIT_GLOBAL_WEIGHT_RULE, RATE_LIMIT_TRADING1);\n"
				+ "  private final MessageDeserializer<MyTestExchangeTradingExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeTradingExchangeInfoResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeTradingApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties, new RequestThrottler(\"MyTestExchangeTrading\"));\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.TradingInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeTradingExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, RATE_LIMITS_EXCHANGE_INFO, 60), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(2);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futuresmarketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.deserializers.MyTestExchangeFuturesMarketDataExchangeInfo2ResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.deserializers.MyTestExchangeFuturesMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfo2Request;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfo2Response;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futuresmarketdata.pojo.MyTestExchangeFuturesMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesMarketDataApiImpl extends AbstractExchangeApi implements MyTestExchangeFuturesMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT = RateLimitRule.createRule(\"exchangeInfoRateLimit\", 3000, 30);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO = List.of(RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO2 = List.of(RATE_LIMIT_EXCHANGE_INFO_RATE_LIMIT);\n"
				+ "  private final MessageDeserializer<MyTestExchangeFuturesMarketDataExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeFuturesMarketDataExchangeInfoResponseDeserializer();\n"
				+ "  private final MessageDeserializer<MyTestExchangeFuturesMarketDataExchangeInfo2Response> exchangeInfo2ResponseDeserializer = new MyTestExchangeFuturesMarketDataExchangeInfo2ResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesMarketDataApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties, new RequestThrottler(\"MyTestExchangeFuturesMarketData\"));\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.FuturesMarketDataInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesMarketDataExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, RATE_LIMITS_EXCHANGE_INFO, 0), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesMarketDataExchangeInfo2Response> exchangeInfo2(MyTestExchangeFuturesMarketDataExchangeInfo2Request request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo2 > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO2_REST_API, \"https://com.sample.mycex/exchangeInfo2\" + urlParameters, HttpMethod.GET, request, RATE_LIMITS_EXCHANGE_INFO2, 0), exchangeInfo2ResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithBothApiGlobalAndEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(3);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl extends AbstractExchangeApi implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"globalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_FUTURES_TRADING1 = RateLimitRule.createRule(\"FuturesTrading1\", 10000, 250);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO1 = RateLimitRule.createRule(\"exchangeInfo1\", 3000, 30);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_CUSTOM_RULE = RateLimitRule.createWeightedRule(\"customRule\", 1500, 300);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO = List.of(RATE_LIMIT_GLOBAL_WEIGHT_RULE, RATE_LIMIT_FUTURES_TRADING1, RATE_LIMIT_EXCHANGE_INFO1, RATE_LIMIT_CUSTOM_RULE);\n"
				+ "  private final MessageDeserializer<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties, new RequestThrottler(\"MyTestExchangeFuturesTrading\"));\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.FuturesTradingInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, RATE_LIMITS_EXCHANGE_INFO, 60), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiWithBothExchangeGlobalAndApiGlobalAndEndpointSpecificRateLimits() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestWithRateLimitRulesAtExchangeLevelDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl extends AbstractExchangeApi implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final RateLimitRule RATE_LIMIT_API_GLOBAL_WEIGHT_RULE = RateLimitRule.createWeightedRule(\"apiGlobalWeightRule\", 2000, 500);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_FUTURES_TRADING1 = RateLimitRule.createRule(\"FuturesTrading1\", 10000, 250);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_EXCHANGE_INFO1 = RateLimitRule.createRule(\"exchangeInfo1\", 3000, 30);\n"
				+ "  private static final RateLimitRule RATE_LIMIT_CUSTOM_RULE = RateLimitRule.createWeightedRule(\"customRule\", 1500, 300);\n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO = List.of(MyTestExchangeExchangeImpl.RATE_LIMIT_EXCHANGE_GLOBAL_RULE, RATE_LIMIT_API_GLOBAL_WEIGHT_RULE, RATE_LIMIT_FUTURES_TRADING1, RATE_LIMIT_EXCHANGE_INFO1, RATE_LIMIT_CUSTOM_RULE);\n"
				+ "  private final MessageDeserializer<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(String exchangeName, Properties properties, RequestThrottler requestThrottler) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties, requestThrottler);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.BarRequestInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, RATE_LIMITS_EXCHANGE_INFO, 60), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",	
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testExchangeApiInterfaceImplementationGeneratorTestOnlyExchangeLevelWeightedLimitRateRuleExchangeDescriptor() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "exchangeApiInterfaceImplementationGeneratorTestOnlyExchangeLevelWeightedLimitRateRuleExchangeDescriptor.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.futurestrading;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchangeImpl;\n"
				+ "import com.foo.bar.gen.futurestrading.deserializers.MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.futurestrading.pojo.MyTestExchangeFuturesTradingExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RateLimitRule;\n"
				+ "import com.scz.jxapi.netutils.rest.ratelimits.RequestThrottler;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeFuturesTradingApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeFuturesTradingApiImpl extends AbstractExchangeApi implements MyTestExchangeFuturesTradingApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeFuturesTradingApiImpl.class);\n"
				+ "  \n"
				+ "  private static final List<RateLimitRule> RATE_LIMITS_EXCHANGE_INFO = List.of(MyTestExchangeExchangeImpl.RATE_LIMIT_EXCHANGE_GLOBAL_RULE);\n"
				+ "  private final MessageDeserializer<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeFuturesTradingExchangeInfoResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeFuturesTradingApiImpl(String exchangeName, Properties properties, RequestThrottler requestThrottler) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties, requestThrottler);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.BarRequestInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeFuturesTradingExchangeInfoResponse> exchangeInfo(MyTestExchangeFuturesTradingExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, RATE_LIMITS_EXCHANGE_INFO, 60), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoWsEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoWebsocketEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataExchangeInfoResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataExchangeInfoResponse;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl extends AbstractExchangeApi implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private final MessageDeserializer<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfoResponseDeserializer = new MyTestExchangeMarketDataExchangeInfoResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.BarRequestInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeMarketDataExchangeInfoResponse> exchangeInfo(MyTestExchangeMarketDataExchangeInfoRequest request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"symbols\", JsonUtil.pojoToJsonString(request.getSymbols()));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET exchangeInfo > \" + request);\n"
				+ "    return submit(HttpRequest.create(EXCHANGE_INFO_REST_API, \"https://com.sample.mycex/exchangeInfo\" + urlParameters, HttpMethod.GET, request, null, 0), exchangeInfoResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiNoRestEndpoint() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorNoRestEndpoint.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.TickerMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.TickerMessage;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl extends AbstractExchangeApi implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private final WebsocketEndpoint<TickerMessage> tickerStreamStringObjectTypeWs;\n"
				+ "  private final WebsocketEndpoint<TickerMessage> tickerStreamStringRequestTypeWs;\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties);\n"
				+ "    this.websocketManager = createWebsocketManager(\"wss://com.foo.exchange/ws\", \"com.foo.bar.BarWebsocketFactory\", \"com.foo.bar.BarWebsocketHookFactory\");\n"
				+ "    this.tickerStreamStringObjectTypeWs = createWebsocketEndpoint(TICKER_STREAM_STRING_OBJECT_TYPE_WS_API, new TickerMessageDeserializer());\n"
				+ "    this.tickerStreamStringRequestTypeWs = createWebsocketEndpoint(TICKER_STREAM_STRING_REQUEST_TYPE_WS_API, new TickerMessageDeserializer());\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStreamStringObjectType(MyTestExchangeMarketDataTickerStreamStringObjectTypeRequest request, WebsocketListener<TickerMessage> listener) {\n"
				+ "    String topic = EncodingUtil.substituteArguments(\"${symbol}@ticker\", \"symbol\", request.getSymbol());\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStreamStringObjectType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"subject\", \"ticker\", \"symbol\", \"\" + request.getSymbol()));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return tickerStreamStringObjectTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStreamStringObjectType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStreamStringObjectType: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamStringObjectTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeTickerStreamStringRequestType(String request, WebsocketListener<TickerMessage> listener) {\n"
				+ "    String topic = EncodingUtil.substituteArguments(\"${symbol}@ticker\", \"symbol\", request);\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeTickerStreamStringRequestType:symbol:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"subject\", \"\" + topic, \"symbol\", \"\" + request));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return tickerStreamStringRequestTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeTickerStreamStringRequestType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeTickerStreamStringRequestType: subscriptionId:\" + subscriptionId);\n"
				+ "    return tickerStreamStringRequestTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificResponseDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestResponseDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataSubscribeTickerMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.MyTestExchangeMarketDataSubscribeTickertMapListStreamMessageDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataSubscribeTickerMessage;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawBigDecimalMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawBooleanMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawIntegerMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawLongMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.RawStringMessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.IntegerJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.MapJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl extends AbstractExchangeApi implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private final MessageDeserializer<Integer> getRestResponseDataTypeIntResponseDeserializer = RawIntegerMessageDeserializer.getInstance();\n"
				+ "  private final MessageDeserializer<Long> getRestResponseDataTypeLongResponseDeserializer = RawLongMessageDeserializer.getInstance();\n"
				+ "  private final MessageDeserializer<BigDecimal> getRestResponseDataTypeBigDecimalResponseDeserializer = RawBigDecimalMessageDeserializer.getInstance();\n"
				+ "  private final MessageDeserializer<String> getRestResponseDataTypeStringResponseDeserializer = RawStringMessageDeserializer.getInstance();\n"
				+ "  private final MessageDeserializer<Boolean> getRestResponseDataTypeBooleanResponseDeserializer = RawBooleanMessageDeserializer.getInstance();\n"
				+ "  private final MessageDeserializer<MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObjectResponseDeserializer = new MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponseDeserializer();\n"
				+ "  private final MessageDeserializer<List<Integer>> getRestResponseDataTypeIntListResponseDeserializer = new ListJsonFieldDeserializer<>(IntegerJsonFieldDeserializer.getInstance());\n"
				+ "  private final MessageDeserializer<Map<String, List<MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMapResponseDeserializer = new MapJsonFieldDeserializer<>(new ListJsonFieldDeserializer<>(new MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponseDeserializer()));\n"
				+ "  private final MessageDeserializer<String> getRestEmptyResponseDataTypeResponseDeserializer = RawStringMessageDeserializer.getInstance();\n"
				+ "  private final WebsocketEndpoint<MyTestExchangeMarketDataSubscribeTickerMessage> subscribeTickerWs;\n"
				+ "  private final WebsocketEndpoint<List<Map<String, MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage>>> subscribeTickertMapListStreamWs;\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.BarRequestInterceptorFactory\");\n"
				+ "    this.websocketManager = createWebsocketManager(\"wss://com.foo.exchange/ws\", \"com.foo.bar.BarWebsocketFactory\", \"com.foo.bar.BarWebsocketHookFactory\");\n"
				+ "    this.subscribeTickerWs = createWebsocketEndpoint(SUBSCRIBE_TICKER_WS_API, new MyTestExchangeMarketDataSubscribeTickerMessageDeserializer());\n"
				+ "    this.subscribeTickertMapListStreamWs = createWebsocketEndpoint(SUBSCRIBE_TICKERT_MAP_LIST_STREAM_WS_API, new ListJsonFieldDeserializer<>(new MapJsonFieldDeserializer<>(new MyTestExchangeMarketDataSubscribeTickertMapListStreamMessageDeserializer())));\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Integer> getRestResponseDataTypeInt() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeInt >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_INT_REST_API, \"https://com.sample.mycex/getInt\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeIntResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Long> getRestResponseDataTypeLong() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeLong >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_LONG_REST_API, \"https://com.sample.mycex/getLong\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeLongResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<BigDecimal> getRestResponseDataTypeBigDecimal() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeBigDecimal >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_BIG_DECIMAL_REST_API, \"https://com.sample.mycex/getBigDecimal\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeBigDecimalResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<String> getRestResponseDataTypeString() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeString >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_STRING_REST_API, \"https://com.sample.mycex/getString\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeStringResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Boolean> getRestResponseDataTypeBoolean() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeBoolean >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_BOOLEAN_REST_API, \"https://com.sample.mycex/getBigDecimal\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeBooleanResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<MyTestExchangeMarketDataGetRestResponseDataTypeObjectResponse> getRestResponseDataTypeObject() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeObject >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_OBJECT_REST_API, \"https://com.sample.mycex/getBigDecimal\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeObjectResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<List<Integer>> getRestResponseDataTypeIntList() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeIntList >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_INT_LIST_REST_API, \"https://com.sample.mycex/getIntList\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeIntListResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<Map<String, List<MyTestExchangeMarketDataGetRestResponseDataTypeObjectListMapResponse>>> getRestResponseDataTypeObjectListMap() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestResponseDataTypeObjectListMap >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_RESPONSE_DATA_TYPE_OBJECT_LIST_MAP_REST_API, \"https://com.sample.mycex/getObjectlistMap\", HttpMethod.GET, null, null, 0), getRestResponseDataTypeObjectListMapResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<String> getRestEmptyResponseDataType() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestEmptyResponseDataType >\");\n"
				+ "    return submit(HttpRequest.create(GET_REST_EMPTY_RESPONSE_DATA_TYPE_REST_API, \"https://com.sample.mycex/getEmptyResponse\", HttpMethod.GET, null, null, 0), getRestEmptyResponseDataTypeResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeSubscribeTicker(WebsocketListener<MyTestExchangeMarketDataSubscribeTickerMessage> listener) {\n"
				+ "    String topic = \"subscribeTickerTopic\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeSubscribeTicker\");\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(null, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"tickerMapList\"));\n"
				+ "    return subscribeTickerWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeSubscribeTicker(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeSubscribeTicker: subscriptionId:\" + subscriptionId);\n"
				+ "    return subscribeTickerWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeSubscribeTickertMapListStream(WebsocketListener<List<Map<String, MyTestExchangeMarketDataSubscribeTickertMapListStreamMessage>>> listener) {\n"
				+ "    String topic = \"subscribeTickerMapListTopic\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeSubscribeTickertMapListStream\");\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(null, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"tickerMapList\"));\n"
				+ "    return subscribeTickertMapListStreamWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeSubscribeTickertMapListStream(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeSubscribeTickertMapListStream: subscriptionId:\" + subscriptionId);\n"
				+ "    return subscribeTickertMapListStreamWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiSpecificRequestDataTypes() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorWithAllRestRequestDataTypes.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.marketdata;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeExchange;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.GenericResponseDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.deserializers.TickerDeserializer;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.GenericResponse;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.SingleSymbol;\n"
				+ "import com.foo.bar.gen.marketdata.pojo.Ticker;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.netutils.websocket.DefaultWebsocketMessageTopicMatcher;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketEndpoint;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketListener;\n"
				+ "import com.scz.jxapi.netutils.websocket.WebsocketSubscribeRequest;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import java.math.BigDecimal;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Map;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeMarketDataApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeMarketDataApiImpl extends AbstractExchangeApi implements MyTestExchangeMarketDataApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeMarketDataApiImpl.class);\n"
				+ "  \n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeIntResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeLongResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeBigDecimalResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeStringResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeBooleanResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeObjectNoParametersResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeObjectOneParameterResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeIntListResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeObjectListMapResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithObjectRequestDataTypeZeroParametersWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithObjectRequestDataTypeOneParameterWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithIntRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithLongRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithBigDecimalRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithStringRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithBooleanRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithStringListRequestDataTypeWs;\n"
				+ "  private final WebsocketEndpoint<Ticker> streamWithObjectListMapRequestDataTypeWs;\n"
				+ "  \n"
				+ "  public MyTestExchangeMarketDataApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeExchange.ID, properties);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.BarRequestInterceptorFactory\");\n"
				+ "    this.websocketManager = createWebsocketManager(\"wss://com.foo.exchange/ws\", \"com.foo.bar.BarWebsocketFactory\", \"com.foo.bar.BarWebsocketHookFactory\");\n"
				+ "    this.streamWithObjectRequestDataTypeZeroParametersWs = createWebsocketEndpoint(STREAM_WITH_OBJECT_REQUEST_DATA_TYPE_ZERO_PARAMETERS_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithObjectRequestDataTypeOneParameterWs = createWebsocketEndpoint(STREAM_WITH_OBJECT_REQUEST_DATA_TYPE_ONE_PARAMETER_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithIntRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_INT_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithLongRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_LONG_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithBigDecimalRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_BIG_DECIMAL_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithStringRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_STRING_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithBooleanRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_BOOLEAN_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithStringListRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_STRING_LIST_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "    this.streamWithObjectListMapRequestDataTypeWs = createWebsocketEndpoint(STREAM_WITH_OBJECT_LIST_MAP_REQUEST_DATA_TYPE_WS_API, new TickerDeserializer());\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeInt(Integer request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeInt > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_INT_REST_API, \"https://com.sample.mycex/postInt\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeIntResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeLong(Long request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeLong > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_LONG_REST_API, \"https://com.sample.mycex/postLong\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeLongResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeBigDecimal(BigDecimal request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeBigDecimal > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_BIG_DECIMAL_REST_API, \"https://com.sample.mycex/postBigDecimal\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeBigDecimalResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeString(String request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeString > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_STRING_REST_API, \"https://com.sample.mycex/postString\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeStringResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeBoolean(Boolean request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeBoolean > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_BOOLEAN_REST_API, \"https://com.sample.mycex/postBoolean\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeBooleanResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectNoParameters() {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeObjectNoParameters >\");\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_OBJECT_NO_PARAMETERS_REST_API, \"https://com.sample.mycex/postNoParameter\", HttpMethod.POST, null, null, 0), postRestRequestDataTypeObjectNoParametersResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectOneParameter(MyTestExchangeMarketDataPostRestRequestDataTypeObjectOneParameterRequest request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeObjectOneParameter > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_OBJECT_ONE_PARAMETER_REST_API, \"https://com.sample.mycex/postBigDecimal\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeObjectOneParameterResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeIntList(List<Integer> request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeIntList > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_INT_LIST_REST_API, \"https://com.sample.mycex/postBigDecimal\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeIntListResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeObjectListMap(Map<String, List<SingleSymbol>> request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeObjectListMap > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_OBJECT_LIST_MAP_REST_API, \"https://com.sample.mycex/postBigDecimal\", HttpMethod.POST, request, null, 0), postRestRequestDataTypeObjectListMapResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithObjectRequestDataTypeZeroParameters(WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithObjectRequestDataTypeZeroParameters\");\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(null, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithObjectRequestDataTypeZeroParametersTopic\"));\n"
				+ "    return streamWithObjectRequestDataTypeZeroParametersWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithObjectRequestDataTypeZeroParameters(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithObjectRequestDataTypeZeroParameters: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithObjectRequestDataTypeZeroParametersWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithObjectRequestDataTypeOneParameter(SingleSymbol request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = EncodingUtil.substituteArguments(\"ticker\");\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithObjectRequestDataTypeOneParameter:symbolObj:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"\" + topic));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithObjectRequestDataTypeOneParameterWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithObjectRequestDataTypeOneParameter(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithObjectRequestDataTypeOneParameter: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithObjectRequestDataTypeOneParameterWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithIntRequestDataType(Integer request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithIntRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithIntRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithIntRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithIntRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithIntRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithIntRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithLongRequestDataType(Long request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithLongRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithLongRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithLongRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithLongRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithLongRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithLongRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithBigDecimalRequestDataType(BigDecimal request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithBigDecimalRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithBigDecimalRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithBigDecimalRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithBigDecimalRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithBigDecimalRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithBigDecimalRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithStringRequestDataType(String request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithStringRequestDataType:symbol:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithStringRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithStringRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithStringRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithStringRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithStringRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithBooleanRequestDataType(Boolean request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithBooleanRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithBooleanRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithBooleanRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithBooleanRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithBooleanRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithBooleanRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithStringListRequestDataType(List<String> request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = \"ticker\";\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithStringListRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithBooleanRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithStringListRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithStringListRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithStringListRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithStringListRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public String subscribeStreamWithObjectListMapRequestDataType(Map<String, List<SingleSymbol>> request, WebsocketListener<Ticker> listener) {\n"
				+ "    String topic = EncodingUtil.substituteArguments(\"ticker\");\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"subscribeStreamWithObjectListMapRequestDataType:request:\" + request);\n"
				+ "    WebsocketSubscribeRequest websocketSubscribeRequest = WebsocketSubscribeRequest.create(request, topic, DefaultWebsocketMessageTopicMatcher.create(\"topic\", \"streamWithObjectListMapRequestDataTypeTopic\"));\n"
				+ "    websocketSubscribeRequest.setRequest(request);\n"
				+ "    return streamWithObjectListMapRequestDataTypeWs.subscribe(websocketSubscribeRequest, listener);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public boolean unsubscribeStreamWithObjectListMapRequestDataType(String subscriptionId) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"unsubscribeStreamWithObjectListMapRequestDataType: subscriptionId:\" + subscriptionId);\n"
				+ "    return streamWithObjectListMapRequestDataTypeWs.unsubscribe(subscriptionId);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",
				apiInterfaceGenerator.generate());
	}
	
	@Test
	public void testGenerateExchangeApiDifferentRestEndpointQueryParamsDefinitions() throws Exception {
		ExchangeDescriptor exchangeDescriptor = new ExchangeDescriptorParser().fromJson(Paths.get(".", "src", "test", "resources", "testExchangeDescriptorAllUrlQueryParamsDefinitions.json"));
		ExchangeApiDescriptor exchangeApiDescriptor = exchangeDescriptor.getApis().get(0);
		ExchangeApiInterfaceImplementationGenerator apiInterfaceGenerator = new ExchangeApiInterfaceImplementationGenerator(exchangeDescriptor, exchangeApiDescriptor);
		Assert.assertEquals("package com.foo.bar.gen.restapi;\n"
				+ "\n"
				+ "import com.foo.bar.gen.MyTestExchangeWithDifferentUrlQueryParamsExchange;\n"
				+ "import com.foo.bar.gen.restapi.deserializers.GenericResponseDeserializer;\n"
				+ "import com.foo.bar.gen.restapi.pojo.GenericResponse;\n"
				+ "import com.foo.bar.gen.restapi.pojo.Person;\n"
				+ "import com.foo.bar.gen.restapi.pojo.PersonFilter;\n"
				+ "import com.scz.jxapi.exchange.AbstractExchangeApi;\n"
				+ "import com.scz.jxapi.netutils.deserialization.MessageDeserializer;\n"
				+ "import com.scz.jxapi.netutils.deserialization.json.field.ListJsonFieldDeserializer;\n"
				+ "import com.scz.jxapi.netutils.rest.FutureRestResponse;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpMethod;\n"
				+ "import com.scz.jxapi.netutils.rest.HttpRequest;\n"
				+ "import com.scz.jxapi.util.EncodingUtil;\n"
				+ "import com.scz.jxapi.util.JsonUtil;\n"
				+ "import java.util.List;\n"
				+ "import java.util.Properties;\n"
				+ "import org.slf4j.Logger;\n"
				+ "import org.slf4j.LoggerFactory;\n"
				+ "\n"
				+ "/**\n"
				+ " * Actual implementation of {@link MyTestExchangeWithDifferentUrlQueryParamsRestApiApi}<br/>\n"
				+ " * <br><strong>THIS CODE IS GENERATED. DO NOT EDIT MANUALLY!</strong>\n"
				+ " */\n"
				+ "public class MyTestExchangeWithDifferentUrlQueryParamsRestApiApiImpl extends AbstractExchangeApi implements MyTestExchangeWithDifferentUrlQueryParamsRestApiApi {\n"
				+ "  \n"
				+ "  private static final Logger log = LoggerFactory.getLogger(MyTestExchangeWithDifferentUrlQueryParamsRestApiApiImpl.class);\n"
				+ "  \n"
				+ "  private final MessageDeserializer<GenericResponse> getRestRequestDataTypeIntResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> getRestRequestDataTypeObjectResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<List<GenericResponse>> getRestRequestDataTypeStringListResponseDeserializer = new ListJsonFieldDeserializer<>(new GenericResponseDeserializer());\n"
				+ "  private final MessageDeserializer<GenericResponse> deleteRestRequestDataTypeIntResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> deleteRestRequestDataTypeIntAsQueryParamResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> deleteRestRequestDataTypeObjectResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> putRestRequestDataTypeObjectResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> putRestRequestDataTypeObjectResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> putRestRequestDataTypeObjectUsingCustomQueryParamsResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> putRestRequestDataTypeObjectUsingDefaultQueryParamsResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  private final MessageDeserializer<GenericResponse> postRestRequestDataTypeIntListAsQueryParamResponseDeserializer = new GenericResponseDeserializer();\n"
				+ "  \n"
				+ "  public MyTestExchangeWithDifferentUrlQueryParamsRestApiApiImpl(String exchangeName, Properties properties) {\n"
				+ "    super(ID, exchangeName, MyTestExchangeWithDifferentUrlQueryParamsExchange.ID, properties);\n"
				+ "    this.httpRequestExecutor = createHttpRequestExecutor(null);\n"
				+ "    this.httpRequestInterceptor = createHttpRequestInterceptor(\"com.foo.bar.BarHttpRequestInterceptorFactory\");\n"
				+ "  }\n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> getRestRequestDataTypeInt(Integer request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"id\", request);\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestRequestDataTypeInt > \" + request);\n"
				+ "    return submit(HttpRequest.create(GET_REST_REQUEST_DATA_TYPE_INT_REST_API, \"https://com.sample.myexchange/getRestRequestDataTypeInt\" + urlParameters, HttpMethod.GET, request, null, 0), getRestRequestDataTypeIntResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> getRestRequestDataTypeObject(PersonFilter request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"age\", request.getAge(), \"city\", request.getCity());\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestRequestDataTypeObject > \" + request);\n"
				+ "    return submit(HttpRequest.create(GET_REST_REQUEST_DATA_TYPE_OBJECT_REST_API, \"https://com.sample.myexchange/getRestRequestDataTypeObject\" + urlParameters, HttpMethod.GET, request, null, 0), getRestRequestDataTypeObjectResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<List<GenericResponse>> getRestRequestDataTypeStringList(List<String> request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"ids\", JsonUtil.pojoToJsonString(request));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"GET getRestRequestDataTypeStringList > \" + request);\n"
				+ "    return submit(HttpRequest.create(GET_REST_REQUEST_DATA_TYPE_STRING_LIST_REST_API, \"https://com.sample.myexchange/getRestRequestDataTypeStringList\" + urlParameters, HttpMethod.GET, request, null, 0), getRestRequestDataTypeStringListResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> deleteRestRequestDataTypeInt(Integer request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"id\", request);\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"DELETE deleteRestRequestDataTypeInt > \" + request);\n"
				+ "    return submit(HttpRequest.create(DELETE_REST_REQUEST_DATA_TYPE_INT_REST_API, \"https://com.sample.myexchange/deleteRestRequestDataTypeInt\" + urlParameters, HttpMethod.DELETE, request, null, 0), deleteRestRequestDataTypeIntResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> deleteRestRequestDataTypeIntAsQueryParam(Integer request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"id\", request);\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"DELETE deleteRestRequestDataTypeIntAsQueryParam > \" + request);\n"
				+ "    return submit(HttpRequest.create(DELETE_REST_REQUEST_DATA_TYPE_INT_AS_QUERY_PARAM_REST_API, \"https://com.sample.myexchange/deleteRestRequestDataTypeIntAsQueryParam\" + urlParameters, HttpMethod.DELETE, request, null, 0), deleteRestRequestDataTypeIntAsQueryParamResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> deleteRestRequestDataTypeObject(PersonFilter request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"age\", request.getAge(), \"city\", request.getCity());\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"DELETE deleteRestRequestDataTypeObject > \" + request);\n"
				+ "    return submit(HttpRequest.create(DELETE_REST_REQUEST_DATA_TYPE_OBJECT_REST_API, \"https://com.sample.myexchange/deleteRestRequestDataTypeObject\" + urlParameters, HttpMethod.DELETE, request, null, 0), deleteRestRequestDataTypeObjectResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> putRestRequestDataTypeObject(Person request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"PUT putRestRequestDataTypeObject > \" + request);\n"
				+ "    return submit(HttpRequest.create(PUT_REST_REQUEST_DATA_TYPE_OBJECT_REST_API, \"https://com.sample.myexchange/putRestRequestDataTypeObject\", HttpMethod.PUT, request, null, 0), putRestRequestDataTypeObjectResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> putRestRequestDataTypeObject(Person request) {\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"PUT putRestRequestDataTypeObject > \" + request);\n"
				+ "    return submit(HttpRequest.create(PUT_REST_REQUEST_DATA_TYPE_OBJECT_REST_API, \"https://com.sample.myexchange/putRestRequestDataTypeObject\", HttpMethod.PUT, request, null, 0), putRestRequestDataTypeObjectResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> putRestRequestDataTypeObjectUsingCustomQueryParams(Person request) {\n"
				+ "    String urlParameters = EncodingUtil.substituteArguments(\"?id=${id}&name=${name}&age=${age}&city=${city}\", \"id\", request.getId(), \"name\", request.getName(), \"age\", request.getAge(), \"city\", request.getCity());\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"PUT putRestRequestDataTypeObjectUsingCustomQueryParams > \" + request);\n"
				+ "    return submit(HttpRequest.create(PUT_REST_REQUEST_DATA_TYPE_OBJECT_USING_CUSTOM_QUERY_PARAMS_REST_API, \"https://com.sample.myexchange/putRestRequestDataTypeObjectUsingCustomQueryParams\" + urlParameters, HttpMethod.PUT, request, null, 0), putRestRequestDataTypeObjectUsingCustomQueryParamsResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> putRestRequestDataTypeObjectUsingDefaultQueryParams(Person request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"id\", request.getId(), \"name\", request.getName(), \"age\", request.getAge(), \"city\", request.getCity());\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"PUT putRestRequestDataTypeObjectUsingDefaultQueryParams > \" + request);\n"
				+ "    return submit(HttpRequest.create(PUT_REST_REQUEST_DATA_TYPE_OBJECT_USING_DEFAULT_QUERY_PARAMS_REST_API, \"https://com.sample.myexchange/putRestRequestDataTypeObjectUsingDefaultQueryParams\" + urlParameters, HttpMethod.PUT, request, null, 0), putRestRequestDataTypeObjectUsingDefaultQueryParamsResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "  @Override\n"
				+ "  public FutureRestResponse<GenericResponse> postRestRequestDataTypeIntListAsQueryParam(List<Integer> request) {\n"
				+ "    String urlParameters = EncodingUtil.createUrlQueryParameters(\"intListArg\", JsonUtil.pojoToJsonString(request));\n"
				+ "    if (log.isDebugEnabled())\n"
				+ "      log.debug(\"POST postRestRequestDataTypeIntListAsQueryParam > \" + request);\n"
				+ "    return submit(HttpRequest.create(POST_REST_REQUEST_DATA_TYPE_INT_LIST_AS_QUERY_PARAM_REST_API, \"https://com.sample.myexchange/postRestRequestDataTypeIntListAsQueryParam\" + urlParameters, HttpMethod.POST, request, null, 0), postRestRequestDataTypeIntListAsQueryParamResponseDeserializer);\n"
				+ "  }\n"
				+ "  \n"
				+ "}\n"
				+ "",
				apiInterfaceGenerator.generate());
	}
}
